import { PIU_DADI, inc, type Voce } from "./incantesimiSottoclassi.ts";

// Trucchetti e incantesimi di 1° livello del Manuale del Giocatore che non sono altrove nel catalogo
// (descrizioni riassunte, non il testo del manuale).

const AUMENTO_TRUCCHETTO = "I danni aumentano al 5°, 11° e 17° livello del personaggio.";

export const VOCI_M0_1: Record<string, Voce> = {
  // --- Trucchetti ---
  "Spruzzo Acido": inc(["Mago", "Stregone"], 0, "Evocazione", "1 azione", "18 metri", "V, S", "Istantanea",
    "Una bolla di acido colpisce una creatura entro gittata (o due creature adiacenti): chi fallisce il tiro salvezza subisce 1d6 danni da acido.",
    { tiroSalvezza: { car: "DES", effetto: "nessun effetto" }, danni: { dado: "1d6", tipo: "da acido", trucchetto: true }, livelloSuperiore: AUMENTO_TRUCCHETTO }),
  "Artificio Druidico": inc(["Druido"], 0, "Trasmutazione", "1 azione", "9 metri", "V, S, M (un ramoscello di agrifoglio)", "Istantanea",
    "Piccoli prodigi della natura: prevedere il tempo del giorno dopo, far fiorire una pianta, produrre un effetto sensoriale innocuo o accendere o spegnere una fiamma piccola."),
  "Deflagrazione Occulta": inc(["Warlock"], 0, "Invocazione", "1 azione", "36 metri", "V, S", "Istantanea",
    "Un raggio di energia crepitante: attacco a distanza con incantesimo, 1d10 danni da forza. Al 5°, 11° e 17° livello i raggi diventano 2, 3 e 4, ciascuno con un proprio attacco (ripeti il lancio per ogni raggio).",
    { attacco: { numero: 1 }, danni: { dado: "1d10", tipo: "da forza", perAttacco: true } }),
  "Amicizia": inc(["Bardo", "Mago", "Stregone", "Warlock"], 0, "Ammaliamento", "1 azione", "Incantatore", "S, M (un po' di trucco)", "Concentrazione, fino a 1 minuto",
    "L'incantatore ha vantaggio alle prove di Carisma contro una creatura non ostile. Alla fine dell'incantesimo la creatura capisce di essere stata influenzata e diventa ostile."),
  "Guida": inc(["Chierico", "Druido"], 0, "Divinazione", "1 azione", "Contatto", "V, S", "Concentrazione, fino a 1 minuto",
    "Una creatura consenziente toccata può tirare 1d4 e aggiungerlo a una prova di caratteristica a sua scelta, una volta, prima che l'incantesimo termini."),
  "Luce": inc(["Bardo", "Chierico", "Mago", "Stregone"], 0, "Invocazione", "1 azione", "Contatto", "V, M (una lucciola o muschio fosforescente)", "1 ora",
    "Un oggetto toccato emana luce intensa per 6 metri e fioca per altri 6. Se l'oggetto è tenuto da una creatura ostile, questa può evitarlo con il tiro salvezza.",
    { tiroSalvezza: { car: "DES", effetto: "nessun effetto" } }),
  "Mano Magica": inc(["Bardo", "Mago", "Stregone", "Warlock"], 0, "Evocazione", "1 azione", "9 metri", "V, S", "1 minuto",
    "Una mano spettrale fluttuante manipola un oggetto, apre una porta o un contenitore, o recupera e ripone un oggetto, con un'azione a turno. Trasporta fino a 5 kg e non attacca."),
  "Riparare": inc(["Bardo", "Chierico", "Druido", "Mago", "Stregone"], 0, "Trasmutazione", "1 minuto", "Contatto", "V, S, M (due calamite)", "Istantanea",
    "Ripara una singola rottura o lacerazione in un oggetto toccato (una catena rotta, uno strappo nel mantello), purché la rottura non superi 30 cm. Non ripara oggetti magici."),
  "Messaggio": inc(["Bardo", "Mago", "Stregone"], 0, "Trasmutazione", "1 azione", "36 metri", "V, S, M (un filo di rame)", "1 round",
    "Sussurra un messaggio a una creatura entro gittata, l'unica a sentirlo, che può rispondere sottovoce. Può attraversare ostacoli, ma non il piombo o il silenzio magico."),
  "Spruzzo Velenoso": inc(["Druido", "Mago", "Stregone", "Warlock"], 0, "Necromanzia", "1 azione", "3 metri", "V, S", "Istantanea",
    "Un'esalazione velenosa investe una creatura entro gittata: se fallisce il tiro salvezza subisce 1d12 danni da veleno.",
    { tiroSalvezza: { car: "COS", effetto: "nessun effetto" }, danni: { dado: "1d12", tipo: "da veleno", trucchetto: true }, livelloSuperiore: AUMENTO_TRUCCHETTO }),
  "Prestidigitazione": inc(["Bardo", "Mago", "Stregone", "Warlock"], 0, "Trasmutazione", "1 azione", "3 metri", "V, S", "Fino a 1 ora",
    "Piccoli trucchi magici: effetti sensoriali, accendere o spegnere una fiamma, pulire o sporcare un oggetto, scaldare, raffreddare o insaporire materiale, fare un segno o un simbolo. Fino a tre effetti attivi insieme."),
  "Produrre Fiamma": inc(["Druido"], 0, "Evocazione", "1 azione", "Incantatore", "V, S", "10 minuti",
    "Una fiamma tremolante appare in una mano dell'incantatore e fa luce. Con un'azione può scagliarla a 9 metri: attacco a distanza con incantesimo, 1d8 danni da fuoco.",
    { attacco: { numero: 1 }, danni: { dado: "1d8", tipo: "da fuoco", trucchetto: true, perAttacco: true }, livelloSuperiore: AUMENTO_TRUCCHETTO }),
  "Raggio di Gelo": inc(["Mago", "Stregone"], 0, "Invocazione", "1 azione", "18 metri", "V, S", "Istantanea",
    "Un raggio gelido: attacco a distanza con incantesimo, 1d8 danni da freddo. Il bersaglio colpito ha la velocità ridotta di 3 metri fino all'inizio del turno successivo dell'incantatore.",
    { attacco: { numero: 1 }, danni: { dado: "1d8", tipo: "da freddo", trucchetto: true, perAttacco: true }, livelloSuperiore: AUMENTO_TRUCCHETTO }),
  "Resistenza": inc(["Chierico", "Druido"], 0, "Abiurazione", "1 azione", "Contatto", "V, S, M (un mantello in miniatura)", "Concentrazione, fino a 1 minuto",
    "Una creatura consenziente toccata può tirare 1d4 e aggiungerlo a un tiro salvezza a sua scelta, una volta, prima che l'incantesimo termini."),
  "Fiamma Sacra": inc(["Chierico"], 0, "Invocazione", "1 azione", "18 metri", "V, S", "Istantanea",
    "Una luce simile a una fiamma scende su una creatura entro gittata: se fallisce il tiro salvezza subisce 1d8 danni radiosi. Il bersaglio non ottiene benefici dalla copertura.",
    { tiroSalvezza: { car: "DES", effetto: "nessun effetto" }, danni: { dado: "1d8", tipo: "radiosi", trucchetto: true }, livelloSuperiore: AUMENTO_TRUCCHETTO }),
  "Randello Incantato": inc(["Druido"], 0, "Trasmutazione", "1 azione bonus", "Contatto", "V, S, M (vischio, foglia di trifoglio, bastone o clava)", "1 minuto",
    "Il bastone o la clava impugnati diventano armi magiche: per attaccare si usa la Saggezza al posto di Forza e il dado di danno è un d8. L'incantesimo termina se l'incantatore lascia l'arma."),
  "Presa Folgorante": inc(["Mago", "Stregone"], 0, "Invocazione", "1 azione", "Contatto", "V, S", "Istantanea",
    "Attacco in mischia con incantesimo, con vantaggio se il bersaglio indossa armatura di metallo: 1d8 danni da fulmine e il bersaglio non può usare reazioni fino all'inizio del suo turno.",
    { attacco: { numero: 1 }, danni: { dado: "1d8", tipo: "da fulmine", trucchetto: true, perAttacco: true }, livelloSuperiore: AUMENTO_TRUCCHETTO }),
  "Stabilizzare": inc(["Chierico"], 0, "Necromanzia", "1 azione", "Contatto", "V, S", "Istantanea",
    "Una creatura vivente toccata a 0 punti ferita diventa stabile. Non ha effetto su non morti e costrutti."),
  "Colpo Accurato": inc(["Bardo", "Mago", "Stregone", "Warlock"], 0, "Divinazione", "1 azione", "9 metri", "S", "Concentrazione, fino a 1 round",
    "L'incantatore intuisce le difese di una creatura: nel suo turno successivo ha vantaggio al primo tiro per colpire contro di essa."),
  "Beffa Crudele": inc(["Bardo"], 0, "Ammaliamento", "1 azione", "18 metri", "V", "Istantanea",
    "Una raffica di insulti magici: se il bersaglio fallisce il tiro salvezza subisce 1d4 danni psichici e ha svantaggio al prossimo tiro per colpire prima della fine del suo turno successivo.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" }, danni: { dado: "1d4", tipo: "psichici", trucchetto: true }, livelloSuperiore: AUMENTO_TRUCCHETTO }),

  // --- 1° livello ---
  "Allarme": inc(["Mago", "Ranger"], 1, "Abiurazione", "1 minuto", "9 metri", "V, S, M (un campanello e un filo d'argento)", "8 ore",
    "Sorveglia una porta, una finestra o un'area di massimo un cubo di 6 metri: un allarme mentale o sonoro avvisa l'incantatore quando una creatura Minuscola o più grande la attraversa.",
    { rituale: true }),
  "Armatura di Agathys": inc(["Warlock"], 1, "Abiurazione", "1 azione", "Incantatore", "V, S, M (una tazza d'acqua)", "1 ora",
    "Una forza gelida dà all'incantatore 5 PF temporanei. Finché li ha, chi lo colpisce in mischia subisce 5 danni da freddo.",
    { livelloSuperiore: "PF temporanei e danni da freddo aumentano di 5 per ogni livello di slot oltre il 1°." }),
  "Braccia di Hadar": inc(["Warlock"], 1, "Evocazione", "1 azione", "Incantatore (raggio di 3 metri)", "V, S", "Istantanea",
    "Tentacoli di energia oscura emergono dall'incantatore: le creature entro 3 metri subiscono 2d6 danni necrotici e non possono usare reazioni fino al proprio turno successivo; con un tiro salvezza superato i danni sono dimezzati.",
    { tiroSalvezza: { car: "FOR", effetto: "metà danni e può usare reazioni" }, danni: { dado: "2d6", tipo: "necrotici", perLivello: "1d6" }, livelloSuperiore: PIU_DADI("1d6") }),
  "Sfera Cromatica": inc(["Mago", "Stregone"], 1, "Invocazione", "1 azione", "27 metri", "V, S, M (un diamante da 50 mo)", "Istantanea",
    "Scaglia una sfera di energia di un tipo a scelta (acido, freddo, fuoco, fulmine, tuono o veleno): attacco a distanza con incantesimo, 3d8 danni del tipo scelto.",
    { attacco: { numero: 1 }, danni: { dado: "3d8", tipo: "dell'energia scelta", perLivello: "1d8", perAttacco: true }, livelloSuperiore: PIU_DADI("1d8") }),
  "Spruzzo Colorato": inc(["Mago", "Stregone"], 1, "Illusione", "1 azione", "Incantatore (cono di 4,5 metri)", "V, S, M (un pizzico di polvere o sabbia colorata)", "1 round",
    "Un cono di luci scintillanti: tira 6d10 e partendo dalla creatura con meno PF accecano le creature finché il totale basta (PF attuali), fino alla fine del turno successivo dell'incantatore. Gli incoscienti e i ciechi sono ignorati.",
    { livelloSuperiore: "+2d10 al totale per ogni livello di slot oltre il 1°." }),
  "Duello Obbligato": inc(["Paladino"], 1, "Ammaliamento", "1 azione bonus", "9 metri", "V", "Concentrazione, fino a 1 minuto",
    "Una creatura che fallisce il tiro salvezza è costretta a concentrarsi sull'incantatore: ha svantaggio ai tiri contro altri bersagli e non può muoversi volontariamente lontano oltre 9 metri. L'effetto termina se l'incantatore attacca altri o lancia incantesimi su altri.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Comprensione dei Linguaggi": inc(["Bardo", "Mago", "Stregone", "Warlock"], 1, "Divinazione", "1 azione", "Incantatore", "V, S, M (un pizzico di fuliggine e sale)", "1 ora",
    "L'incantatore capisce il significato letterale di ogni linguaggio parlato che sente e di ogni testo che tocca. Non rivela messaggi in codice o messaggi segreti.",
    { rituale: true }),
  "Creare o Distruggere Acqua": inc(["Chierico", "Druido"], 1, "Trasmutazione", "1 azione", "9 metri", "V, S, M (una goccia d'acqua o polvere)", "Istantanea",
    "Crea fino a 40 litri d'acqua pulita in contenitori aperti, o la fa cadere come pioggia in un cubo di 9 metri; oppure distrugge la stessa quantità d'acqua o nebbia in un cubo di 9 metri.",
    { livelloSuperiore: "Quantità e area aumentano di 40 litri e di 1,5 metri di spigolo per ogni livello di slot oltre il 1°." }),
  "Individuazione del Bene e del Male": inc(["Chierico", "Paladino"], 1, "Divinazione", "1 azione", "Incantatore", "V, S", "Concentrazione, fino a 10 minuti",
    "Entro 9 metri l'incantatore percepisce la presenza e la posizione di aberrazioni, celestiali, elementali, folletti, immondi e non morti, e di luoghi o oggetti consacrati o dissacrati."),
  "Individuazione di Veleni e Malattie": inc(["Chierico", "Druido", "Paladino", "Ranger"], 1, "Divinazione", "1 azione", "Incantatore", "V, S, M (una foglia di tasso)", "Concentrazione, fino a 10 minuti",
    "Entro 9 metri l'incantatore percepisce veleni, creature velenose e malattie, il loro tipo e la loro posizione.",
    { rituale: true }),
  "Intralciare": inc(["Druido"], 1, "Evocazione", "1 azione", "27 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Erbe e rampicanti coprono un quadrato di 6 metri: è terreno difficile e le creature che falliscono il tiro salvezza sono trattenute finché dura. Una creatura trattenuta può usare un'azione per tentare una prova di Forza e liberarsi.",
    { tiroSalvezza: { car: "FOR", effetto: "non è trattenuta" } }),
  "Falsa Vita": inc(["Mago", "Stregone"], 1, "Necromanzia", "1 azione", "Incantatore", "V, S, M (un po' di alcol o liquore)", "1 ora",
    "L'incantatore ottiene 1d4 + 4 punti ferita temporanei per la durata.",
    { livelloSuperiore: "+5 PF temporanei per ogni livello di slot oltre il 1°." }),
  "Caduta Morbida": inc(["Bardo", "Mago", "Stregone"], 1, "Trasmutazione", "1 reazione, quando l'incantatore o una creatura entro gittata cade", "18 metri", "V, M (una piccola piuma)", "1 minuto",
    "Fino a cinque creature in caduta rallentano la discesa a 18 metri per round e non subiscono danni da caduta se atterrano prima della fine dell'incantesimo."),
  "Trova Famiglio": inc(["Mago"], 1, "Evocazione", "1 ora", "3 metri", "V, S, M (carbone, incenso e erbe per 10 mo, in un braciere di ottone)", "Istantanea",
    "L'incantatore ottiene un famiglio (un animale piccolo con forma di folletto, celestiale o immondo): ci comunica a telepatia entro 30 metri, ne usa i sensi con un'azione e può far consegnare incantesimi a contatto. Se scende a 0 PF sparisce.",
    { rituale: true }),
  "Bacche Benefiche": inc(["Druido", "Ranger"], 1, "Trasmutazione", "1 azione", "Contatto", "V, S, M (un rametto di vischio)", "Istantanea",
    "Fino a dieci bacche toccate diventano magiche per 24 ore. Mangiarne una (azione) ridà 1 PF e basta come cibo di una giornata."),
  "Unto": inc(["Mago"], 1, "Evocazione", "1 azione", "18 metri", "V, S, M (burro o grasso di maiale)", "1 minuto",
    "Grasso scivoloso copre un quadrato di 3 metri: è terreno difficile e chi vi si trova all'inizio del turno, entra o vi finisce il movimento deve superare il tiro salvezza o cade prono.",
    { tiroSalvezza: { car: "DES", effetto: "non cade prono" } }),
  "Dardo Guida": inc(["Chierico"], 1, "Invocazione", "1 azione", "36 metri", "V, S", "1 round",
    "Un lampo di luce: attacco a distanza con incantesimo, 4d6 danni radiosi. Il prossimo attacco contro il bersaglio prima della fine del turno successivo dell'incantatore ha vantaggio.",
    { attacco: { numero: 1 }, danni: { dado: "4d6", tipo: "radiosi", perLivello: "1d6", perAttacco: true }, livelloSuperiore: PIU_DADI("1d6") }),
  "Pioggia di Spine": inc(["Ranger"], 1, "Evocazione", "1 azione bonus", "Incantatore", "V", "Concentrazione, fino a 1 minuto",
    "Il prossimo colpo a distanza con un'arma a distanza fa piovere spine: il bersaglio e le creature entro 1,5 metri subiscono 1d10 danni perforanti (metà se superano il tiro salvezza).",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "1d10", tipo: "perforanti", perLivello: "1d10" }, livelloSuperiore: PIU_DADI("1d10") }),
  "Parola Guaritrice": inc(["Bardo", "Chierico", "Druido"], 1, "Invocazione", "1 azione bonus", "18 metri", "V", "Istantanea",
    "Una creatura visibile entro gittata recupera 1d4 + il modificatore di caratteristica da incantatore punti ferita. Non ha effetto su non morti e costrutti.",
    { livelloSuperiore: "+1d4 PF per ogni livello di slot oltre il 1°." }),
  "Rimprovero Infernale": inc(["Warlock"], 1, "Invocazione", "1 reazione, quando l'incantatore subisce danni da una creatura visibile entro 18 metri", "18 metri", "V, S", "Istantanea",
    "L'incantatore indica l'aggressore, avvolto da fiamme infernali: subisce 2d10 danni da fuoco (metà con il tiro salvezza superato).",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "2d10", tipo: "da fuoco", perLivello: "1d10" }, livelloSuperiore: PIU_DADI("1d10") }),
  "Eroismo": inc(["Bardo", "Paladino"], 1, "Ammaliamento", "1 azione", "Contatto", "V, S", "Concentrazione, fino a 1 minuto",
    "Una creatura toccata è immune alla condizione di spaventato e all'inizio di ogni suo turno ottiene PF temporanei pari al modificatore di caratteristica da incantatore.",
    { livelloSuperiore: "Una creatura in più per ogni livello di slot oltre il 1°." }),
  "Maleficio": inc(["Warlock"], 1, "Ammaliamento", "1 azione bonus", "27 metri", "V, S, M (l'occhio pietrificato di un tritone)", "Concentrazione, fino a 1 ora",
    "L'incantatore maledice una creatura: infligge 1d6 danni necrotici extra quando la colpisce con un attacco e il bersaglio ha svantaggio alle prove di una caratteristica a scelta. Se scende a 0 PF si può spostare la maledizione.",
    { livelloSuperiore: "Con uno slot di 3° o 4° livello dura fino a 8 ore, con uno di 5° o superiore fino a 24 ore." }),
  "Scrittura Illusoria": inc(["Bardo", "Mago", "Warlock"], 1, "Illusione", "1 minuto", "Contatto", "S, M (inchiostro da 10 mo)", "10 giorni",
    "L'incantatore scrive su carta o pergamena un messaggio che solo i lettori designati comprendono: gli altri vedono una scrittura incomprensibile o un testo diverso.",
    { rituale: true }),
  "Infliggere Ferite": inc(["Chierico"], 1, "Necromanzia", "1 azione", "Contatto", "V, S", "Istantanea",
    "Attacco in mischia con incantesimo: 3d10 danni necrotici.",
    { attacco: { numero: 1 }, danni: { dado: "3d10", tipo: "necrotici", perLivello: "1d10", perAttacco: true }, livelloSuperiore: PIU_DADI("1d10") }),
  "Salto": inc(["Druido", "Mago", "Ranger", "Stregone"], 1, "Trasmutazione", "1 azione", "Contatto", "V, S, M (la zampa di una cavalletta)", "1 minuto",
    "La distanza di salto della creatura toccata triplica per la durata."),
  "Passo Lungo": inc(["Bardo", "Druido", "Mago", "Ranger"], 1, "Trasmutazione", "1 azione", "Contatto", "V, S, M (un pizzico di terra)", "1 ora",
    "La velocità della creatura toccata aumenta di 3 metri per la durata.",
    { livelloSuperiore: "Una creatura in più per ogni livello di slot oltre il 1°." }),
  "Armatura Magica": inc(["Mago", "Stregone"], 1, "Abiurazione", "1 azione", "Contatto", "V, S, M (un pezzo di cuoio conciato)", "8 ore",
    "Una creatura consenziente senza armatura è protetta da una forza magica: la sua CA base diventa 13 + il modificatore di Destrezza. L'incantesimo termina se indossa un'armatura."),
  "Purificare Cibo e Bevande": inc(["Chierico", "Druido", "Paladino"], 1, "Trasmutazione", "1 azione", "3 metri", "V, S", "Istantanea",
    "Il cibo e le bevande non magici in una sfera di 1,5 metri di raggio sono liberati da veleni e malattie.",
    { rituale: true }),
  "Immagine Silenziosa": inc(["Bardo", "Mago", "Stregone"], 1, "Illusione", "1 azione", "18 metri", "V, S, M (un po' di vello)", "Concentrazione, fino a 10 minuti",
    "Crea l'immagine di un oggetto, una creatura o un fenomeno, non più grande di un cubo di 4,5 metri: solo visiva, senza suoni, odori o altro. Un'interazione fisica rivela che è un'illusione."),
  "Servitore Invisibile": inc(["Bardo", "Mago", "Warlock"], 1, "Evocazione", "1 azione", "18 metri", "V, S, M (un pezzo di corda e di legno)", "1 ora",
    "Una forza invisibile, priva di mente e di forma, esegue semplici compiti a comando entro gittata: portare, aprire porte, pulire. Ha CA 10, 1 PF e Forza 2; non attacca.",
    { rituale: true }),
  "Dardo Stregato": inc(["Mago", "Stregone", "Warlock"], 1, "Invocazione", "1 azione", "9 metri", "V, S, M (un ramo di un albero colpito da un fulmine)", "Concentrazione, fino a 1 minuto",
    "Un raggio crepitante collega l'incantatore a un bersaglio: attacco a distanza con incantesimo, 1d12 danni da fulmine. Finché la concentrazione dura, con un'azione l'incantatore infligge altri 1d12 senza nuovo attacco.",
    { attacco: { numero: 1 }, danni: { dado: "1d12", tipo: "da fulmine", perLivello: "1d12", perAttacco: true }, livelloSuperiore: PIU_DADI("1d12") }),
  "Punizione Furente": inc(["Paladino"], 1, "Invocazione", "1 azione bonus", "Incantatore", "V", "Concentrazione, fino a 1 minuto",
    "Il prossimo colpo con un'arma infligge 1d6 danni psichici extra e il bersaglio deve superare un tiro salvezza su Saggezza o è spaventato dall'incantatore (lo ripete a ogni turno per terminare l'effetto).",
    { tiroSalvezza: { car: "SAG", effetto: "non è spaventato" } }),
  "Punizione Tonante": inc(["Paladino"], 1, "Invocazione", "1 azione bonus", "Incantatore", "V", "Concentrazione, fino a 1 minuto",
    "Il prossimo colpo in mischia con un'arma infligge 2d6 danni da tuono extra, si ode a 90 metri e, se il bersaglio fallisce il tiro salvezza su Forza, è spinto di 3 metri e cade prono.",
    { tiroSalvezza: { car: "FOR", effetto: "non è spinto né prono" } }),
  "Punizione Ustionante": inc(["Paladino"], 1, "Invocazione", "1 azione bonus", "Incantatore", "V", "Concentrazione, fino a 1 minuto",
    "Il prossimo colpo in mischia con un'arma infligge 1d6 danni da fuoco extra e il bersaglio prende fuoco: subisce 1d6 danni da fuoco all'inizio di ogni suo turno finché non supera un tiro salvezza su Costituzione.",
    { tiroSalvezza: { car: "COS", effetto: "il fuoco si spegne" }, livelloSuperiore: PIU_DADI("1d6") }),
  "Disco Fluttuante di Tenser": inc(["Mago"], 1, "Evocazione", "1 azione", "9 metri", "V, S, M (una goccia di mercurio)", "1 ora",
    "Un disco di forza orizzontale di 90 cm di diametro fluttua a 90 cm da terra e segue l'incantatore portando fino a 250 kg.",
    { rituale: true }),
};
