import type { SchedaIncantesimo } from "../../src/tipi.ts";
import type { NomeClasse } from "../../src/dati/classi.ts";

// Incantesimi di dominio, giuramento, circolo e patrono (src/dati/incantesimiSottoclasse.ts) che non erano già
// nel catalogo, con le classi che li hanno nella propria lista. Descrizioni riassunte, non il testo del manuale.
// Le classi di ogni voce vanno nella tabella `incantesimo_classi`.

type Voce = { classi: NomeClasse[]; scheda: SchedaIncantesimo };

type Extra = Partial<Pick<SchedaIncantesimo, "rituale" | "livelloSuperiore" | "attacco" | "tiroSalvezza" | "danni">>;

// La concentrazione si ricava dalla durata ("Concentrazione, fino a...").
const inc = (
  classi: NomeClasse[], livello: number, scuola: string, tempo: string, gittata: string, componenti: string, durata: string,
  descrizione: string, extra: Extra = {},
): Voce => ({
  classi,
  scheda: {
    livello, scuola, tempo, gittata, componenti, durata,
    concentrazione: durata.startsWith("Concentrazione"), rituale: false, descrizione, ...extra,
  },
});

const PIU_DADI = (dado: string) => `Con uno slot di livello superiore, +${dado} per ogni livello oltre il base.`;

export const VOCI_SOTTOCLASSI: Record<string, Voce> = {
  // --- 1° livello ---
  "Amicizia con gli Animali": inc(["Bardo", "Druido", "Ranger"], 1, "Ammaliamento", "1 azione", "9 metri", "V, S, M", "24 ore",
    "Una bestia con Intelligenza 3 o meno che l'incantatore vede diventa amichevole con lui se fallisce il tiro salvezza. L'effetto termina se l'incantatore o i suoi compagni la danneggiano.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" }, livelloSuperiore: "Una bestia in più per ogni livello di slot oltre il 1°." }),
  "Anatema": inc(["Bardo", "Chierico"], 1, "Ammaliamento", "1 azione", "9 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Fino a tre creature che falliscono il tiro salvezza sottraggono 1d4 ai tiri per colpire e ai tiri salvezza finché dura l'incantesimo.",
    { tiroSalvezza: { car: "CAR", effetto: "nessun effetto" }, livelloSuperiore: "Una creatura in più per ogni livello di slot oltre il 1°." }),
  "Benedizione": inc(["Chierico", "Paladino"], 1, "Ammaliamento", "1 azione", "9 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Fino a tre creature aggiungono 1d4 ai tiri per colpire e ai tiri salvezza finché dura l'incantesimo.",
    { livelloSuperiore: "Una creatura in più per ogni livello di slot oltre il 1°." }),
  "Camuffare Se Stesso": inc(["Bardo", "Mago", "Stregone"], 1, "Illusione", "1 azione", "Incantatore", "V, S", "1 ora",
    "L'incantatore cambia aspetto, vestiti ed equipaggiamento: può sembrare fino a 30 cm più alto o più basso, più magro o più robusto, ma non cambiare tipo di corpo. Chi esamina da vicino può accorgersene con una prova di Intelligenza (Indagare) contro la CD dell'incantesimo."),
  "Colpo Intrappolante": inc(["Ranger"], 1, "Evocazione", "1 azione bonus", "Incantatore", "V", "Concentrazione, fino a 1 minuto",
    "Il prossimo colpo con un'arma fa spuntare rovi attorno al bersaglio: se fallisce il tiro salvezza è trattenuto e subisce 1d6 danni perforanti all'inizio di ogni suo turno. Una creatura Grande o più grande ha vantaggio al tiro salvezza; ci si libera con una prova di Forza contro la CD.",
    { tiroSalvezza: { car: "FOR", effetto: "i rovi si seccano" }, livelloSuperiore: "+1d6 danni per ogni livello di slot oltre il 1°." }),
  "Comando": inc(["Chierico", "Paladino"], 1, "Ammaliamento", "1 azione", "18 metri", "V", "1 round",
    "L'incantatore pronuncia un ordine di una parola (avvicinati, lascia, fuggi, cadi, fermo...) a una creatura che lo capisce: se fallisce il tiro salvezza, obbedisce nel suo turno successivo. Non ha effetto sui non morti né se l'ordine è direttamente dannoso.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" }, livelloSuperiore: "Una creatura in più per ogni livello di slot oltre il 1°." }),
  "Cura Ferite": inc(["Bardo", "Chierico", "Druido", "Paladino", "Ranger"], 1, "Invocazione", "1 azione", "Contatto", "V, S", "Istantanea",
    "Una creatura toccata recupera 1d8 + il modificatore di caratteristica da incantatore punti ferita. Non ha effetto su non morti e costrutti.",
    { livelloSuperiore: "+1d8 PF per ogni livello di slot oltre il 1°." }),
  "Favore Divino": inc(["Paladino"], 1, "Invocazione", "1 azione bonus", "Incantatore", "V, S", "Concentrazione, fino a 1 minuto",
    "Gli attacchi con le armi dell'incantatore infliggono 1d4 danni radiosi aggiuntivi quando colpiscono."),
  "Identificare": inc(["Bardo", "Mago"], 1, "Divinazione", "1 minuto", "Contatto", "V, S, M", "Istantanea",
    "L'incantatore apprende le proprietà magiche di un oggetto toccato (come usarlo, cariche, sintonia) o gli incantesimi che hanno effetto su una creatura o un oggetto.",
    { rituale: true }),
  "Luminescenza": inc(["Bardo", "Druido"], 1, "Invocazione", "1 azione", "18 metri", "V", "Concentrazione, fino a 1 minuto",
    "Gli oggetti e le creature in un cubo di 6 metri di spigolo che falliscono il tiro salvezza sono avvolti da una luce fioca: non possono essere invisibili e gli attacchi contro di loro hanno vantaggio.",
    { tiroSalvezza: { car: "DES", effetto: "nessun effetto" } }),
  "Marchio del Cacciatore": inc(["Ranger"], 1, "Divinazione", "1 azione bonus", "27 metri", "V", "Concentrazione, fino a 1 ora",
    "L'incantatore marchia una creatura come sua preda: le infligge 1d6 danni extra quando la colpisce con un attacco con arma e ha vantaggio alle prove di Saggezza (Percezione o Sopravvivenza) per trovarla. Se il bersaglio scende a 0 PF può spostare il marchio con un'azione bonus.",
    { livelloSuperiore: "Con uno slot di 3° o 4° livello dura fino a 8 ore, con uno slot di 5° o superiore fino a 24 ore." }),
  "Nube di Nebbia": inc(["Druido", "Mago", "Ranger", "Stregone"], 1, "Evocazione", "1 azione", "36 metri", "V, S", "Concentrazione, fino a 1 ora",
    "Crea una sfera di nebbia di 6 metri di raggio: l'area è in oscurità pesante. Un vento moderato la disperde.",
    { livelloSuperiore: "Il raggio aumenta di 6 metri per ogni livello di slot oltre il 1°." }),
  "Parlare con gli Animali": inc(["Bardo", "Druido", "Ranger"], 1, "Divinazione", "1 azione", "Incantatore", "V, S", "10 minuti",
    "L'incantatore comprende le bestie e può comunicare con loro: sanno dargli informazioni semplici sui luoghi e sulle creature vicine.",
    { rituale: true }),
  "Protezione dal Bene e dal Male": inc(["Chierico", "Mago", "Paladino", "Warlock"], 1, "Abiurazione", "1 azione", "Contatto", "V, S, M", "Concentrazione, fino a 10 minuti",
    "Una creatura consenziente è protetta da aberrazioni, celestiali, elementali, folletti, immondi e non morti: hanno svantaggio ad attaccarla e non possono affascinarla, spaventarla o possederla."),
  "Santuario": inc(["Chierico"], 1, "Abiurazione", "1 azione bonus", "9 metri", "V, S, M", "1 minuto",
    "Chi vuole attaccare la creatura protetta o bersagliarla con un incantesimo dannoso deve prima superare un tiro salvezza su Saggezza, altrimenti sceglie un altro bersaglio. Termina se la creatura protetta attacca o lancia un incantesimo che colpisce un nemico.",
    { tiroSalvezza: { car: "SAG", effetto: "può attaccare la creatura protetta" } }),
  "Scudo della Fede": inc(["Chierico", "Paladino"], 1, "Abiurazione", "1 azione bonus", "18 metri", "V, S, M", "Concentrazione, fino a 10 minuti",
    "Un campo scintillante circonda una creatura a scelta: +2 alla CA finché dura l'incantesimo."),
  "Sonno": inc(["Bardo", "Mago", "Stregone"], 1, "Ammaliamento", "1 azione", "27 metri", "V, S, M", "1 minuto",
    "Si tirano 5d8: le creature entro 6 metri dal punto scelto cadono addormentate a partire da quella con meno PF attuali, finché il totale lo permette. Non ha effetto su non morti e su chi non può essere affascinato. Il danno o una creatura che usa un'azione le svegliano.",
    { livelloSuperiore: "+2d8 al totale per ogni livello di slot oltre il 1°." }),
  "Sussurri Dissonanti": inc(["Bardo"], 1, "Ammaliamento", "1 azione", "18 metri", "V", "Istantanea",
    "Una melodia udibile solo dal bersaglio: se fallisce il tiro salvezza subisce 3d6 danni psichici e deve usare subito la reazione per allontanarsi il più possibile dall'incantatore. Se lo supera subisce la metà dei danni. Non ha effetto sulle creature sorde.",
    { tiroSalvezza: { car: "SAG", effetto: "metà danni e non fugge" }, danni: { dado: "3d6", tipo: "psichici", perLivello: "1d6" }, livelloSuperiore: PIU_DADI("1d6") }),

  // --- 2° livello ---
  "Arma Magica": inc(["Mago", "Paladino"], 2, "Trasmutazione", "1 azione bonus", "Contatto", "V, S", "Concentrazione, fino a 1 ora",
    "Un'arma non magica diventa un'arma magica +1 agli attacchi e ai danni.",
    { livelloSuperiore: "+2 con uno slot di 4° livello, +3 con uno slot di 6° o superiore." }),
  "Arma Spirituale": inc(["Chierico"], 2, "Invocazione", "1 azione bonus", "18 metri", "V, S", "1 minuto",
    "Crea un'arma spettrale fluttuante: al lancio e con un'azione bonus nei turni successivi (spostandola di 6 metri) fa un attacco con incantesimo in mischia che infligge 1d8 + il modificatore di caratteristica da incantatore danni da forza.",
    { attacco: { numero: 1 }, danni: { dado: "1d8", tipo: "da forza", perAttacco: true }, livelloSuperiore: "+1d8 per ogni due livelli di slot oltre il 2°." }),
  "Augurio": inc(["Chierico"], 2, "Divinazione", "1 minuto", "Incantatore", "V, S, M", "Istantanea",
    "L'incantatore riceve un presagio su un'azione che intende compiere entro 30 minuti: fortuna, sventura, entrambe o nessuna delle due. Lanciato più volte prima di un riposo lungo, rischia una risposta casuale.",
    { rituale: true }),
  "Calmare Emozioni": inc(["Bardo", "Chierico"], 2, "Ammaliamento", "1 azione", "18 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Gli umanoidi in una sfera di 6 metri di raggio che falliscono il tiro salvezza (chi vuole può fallirlo) perdono gli effetti che li affascinano o spaventano, oppure diventano indifferenti verso le creature che l'incantatore sceglie.",
    { tiroSalvezza: { car: "CAR", effetto: "nessun effetto" } }),
  "Cecità/Sordità": inc(["Bardo", "Chierico", "Mago", "Stregone"], 2, "Necromanzia", "1 azione", "9 metri", "V", "1 minuto",
    "Un nemico che fallisce il tiro salvezza diventa accecato o assordato, a scelta dell'incantatore. Ripete il tiro salvezza alla fine di ogni suo turno.",
    { tiroSalvezza: { car: "COS", effetto: "nessun effetto" }, livelloSuperiore: "Un bersaglio in più per ogni livello di slot oltre il 2°." }),
  "Crescita di Spine": inc(["Druido", "Ranger"], 2, "Trasmutazione", "1 azione", "45 metri", "V, S, M", "Concentrazione, fino a 10 minuti",
    "Il terreno in un raggio di 6 metri si copre di spine mimetizzate: è terreno difficile e chi vi si muove subisce 2d4 danni perforanti ogni 1,5 metri percorsi. Chi non l'ha visto lanciare deve superare una prova di Saggezza (Percezione) per accorgersene.",
    { danni: { dado: "2d4", tipo: "perforanti" } }),
  "Folata di Vento": inc(["Druido", "Mago", "Stregone"], 2, "Invocazione", "1 azione", "Incantatore (linea di 18 metri)", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Una linea di vento forte (18 × 3 metri) parte dall'incantatore: chi inizia il turno nella linea e fallisce il tiro salvezza viene spinto di 4,5 metri; muoversi contro vento costa il doppio. Disperde gas e nebbie e spegne le fiamme libere.",
    { tiroSalvezza: { car: "FOR", effetto: "non viene spinto" } }),
  "Forza Fantasma": inc(["Bardo", "Mago", "Stregone"], 2, "Illusione", "1 azione", "18 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Un'illusione di un oggetto o una creatura (fino a un cubo di 3 metri) visibile solo al bersaglio, che la crede reale se fallisce il tiro salvezza. Può infliggere 1d6 danni psichici a turno a chi si trova dentro o accanto al fantasma.",
    { tiroSalvezza: { car: "INT", effetto: "nessun effetto" }, danni: { dado: "1d6", tipo: "psichici" } }),
  "Freccia Acida di Melf": inc(["Mago"], 2, "Invocazione", "1 azione", "27 metri", "V, S, M", "Istantanea",
    "Una freccia verde colpisce con un attacco con incantesimo a distanza: 4d4 danni da acido subito e 2d4 alla fine del turno successivo del bersaglio. Se manca, metà dei danni iniziali e niente danni successivi.",
    { attacco: { numero: 1 }, danni: { dado: "4d4", tipo: "da acido", perLivello: "1d4", perAttacco: true }, livelloSuperiore: "I danni (iniziali e successivi) aumentano di 1d4 per ogni livello di slot oltre il 2°." }),
  "Frantumare": inc(["Bardo", "Mago", "Stregone", "Warlock"], 2, "Invocazione", "1 azione", "18 metri", "V, S, M", "Istantanea",
    "Un rumore assordante in una sfera di 3 metri di raggio: 3d8 danni da tuono (metà con il tiro salvezza). Le creature di pietra, cristallo o metallo hanno svantaggio al tiro salvezza; gli oggetti non trasportati subiscono i danni.",
    { tiroSalvezza: { car: "COS", effetto: "metà danni" }, danni: { dado: "3d8", tipo: "da tuono", perLivello: "1d8" }, livelloSuperiore: PIU_DADI("1d8") }),
  "Individuazione dei Pensieri": inc(["Bardo", "Mago", "Stregone"], 2, "Divinazione", "1 azione", "Incantatore", "V, S, M", "Concentrazione, fino a 1 minuto",
    "L'incantatore legge i pensieri superficiali di una creatura entro 9 metri; con un'azione può sondarne la mente più a fondo (tiro salvezza su Saggezza per resistere). Percepisce anche la presenza di creature pensanti nascoste.",
    { tiroSalvezza: { car: "SAG", effetto: "la sonda termina" } }),
  "Invisibilità": inc(["Bardo", "Mago", "Stregone", "Warlock"], 2, "Illusione", "1 azione", "Contatto", "V, S, M", "Concentrazione, fino a 1 ora",
    "Una creatura toccata e ciò che indossa o trasporta diventano invisibili. L'incantesimo termina se il bersaglio attacca o lancia un incantesimo.",
    { livelloSuperiore: "Un bersaglio in più per ogni livello di slot oltre il 2°." }),
  "Movimenti del Ragno": inc(["Mago", "Stregone", "Warlock"], 2, "Trasmutazione", "1 azione", "Contatto", "V, S, M", "Concentrazione, fino a 1 ora",
    "Una creatura consenziente può muoversi su pareti e soffitti con le mani libere, e ottiene una velocità di scalare pari alla sua velocità."),
  "Oscurità": inc(["Mago", "Stregone", "Warlock"], 2, "Invocazione", "1 azione", "18 metri", "V, M", "Concentrazione, fino a 10 minuti",
    "Un'oscurità magica riempie una sfera di 4,5 metri di raggio: nemmeno la scurovisione vi vede e la luce non magica non la illumina. Se è centrata su un oggetto si sposta con esso."),
  "Passare Senza Tracce": inc(["Druido", "Ranger"], 2, "Abiurazione", "1 azione", "Incantatore", "V, S, M", "Concentrazione, fino a 1 ora",
    "L'incantatore e le creature scelte entro 9 metri da lui ottengono +10 alle prove di Destrezza (Furtività) e non lasciano tracce, se non con la magia."),
  "Passo Velato": inc(["Mago", "Stregone", "Warlock"], 2, "Evocazione", "1 azione bonus", "Incantatore", "V", "Istantanea",
    "Avvolto da una nebbia argentea, l'incantatore si teletrasporta fino a 9 metri in uno spazio libero che vede."),
  "Pelle Coriacea": inc(["Druido", "Ranger"], 2, "Trasmutazione", "1 azione", "Contatto", "V, S, M", "Concentrazione, fino a 1 ora",
    "La pelle di una creatura consenziente diventa dura come corteccia: la sua CA non può essere inferiore a 16, qualunque armatura indossi."),
  "Raggio Lunare": inc(["Druido"], 2, "Invocazione", "1 azione", "36 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Un cilindro di luce lunare di 1,5 metri di raggio: chi vi entra per la prima volta in un turno o vi inizia il turno subisce 2d10 danni radiosi (metà con il tiro salvezza); i mutaforma hanno svantaggio e riprendono la loro forma. Con un'azione si sposta di 18 metri.",
    { tiroSalvezza: { car: "COS", effetto: "metà danni" }, danni: { dado: "2d10", tipo: "radiosi", perLivello: "1d10" }, livelloSuperiore: PIU_DADI("1d10") }),
  "Ragnatela": inc(["Mago", "Stregone"], 2, "Evocazione", "1 azione", "18 metri", "V, S, M", "Concentrazione, fino a 1 ora",
    "Ragnatele appiccicose riempiono un cubo di 6 metri di spigolo: sono terreno difficile e oscurità leggera, e chi vi entra o vi inizia il turno resta trattenuto se fallisce il tiro salvezza (si libera con una prova di Forza). Bruciano facilmente.",
    { tiroSalvezza: { car: "DES", effetto: "non è trattenuto" } }),
  "Ristorare Inferiore": inc(["Bardo", "Chierico", "Druido", "Paladino", "Ranger"], 2, "Abiurazione", "1 azione", "Contatto", "V, S", "Istantanea",
    "Una creatura toccata guarisce da una malattia o da una condizione tra accecato, assordato, avvelenato e paralizzato."),
  "Sfera Infuocata": inc(["Druido", "Mago"], 2, "Evocazione", "1 azione", "18 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Una sfera di fuoco di 1,5 metri di diametro: chi termina il turno entro 1,5 metri da essa subisce 2d6 danni da fuoco (metà con il tiro salvezza). Con un'azione bonus la si sposta di 9 metri e, se urta una creatura, questa fa il tiro salvezza.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "2d6", tipo: "da fuoco", perLivello: "1d6" }, livelloSuperiore: PIU_DADI("1d6") }),
  "Sfocatura": inc(["Mago", "Stregone"], 2, "Illusione", "1 azione", "Incantatore", "V", "Concentrazione, fino a 1 minuto",
    "Il corpo dell'incantatore diventa sfocato: le creature che lo attaccano hanno svantaggio, salvo che non vedano con vista cieca o vista pura."),
  "Silenzio": inc(["Bardo", "Chierico", "Ranger"], 2, "Illusione", "1 azione", "36 metri", "V, S", "Concentrazione, fino a 10 minuti",
    "Nessun suono esiste in una sfera di 6 metri di raggio: chi vi si trova è immune ai danni da tuono, assordato e non può lanciare incantesimi con componente verbale.",
    { rituale: true }),
  "Suggestione": inc(["Bardo", "Mago", "Stregone", "Warlock"], 2, "Ammaliamento", "1 azione", "9 metri", "V, M", "Concentrazione, fino a 8 ore",
    "L'incantatore suggerisce un'azione ragionevole (una o due frasi) a una creatura che lo capisce: se fallisce il tiro salvezza la persegue al meglio delle sue capacità. Termina se l'incantatore o i suoi compagni la danneggiano.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Zona di Verità": inc(["Bardo", "Chierico", "Paladino"], 2, "Ammaliamento", "1 azione", "18 metri", "V, S", "10 minuti",
    "In una sfera di 4,5 metri di raggio chi fallisce il tiro salvezza non può mentire deliberatamente; l'incantatore sa chi l'ha superato. Chi ne è influenzato può evitare di rispondere.",
    { tiroSalvezza: { car: "CAR", effetto: "può mentire" } }),

  // --- 3° livello ---
  "Anti-Individuazione": inc(["Bardo", "Mago", "Ranger"], 3, "Abiurazione", "1 azione", "Contatto", "V, S, M", "8 ore",
    "Una creatura consenziente, un luogo o un oggetto non possono essere bersagliati dalla magia di divinazione né percepiti con sensori magici di scrutamento."),
  "Camminare sull'Acqua": inc(["Chierico", "Druido", "Ranger", "Stregone"], 3, "Trasmutazione", "1 azione", "9 metri", "V, S, M", "1 ora",
    "Fino a dieci creature consenzienti possono camminare su qualsiasi liquido (anche acido o lava, subendone però i danni) come su terreno solido.",
    { rituale: true }),
  "Chiaroveggenza": inc(["Bardo", "Chierico", "Mago", "Stregone"], 3, "Divinazione", "10 minuti", "1,5 chilometri", "V, S, M", "Concentrazione, fino a 10 minuti",
    "Crea un sensore invisibile in un luogo conosciuto: l'incantatore può vedere o sentire (a scelta) attraverso di esso."),
  "Creare Cibo e Acqua": inc(["Chierico", "Paladino"], 3, "Evocazione", "1 azione", "9 metri", "V, S", "Istantanea",
    "Crea cibo e acqua sufficienti per quindici umanoidi o cinque cavalcature per 24 ore. Il cibo si guasta dopo 24 ore se non viene mangiato."),
  "Dissolvi Magie": inc(["Bardo", "Chierico", "Druido", "Mago", "Paladino", "Stregone", "Warlock"], 3, "Abiurazione", "1 azione", "36 metri", "V, S", "Istantanea",
    "Termina gli incantesimi di 3° livello o inferiore su una creatura, un oggetto o un effetto magico. Per quelli di livello superiore serve una prova di caratteristica da incantatore con CD 10 + il loro livello.",
    { livelloSuperiore: "Termina automaticamente gli incantesimi di livello pari o inferiore allo slot usato." }),
  "Faro di Speranza": inc(["Chierico"], 3, "Abiurazione", "1 azione", "9 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Le creature scelte hanno vantaggio ai tiri salvezza su Saggezza e contro morte, e recuperano il massimo dei punti ferita possibili da ogni cura."),
  "Fondersi nella Pietra": inc(["Chierico", "Druido"], 3, "Trasmutazione", "1 azione", "Contatto", "V, S", "8 ore",
    "L'incantatore entra in un blocco di pietra abbastanza grande da contenerlo e vi resta nascosto. Se la pietra viene distrutta o modellata ne viene espulso subendo danni.",
    { rituale: true }),
  "Forma Gassosa": inc(["Mago", "Stregone", "Warlock"], 3, "Trasmutazione", "1 azione", "Contatto", "V, S, M", "Concentrazione, fino a 1 ora",
    "Una creatura consenziente diventa una nube nebulosa: vola a 3 metri, passa attraverso piccole fessure, ha resistenza ai danni non magici e vantaggio ai tiri salvezza su FOR, DES e COS, ma non può attaccare né lanciare incantesimi."),
  "Fulmine": inc(["Mago", "Stregone"], 3, "Invocazione", "1 azione", "Incantatore (linea di 30 metri)", "V, S, M", "Istantanea",
    "Un fulmine in una linea di 30 × 1,5 metri: 8d6 danni da fulmine (metà con il tiro salvezza). Incendia gli oggetti infiammabili non trasportati.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "8d6", tipo: "da fulmine", perLivello: "1d6" }, livelloSuperiore: PIU_DADI("1d6") }),
  "Guardiani Spirituali": inc(["Chierico"], 3, "Evocazione", "1 azione", "Incantatore (raggio di 4,5 metri)", "V, S, M", "Concentrazione, fino a 10 minuti",
    "Spiriti protettivi circondano l'incantatore: per i nemici l'area è terreno difficile e chi vi entra per la prima volta in un turno o vi inizia il turno subisce 3d8 danni radiosi (o necrotici, per un incantatore malvagio), metà con il tiro salvezza.",
    { tiroSalvezza: { car: "SAG", effetto: "metà danni" }, danni: { dado: "3d8", tipo: "radiosi", perLivello: "1d8" }, livelloSuperiore: PIU_DADI("1d8") }),
  "Intermittenza": inc(["Mago", "Stregone"], 3, "Trasmutazione", "1 azione", "Incantatore", "V, S", "1 minuto",
    "Alla fine di ogni suo turno l'incantatore tira un d20: con 11 o più svanisce nel Piano Etereo fino all'inizio del turno successivo, quando riappare entro 3 metri dal punto di partenza."),
  "Inviare": inc(["Bardo", "Chierico", "Mago"], 3, "Evocazione", "1 azione", "Illimitata", "V, S, M", "1 round",
    "Un messaggio di massimo 25 parole raggiunge una creatura conosciuta, ovunque si trovi, che può rispondere subito allo stesso modo. Su un altro piano c'è il 5% di probabilità che non arrivi."),
  "Invocare il Fulmine": inc(["Druido"], 3, "Evocazione", "1 azione", "36 metri", "V, S", "Concentrazione, fino a 10 minuti",
    "Una nube temporalesca: al lancio e con un'azione nei turni successivi un fulmine colpisce un punto, infliggendo 3d10 danni da fulmine entro 1,5 metri (metà con il tiro salvezza). All'aperto durante una tempesta infligge 1d10 in più.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "3d10", tipo: "da fulmine", perLivello: "1d10" }, livelloSuperiore: PIU_DADI("1d10") }),
  "Lentezza": inc(["Mago", "Stregone"], 3, "Trasmutazione", "1 azione", "36 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Fino a sei creature in un cubo di 12 metri che falliscono il tiro salvezza hanno velocità dimezzata, -2 a CA e ai tiri salvezza su DES, niente reazioni e una sola azione o azione bonus per turno (non entrambe). Ripetono il tiro salvezza alla fine di ogni loro turno.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Luce Diurna": inc(["Chierico", "Druido", "Paladino", "Ranger", "Stregone"], 3, "Invocazione", "1 azione", "18 metri", "V, S", "1 ora",
    "Una sfera di luce intensa di 18 metri di raggio (più 18 di luce fioca). Dissolve l'oscurità magica di 3° livello o inferiore con cui si sovrappone."),
  "Manto del Crociato": inc(["Paladino"], 3, "Invocazione", "1 azione", "Incantatore", "V", "Concentrazione, fino a 1 minuto",
    "Un'aura di 9 metri di raggio: gli attacchi con armi delle creature amiche nell'aura infliggono 1d4 danni radiosi aggiuntivi."),
  "Nube Maleodorante": inc(["Bardo", "Mago", "Stregone"], 3, "Evocazione", "1 azione", "27 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Una sfera di gas nauseante di 6 metri di raggio, in oscurità pesante: chi vi inizia il turno e fallisce il tiro salvezza perde l'azione del turno. Non ha effetto su chi non respira o è immune al veleno.",
    { tiroSalvezza: { car: "COS", effetto: "agisce normalmente" } }),
  "Palla di Fuoco": inc(["Mago", "Stregone"], 3, "Invocazione", "1 azione", "45 metri", "V, S, M", "Istantanea",
    "Un'esplosione di fiamme in una sfera di 6 metri di raggio: 8d6 danni da fuoco (metà con il tiro salvezza). Aggira gli angoli e incendia gli oggetti infiammabili non trasportati.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "8d6", tipo: "da fuoco", perLivello: "1d6" }, livelloSuperiore: PIU_DADI("1d6") }),
  "Parlare con i Morti": inc(["Bardo", "Chierico"], 3, "Necromanzia", "1 azione", "3 metri", "V, S, M", "10 minuti",
    "Un cadavere con una bocca risponde fino a cinque domande con ciò che sapeva in vita. Le risposte sono brevi e possono essere criptiche; non funziona due volte sullo stesso corpo entro 10 giorni."),
  "Protezione dall'Energia": inc(["Chierico", "Druido", "Mago", "Ranger", "Stregone"], 3, "Abiurazione", "1 azione", "Contatto", "V, S", "Concentrazione, fino a 1 ora",
    "Una creatura consenziente ottiene resistenza a un tipo di danno a scelta: acido, freddo, fuoco, fulmine o tuono."),
  "Respirare Sott'Acqua": inc(["Druido", "Mago", "Ranger", "Stregone"], 3, "Trasmutazione", "1 azione", "9 metri", "V, S, M", "24 ore",
    "Fino a dieci creature consenzienti possono respirare sott'acqua, mantenendo la respirazione normale.",
    { rituale: true }),
  "Revivificare": inc(["Chierico", "Paladino"], 3, "Necromanzia", "1 azione", "Contatto", "V, S, M", "Istantanea",
    "Una creatura morta da non più di un minuto torna in vita con 1 PF, se non è morta di vecchiaia e ha il corpo integro. Consuma diamanti per 300 mo."),
  "Tempesta di Nevischio": inc(["Druido", "Mago", "Stregone"], 3, "Evocazione", "1 azione", "45 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Un cilindro di nevischio di 12 metri di raggio: oscurità pesante e terreno difficile, spegne le fiamme libere. Chi vi entra o vi inizia il turno cade prono se fallisce il tiro salvezza; chi si concentra deve superare un tiro salvezza su COS per mantenerla.",
    { tiroSalvezza: { car: "DES", effetto: "non cade prono" } }),
  "Velocità": inc(["Mago", "Stregone"], 3, "Trasmutazione", "1 azione", "9 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Una creatura consenziente raddoppia la velocità, ottiene +2 alla CA, vantaggio ai tiri salvezza su DES e un'azione in più per turno (attacco singolo, Scatto, Disimpegno, Nascondersi o Usare un Oggetto). Alla fine perde il turno successivo per la stanchezza."),
  "Muro di Vento": inc(["Druido", "Ranger"], 3, "Invocazione", "1 azione", "36 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Un muro di vento lungo 15 metri e alto 4,5: chi si trova nel suo spazio alla comparsa subisce 3d8 danni contundenti (metà con il tiro salvezza). Devia frecce e proiettili, respinge gas e creature volanti piccole.",
    { tiroSalvezza: { car: "FOR", effetto: "metà danni" }, danni: { dado: "3d8", tipo: "contundenti" } }),
  "Crescita Vegetale": inc(["Bardo", "Druido", "Ranger"], 3, "Trasmutazione", "1 azione o 8 ore", "45 metri", "V, S", "Istantanea",
    "Con 1 azione, la vegetazione in un raggio di 30 metri diventa fittissima: muoversi costa 4 volte tanto. Con 8 ore, le piante entro 750 metri daranno il doppio del raccolto per un anno."),

  // --- 4° livello ---
  "Avvizzire": inc(["Druido", "Mago", "Stregone", "Warlock"], 4, "Necromanzia", "1 azione", "9 metri", "V, S", "Istantanea",
    "L'energia necrotica prosciuga una creatura: 8d8 danni necrotici (metà con il tiro salvezza). Le piante hanno svantaggio e subiscono il massimo dei danni; non ha effetto su non morti e costrutti.",
    { tiroSalvezza: { car: "COS", effetto: "metà danni" }, danni: { dado: "8d8", tipo: "necrotici", perLivello: "1d8" }, livelloSuperiore: PIU_DADI("1d8") }),
  "Confusione": inc(["Bardo", "Druido", "Mago", "Stregone"], 4, "Ammaliamento", "1 azione", "27 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Le creature in una sfera di 3 metri che falliscono il tiro salvezza agiscono a caso secondo un d10 (si muovono a caso, restano ferme, attaccano chi è vicino...). Ripetono il tiro salvezza alla fine di ogni loro turno.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" }, livelloSuperiore: "Il raggio aumenta di 1,5 metri per ogni livello di slot oltre il 4°." }),
  "Controllare Acqua": inc(["Chierico", "Druido", "Mago"], 4, "Trasmutazione", "1 azione", "90 metri", "V, S, M", "Concentrazione, fino a 10 minuti",
    "L'incantatore controlla l'acqua in un cubo di 30 metri: può alzarla o abbassarla, separarla, deviarne la corrente o creare un vortice che trascina e danneggia le creature."),
  "Divinazione": inc(["Chierico"], 4, "Divinazione", "1 azione", "Incantatore", "V, S, M", "Istantanea",
    "L'incantatore pone una domanda su un evento dei prossimi 7 giorni e riceve una risposta veritiera, anche se criptica. Lanciato più volte prima di un riposo lungo, rischia una risposta casuale.",
    { rituale: true }),
  "Dominare Bestie": inc(["Druido", "Stregone"], 4, "Ammaliamento", "1 azione", "18 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Una bestia che fallisce il tiro salvezza (con vantaggio se la si sta combattendo) è affascinata e obbedisce agli ordini telepatici dell'incantatore. Ripete il tiro salvezza quando subisce danni.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" }, livelloSuperiore: "Dura fino a 10 minuti con uno slot di 5°, 1 ora con il 6°, 8 ore con il 7° o superiore." }),
  "Esilio": inc(["Chierico", "Mago", "Paladino", "Stregone", "Warlock"], 4, "Abiurazione", "1 azione", "18 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Una creatura che fallisce il tiro salvezza viene spedita in un semipiano innocuo (o nel suo piano d'origine, se è di un altro piano, dove resta se l'incantesimo dura fino alla fine).",
    { tiroSalvezza: { car: "CAR", effetto: "nessun effetto" }, livelloSuperiore: "Una creatura in più per ogni livello di slot oltre il 4°." }),
  "Guardiano della Fede": inc(["Chierico"], 4, "Evocazione", "1 azione", "9 metri", "V", "8 ore",
    "Un guardiano spettrale Grande occupa uno spazio: i nemici che si avvicinano entro 3 metri per la prima volta in un turno subiscono 20 danni radiosi (10 con il tiro salvezza). Svanisce dopo aver inflitto 60 danni.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" } }),
  "Interdizione alla Morte": inc(["Chierico", "Paladino"], 4, "Abiurazione", "1 azione", "Contatto", "V, S", "8 ore",
    "La prima volta che la creatura protetta scenderebbe a 0 PF, scende invece a 1 PF e l'incantesimo termina. Annulla anche un effetto che la ucciderebbe all'istante senza infliggere danni."),
  "Invisibilità Superiore": inc(["Bardo", "Mago", "Stregone"], 4, "Illusione", "1 azione", "Contatto", "V, S", "Concentrazione, fino a 1 minuto",
    "Una creatura toccata diventa invisibile e resta tale anche se attacca o lancia incantesimi."),
  "Libertà di Movimento": inc(["Bardo", "Chierico", "Druido", "Ranger"], 4, "Abiurazione", "1 azione", "Contatto", "V, S, M", "1 ora",
    "Il movimento di una creatura consenziente non è rallentato da terreno difficile, né ridotto da incantesimi e magia; non può essere paralizzata o trattenuta magicamente e si libera da una lotta con 1,5 metri di movimento."),
  "Localizzare Creatura": inc(["Bardo", "Chierico", "Druido", "Mago", "Paladino", "Ranger"], 4, "Divinazione", "1 azione", "Incantatore", "V, S, M", "Concentrazione, fino a 1 ora",
    "L'incantatore percepisce la direzione di una creatura conosciuta (o di una del tipo indicato) entro 300 metri. L'acqua corrente la blocca."),
  "Metamorfosi": inc(["Bardo", "Druido", "Mago", "Stregone"], 4, "Trasmutazione", "1 azione", "18 metri", "V, S, M", "Concentrazione, fino a 1 ora",
    "Una creatura che fallisce il tiro salvezza (i consenzienti non lo fanno) diventa una bestia di GS pari o inferiore al suo livello, con i PF della nuova forma; torna normale se scende a 0 PF.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Muro di Fuoco": inc(["Druido", "Mago", "Stregone"], 4, "Invocazione", "1 azione", "36 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Un muro di fuoco (lungo fino a 18 metri o ad anello di 6 metri di diametro): chi si trova nella sua area alla comparsa subisce 5d8 danni da fuoco (metà con il tiro salvezza), come chi termina il turno vicino al lato scelto o vi entra.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "5d8", tipo: "da fuoco", perLivello: "1d8" }, livelloSuperiore: PIU_DADI("1d8") }),
  "Occhio Arcano": inc(["Chierico", "Mago"], 4, "Divinazione", "1 azione", "9 metri", "V, S, M", "Concentrazione, fino a 1 ora",
    "Crea un occhio invisibile e fluttuante, con scurovisione, che trasmette ciò che vede all'incantatore. Con un'azione si muove di 9 metri in qualsiasi direzione."),
  "Pelle di Pietra": inc(["Druido", "Mago", "Ranger", "Stregone"], 4, "Abiurazione", "1 azione", "Contatto", "V, S, M", "Concentrazione, fino a 1 ora",
    "Una creatura consenziente ha resistenza ai danni contundenti, perforanti e taglienti non magici. Consuma polvere di diamante per 100 mo."),
  "Porta Dimensionale": inc(["Bardo", "Mago", "Stregone", "Warlock"], 4, "Evocazione", "1 azione", "150 metri", "V", "Istantanea",
    "L'incantatore si teletrasporta in un luogo entro gittata che vede o descrive, portando con sé una creatura consenziente adiacente. Se il luogo è occupato, entrambi subiscono 4d6 danni da forza e il teletrasporto fallisce."),
  "Rampicante Afferrante": inc(["Druido", "Ranger"], 4, "Evocazione", "1 azione bonus", "9 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Un rampicante spunta dal terreno: con un'azione bonus trascina di 6 metri verso di sé una creatura entro 9 metri che fallisce il tiro salvezza.",
    { tiroSalvezza: { car: "DES", effetto: "non viene trascinata" } }),
  "Scolpire Pietra": inc(["Chierico", "Druido", "Mago"], 4, "Trasmutazione", "1 azione", "Contatto", "V, S, M", "Istantanea",
    "L'incantatore modella un blocco di pietra di al massimo 1,5 metri per lato: armi, statue, un passaggio o una porta, ma senza meccanismi complessi."),
  "Scudo di Fuoco": inc(["Mago"], 4, "Invocazione", "1 azione", "Incantatore", "V, S, M", "10 minuti",
    "Fiamme calde o gelide avvolgono l'incantatore: resistenza ai danni da freddo (fiamme calde) o da fuoco (gelide). Chi lo colpisce in mischia da entro 1,5 metri subisce 2d8 danni da fuoco o da freddo.",
    { danni: { dado: "2d8", tipo: "da fuoco o da freddo" } }),
  "Tempesta di Ghiaccio": inc(["Druido", "Mago", "Stregone"], 4, "Invocazione", "1 azione", "90 metri", "V, S, M", "Istantanea",
    "Una grandinata in un cilindro di 6 metri di raggio: 2d8 danni contundenti e 4d6 da freddo (metà con il tiro salvezza). Per un turno l'area è terreno difficile.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, livelloSuperiore: "I danni contundenti aumentano di 1d8 per ogni livello di slot oltre il 4°." }),
  "Tentacoli Neri di Evard": inc(["Mago"], 4, "Evocazione", "1 azione", "27 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Tentacoli neri in un quadrato di 6 metri: terreno difficile. Chi vi entra per la prima volta in un turno o vi inizia il turno subisce 3d6 danni contundenti ed è trattenuto se fallisce il tiro salvezza; si libera con una prova di Forza o Destrezza.",
    { tiroSalvezza: { car: "DES", effetto: "nessun effetto" }, danni: { dado: "3d6", tipo: "contundenti" } }),
  "Terreno Illusorio": inc(["Bardo", "Druido", "Mago", "Warlock"], 4, "Illusione", "10 minuti", "90 metri", "V, S, M", "24 ore",
    "Un terreno naturale in un cubo di 45 metri appare, suona e odora come un altro tipo di terreno. Le strutture e le creature non vengono nascoste. Chi lo esamina può accorgersi dell'illusione con Indagare."),

  // --- 5° livello ---
  "Blocca Mostri": inc(["Bardo", "Mago", "Stregone", "Warlock"], 5, "Ammaliamento", "1 azione", "27 metri", "V, S, M", "Concentrazione, fino a 1 minuto",
    "Una creatura (non non morta) che fallisce il tiro salvezza è paralizzata. Ripete il tiro salvezza alla fine di ogni suo turno.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" }, livelloSuperiore: "Una creatura in più per ogni livello di slot oltre il 5°." }),
  "Camminare tra gli Alberi": inc(["Druido", "Ranger"], 5, "Evocazione", "1 azione", "Incantatore", "V, S", "Concentrazione, fino a 1 minuto",
    "Una volta per turno l'incantatore entra in un albero ed esce da un altro della stessa specie entro 150 metri, spendendo 1,5 metri di movimento."),
  "Colpo Infuocato": inc(["Chierico"], 5, "Invocazione", "1 azione", "18 metri", "V, S, M", "Istantanea",
    "Una colonna di fuoco divino in un cilindro di 3 metri di raggio: 4d6 danni da fuoco e 4d6 radiosi (metà con il tiro salvezza).",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "8d6", tipo: "da fuoco e radiosi (metà e metà)", perLivello: "1d6" }, livelloSuperiore: "+1d6 danni da fuoco o radiosi per ogni livello di slot oltre il 5°." }),
  "Comunione": inc(["Chierico"], 5, "Divinazione", "1 minuto", "Incantatore", "V, S, M", "1 minuto",
    "L'incantatore contatta la sua divinità e pone fino a tre domande a cui si risponde sì o no. Lanciato più volte prima di un riposo lungo, rischia di non ricevere risposta.",
    { rituale: true }),
  "Comunione con la Natura": inc(["Druido", "Ranger"], 5, "Divinazione", "1 minuto", "Incantatore", "V, S", "Istantanea",
    "L'incantatore apprende tre fatti sul territorio circostante entro 4,5 km (5 km sotto terra): terreno, acque, piante, animali, creature potenti, influenze planari o insediamenti.",
    { rituale: true }),
  "Cono di Freddo": inc(["Mago", "Stregone"], 5, "Invocazione", "1 azione", "Incantatore (cono di 18 metri)", "V, S, M", "Istantanea",
    "Un'ondata di aria gelida: 8d8 danni da freddo (metà con il tiro salvezza). Chi muore diventa una statua di ghiaccio.",
    { tiroSalvezza: { car: "COS", effetto: "metà danni" }, danni: { dado: "8d8", tipo: "da freddo", perLivello: "1d8" }, livelloSuperiore: PIU_DADI("1d8") }),
  "Conoscenza delle Leggende": inc(["Bardo", "Chierico", "Mago"], 5, "Divinazione", "10 minuti", "Incantatore", "V, S, M", "Istantanea",
    "L'incantatore riceve le informazioni leggendarie su una persona, un luogo o un oggetto importanti: più sa già, più dettagliate sono."),
  "Cura Ferite di Massa": inc(["Bardo", "Chierico", "Druido"], 5, "Invocazione", "1 azione", "18 metri", "V, S", "Istantanea",
    "Fino a sei creature in una sfera di 9 metri recuperano ciascuna 3d8 + il modificatore di caratteristica da incantatore PF. Non ha effetto su non morti e costrutti.",
    { livelloSuperiore: "+1d8 PF per ogni livello di slot oltre il 5°." }),
  "Dominare Persone": inc(["Bardo", "Mago", "Stregone"], 5, "Ammaliamento", "1 azione", "18 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Un umanoide che fallisce il tiro salvezza (con vantaggio se lo si sta combattendo) è affascinato e obbedisce agli ordini telepatici dell'incantatore. Ripete il tiro salvezza quando subisce danni.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" }, livelloSuperiore: "Dura fino a 10 minuti con uno slot di 6°, 1 ora con il 7°, 8 ore con l'8° o superiore." }),
  "Evocare Elementale": inc(["Druido", "Mago"], 5, "Evocazione", "1 minuto", "27 metri", "V, S, M", "Concentrazione, fino a 1 ora",
    "Evoca un elementale di GS 5 o inferiore da una massa di aria, terra, fuoco o acqua: è amichevole e obbedisce all'incantatore. Se la concentrazione si interrompe diventa ostile.",
    { livelloSuperiore: "GS massimo +1 per ogni livello di slot oltre il 5°." }),
  "Modificare Memoria": inc(["Bardo", "Mago"], 5, "Ammaliamento", "1 azione", "9 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Una creatura che fallisce il tiro salvezza è affascinata e incapacitata mentre l'incantatore ne modifica un ricordo delle ultime 24 ore (eliminarlo, cambiarlo, crearne uno nuovo).",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" }, livelloSuperiore: "Ricordi più vecchi: 7 giorni con il 6°, 30 giorni con il 7°, un anno con l'8°, qualsiasi momento con il 9°." }),
  "Muro di Pietra": inc(["Druido", "Mago", "Stregone"], 5, "Invocazione", "1 azione", "36 metri", "V, S, M", "Concentrazione, fino a 10 minuti",
    "Un muro di pietra non magica fatto di dieci pannelli di 3 × 3 metri, spessi 15 cm. Se la concentrazione dura per l'intera durata, diventa permanente."),
  "Nube Mortale": inc(["Mago", "Stregone"], 5, "Evocazione", "1 azione", "36 metri", "V, S", "Concentrazione, fino a 10 minuti",
    "Una nebbia velenosa di 6 metri di raggio che si allontana di 3 metri a turno: chi vi entra per la prima volta in un turno o vi inizia il turno subisce 5d8 danni da veleno (metà con il tiro salvezza).",
    { tiroSalvezza: { car: "COS", effetto: "metà danni" }, danni: { dado: "5d8", tipo: "da veleno", perLivello: "1d8" }, livelloSuperiore: PIU_DADI("1d8") }),
  "Onda Distruttiva": inc(["Paladino"], 5, "Invocazione", "1 azione", "Incantatore (raggio di 9 metri)", "V", "Istantanea",
    "Un'onda di energia divina: le creature scelte subiscono 5d6 danni da tuono e 5d6 radiosi o necrotici, e cadono prone (metà dei danni e niente caduta con il tiro salvezza).",
    { tiroSalvezza: { car: "COS", effetto: "metà danni e non cade prono" }, danni: { dado: "10d6", tipo: "da tuono e radiosi o necrotici (metà e metà)" } }),
  "Passapareti": inc(["Mago"], 5, "Trasmutazione", "1 azione", "9 metri", "V, S, M", "1 ora",
    "Un passaggio largo 1,5 metri, alto 2,5 e profondo fino a 6 metri si apre in una parete di legno, pietra o gesso."),
  "Piaga di Insetti": inc(["Chierico", "Druido", "Stregone"], 5, "Evocazione", "1 azione", "90 metri", "V, S, M", "Concentrazione, fino a 10 minuti",
    "Uno sciame di locuste in una sfera di 6 metri di raggio: oscurità leggera e terreno difficile. Chi vi entra per la prima volta in un turno o vi inizia il turno subisce 4d10 danni perforanti (metà con il tiro salvezza).",
    { tiroSalvezza: { car: "COS", effetto: "metà danni" }, danni: { dado: "4d10", tipo: "perforanti", perLivello: "1d10" }, livelloSuperiore: PIU_DADI("1d10") }),
  "Rianimare Morti": inc(["Bardo", "Chierico", "Paladino"], 5, "Necromanzia", "1 ora", "Contatto", "V, S, M", "Istantanea",
    "Una creatura morta da non più di 10 giorni torna in vita con 1 PF, se la sua anima è libera e consenziente. Ha -4 ai tiri per colpire, ai tiri salvezza e alle prove, che diminuisce di 1 a ogni riposo lungo. Consuma un diamante da 500 mo."),
  "Santificare": inc(["Chierico"], 5, "Invocazione", "24 ore", "Contatto", "V, S, M", "Fino a quando non viene dissolto",
    "Rende sacro (o profano) un luogo di 18 metri di raggio: celestiali, elementali, folletti, immondi e non morti non vi entrano facilmente, e l'incantatore può legarvi un effetto aggiuntivo (coraggio, oscurità, lingue, riposo eterno...)."),
  "Scrutare": inc(["Bardo", "Chierico", "Druido", "Mago", "Warlock"], 5, "Divinazione", "10 minuti", "Incantatore", "V, S, M", "Concentrazione, fino a 10 minuti",
    "L'incantatore osserva e ascolta una creatura su qualsiasi piano tramite un sensore invisibile, se fallisce il tiro salvezza (più facile quanto meglio la conosce).",
    { tiroSalvezza: { car: "SAG", effetto: "non si può scrutare per 24 ore" } }),
  "Sembrare": inc(["Bardo", "Mago", "Stregone"], 5, "Illusione", "1 azione", "9 metri", "V, S", "8 ore",
    "L'incantatore cambia l'aspetto di quante creature vuole entro gittata, come Camuffare Se Stesso; chi non è consenziente può evitarlo con il tiro salvezza.",
    { tiroSalvezza: { car: "CAR", effetto: "nessun effetto" } }),
  "Sogno": inc(["Bardo", "Mago", "Warlock"], 5, "Illusione", "1 minuto", "Speciale", "V, S, M", "8 ore",
    "L'incantatore (o un messaggero) entra nei sogni di una creatura conosciuta sullo stesso piano per parlarle o, se ostile, darle un incubo: con il tiro salvezza fallito non trae benefici dal riposo e subisce 3d6 danni psichici al risveglio.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun incubo" }, danni: { dado: "3d6", tipo: "psichici" } }),
  "Telecinesi": inc(["Mago", "Stregone"], 5, "Trasmutazione", "1 azione", "18 metri", "V, S", "Concentrazione, fino a 10 minuti",
    "Con un'azione a turno l'incantatore sposta di 9 metri una creatura (prova contrapposta di caratteristica da incantatore contro la sua Forza) o un oggetto fino a 500 kg."),
};

export const SCHEDE_SOTTOCLASSI: Record<string, SchedaIncantesimo> =
  Object.fromEntries(Object.entries(VOCI_SOTTOCLASSI).map(([nome, v]) => [nome, v.scheda]));

export const CLASSI_SOTTOCLASSI: Record<string, NomeClasse[]> =
  Object.fromEntries(Object.entries(VOCI_SOTTOCLASSI).map(([nome, v]) => [nome, v.classi]));
