-- Schema iniziale in PostgreSQL: corrisponde allo schema 5 dell'archivio SQLite, consolidato.
-- Nomi senza distinzione di maiuscole: citext. creato_da NULL = voce ufficiale (seed), altrimenti l'utente.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE utenti (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- BY DEFAULT: l'import conserva gli id
  username citext NOT NULL UNIQUE,
  hash text NOT NULL,
  creato timestamptz NOT NULL DEFAULT now()
);

-- Del token si salva solo l'impronta SHA-256.
CREATE TABLE sessioni (
  token text PRIMARY KEY,
  utente_id integer NOT NULL REFERENCES utenti(id) ON DELETE CASCADE,
  scadenza timestamptz NOT NULL
);
CREATE INDEX sessioni_utente ON sessioni (utente_id);
CREATE INDEX sessioni_scadenza ON sessioni (scadenza);

-- --- Cataloghi condivisi ---

CREATE TABLE incantesimi (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome citext NOT NULL UNIQUE,
  livello integer NOT NULL,
  scuola text NOT NULL,
  tempo text NOT NULL,
  gittata text,
  componenti text,
  durata text,
  concentrazione boolean NOT NULL DEFAULT false,
  rituale boolean NOT NULL DEFAULT false,
  descrizione text,                  -- NULL: voce senza dettagli (si può solo spendere lo slot)
  livello_superiore text,
  attacco_numero integer,
  attacco_per_livello integer,
  ts_caratteristica text,
  ts_effetto text,
  danni_dado text,
  danni_tipo text,
  danni_mod integer,
  danni_per_livello text,
  danni_mod_per_livello integer,
  danni_trucchetto boolean NOT NULL DEFAULT false,
  danni_per_attacco boolean NOT NULL DEFAULT false,
  creato_da integer REFERENCES utenti(id)
);

CREATE TABLE incantesimo_classi (
  incantesimo_id integer NOT NULL REFERENCES incantesimi(id) ON DELETE CASCADE,
  classe text NOT NULL,
  PRIMARY KEY (incantesimo_id, classe)
);

CREATE TABLE armi (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome citext NOT NULL UNIQUE,
  dado text NOT NULL,
  dado_versatile text,
  tipo_danno text NOT NULL,
  proprieta text NOT NULL,
  accurata boolean NOT NULL,
  categoria text,                    -- semplice, guerra
  distanza boolean NOT NULL DEFAULT false,
  creato_da integer REFERENCES utenti(id)
);

CREATE TABLE armature (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome citext NOT NULL UNIQUE,
  categoria text NOT NULL,           -- leggera, media, pesante
  ca integer NOT NULL,
  max_des integer,                   -- NULL: nessun limite al bonus di DES
  forza_min integer NOT NULL DEFAULT 0,
  svantaggio_furtivita boolean NOT NULL DEFAULT false,
  peso double precision NOT NULL,
  creato_da integer REFERENCES utenti(id)
);

-- Un privilegio che migliora con il livello ha una sola voce, con le soglie nella descrizione.
CREATE TABLE privilegi (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome citext NOT NULL,
  fonte citext NOT NULL,
  descrizione text NOT NULL,
  creato_da integer REFERENCES utenti(id),
  UNIQUE (nome, fonte)
);

CREATE TABLE razze (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome citext NOT NULL UNIQUE,
  razza_madre_id integer REFERENCES razze(id), -- sottorazza: si somma alla razza madre
  taglia text,
  velocita text,
  bonus_for integer NOT NULL DEFAULT 0,
  bonus_des integer NOT NULL DEFAULT 0,
  bonus_cos integer NOT NULL DEFAULT 0,
  bonus_int integer NOT NULL DEFAULT 0,
  bonus_sag integer NOT NULL DEFAULT 0,
  bonus_car integer NOT NULL DEFAULT 0,
  bonus_a_scelta integer NOT NULL DEFAULT 0,
  abilita_a_scelta integer NOT NULL DEFAULT 0,
  lingue_a_scelta integer NOT NULL DEFAULT 0,
  trucchetto text,
  creato_da integer REFERENCES utenti(id)
);
CREATE TABLE razza_competenze (
  razza_id integer NOT NULL REFERENCES razze(id) ON DELETE CASCADE,
  tipo text NOT NULL,                -- abilita, lingua, arma, armatura, strumento_a_scelta
  nome text NOT NULL,
  ordine integer NOT NULL,
  PRIMARY KEY (razza_id, tipo, nome)
);
CREATE TABLE razza_privilegi (
  razza_id integer NOT NULL REFERENCES razze(id) ON DELETE CASCADE,
  privilegio_id integer NOT NULL REFERENCES privilegi(id),
  ordine integer NOT NULL,
  PRIMARY KEY (razza_id, privilegio_id)
);

CREATE TABLE background (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome citext NOT NULL UNIQUE,
  strumenti_a_scelta text,           -- artigiano, musicale, gioco
  lingue_a_scelta integer NOT NULL DEFAULT 0,
  mo integer NOT NULL DEFAULT 0,
  privilegio_id integer REFERENCES privilegi(id),
  creato_da integer REFERENCES utenti(id)
);
CREATE TABLE background_competenze (
  background_id integer NOT NULL REFERENCES background(id) ON DELETE CASCADE,
  tipo text NOT NULL,                -- abilita, strumento
  nome text NOT NULL,
  ordine integer NOT NULL,
  PRIMARY KEY (background_id, tipo, nome)
);
CREATE TABLE background_oggetti (
  background_id integer NOT NULL REFERENCES background(id) ON DELETE CASCADE,
  ordine integer NOT NULL,
  nome text NOT NULL,
  qta integer NOT NULL,
  peso double precision NOT NULL,
  PRIMARY KEY (background_id, ordine)
);

-- Le classi sono regole nel codice (@dnd/regole/dati/classi.ts); qui i loro privilegi per livello.
CREATE TABLE classe_privilegi (
  classe text NOT NULL,
  sottoclasse text NOT NULL DEFAULT '', -- '' = privilegio della classe
  livello integer NOT NULL,
  privilegio_id integer NOT NULL REFERENCES privilegi(id),
  ordine integer NOT NULL,
  PRIMARY KEY (classe, sottoclasse, privilegio_id)
);
CREATE INDEX classe_privilegi_livello ON classe_privilegi (classe, livello);

-- --- Personaggi ---

CREATE TABLE personaggi (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- BY DEFAULT: l'import conserva gli id
  utente_id integer NOT NULL REFERENCES utenti(id) ON DELETE CASCADE,
  revisione integer NOT NULL,
  aggiornato timestamptz NOT NULL DEFAULT now(),
  nome text NOT NULL DEFAULT '',
  classe text NOT NULL DEFAULT '',
  sottoclasse text NOT NULL DEFAULT '',
  livello integer NOT NULL DEFAULT 1,
  razza text NOT NULL DEFAULT '',
  background text NOT NULL DEFAULT '',
  allineamento text NOT NULL DEFAULT '',
  giocatore text NOT NULL DEFAULT '',
  eta integer NOT NULL DEFAULT 0,
  altezza text NOT NULL DEFAULT '',
  peso text NOT NULL DEFAULT '',
  occhi text NOT NULL DEFAULT '',
  capelli text NOT NULL DEFAULT '',
  carnagione text NOT NULL DEFAULT '',
  velocita text NOT NULL DEFAULT '',
  taglia text NOT NULL DEFAULT 'Media',
  ispirazione boolean NOT NULL DEFAULT false,
  avatar text NOT NULL DEFAULT '',   -- data URL
  indebolimento integer NOT NULL DEFAULT 0,
  armatura_id integer REFERENCES armature(id),
  scudo boolean NOT NULL DEFAULT false,
  pf_attuali integer NOT NULL DEFAULT 0,
  pf_massimi integer NOT NULL DEFAULT 0,
  pf_temporanei integer NOT NULL DEFAULT 0,
  dadi_vita_rimanenti integer NOT NULL DEFAULT 0,
  ts_morte_successi integer NOT NULL DEFAULT 0,
  ts_morte_fallimenti integer NOT NULL DEFAULT 0,
  stabile boolean NOT NULL DEFAULT false,
  concentrazione_id integer REFERENCES incantesimi(id),
  recupero_arcano_usato boolean NOT NULL DEFAULT false,
  mr integer NOT NULL DEFAULT 0,
  ma integer NOT NULL DEFAULT 0,
  me integer NOT NULL DEFAULT 0,
  mo integer NOT NULL DEFAULT 0,
  mp integer NOT NULL DEFAULT 0,
  xp_totale integer NOT NULL DEFAULT 0,
  tratti text NOT NULL DEFAULT '',
  ideali text NOT NULL DEFAULT '',
  legami text NOT NULL DEFAULT '',
  difetti text NOT NULL DEFAULT '',
  background_bio text NOT NULL DEFAULT ''
);
CREATE INDEX personaggi_utente ON personaggi (utente_id);

-- Tabelle figlie: riscritte a ogni salvataggio.
CREATE TABLE personaggio_caratteristiche (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  car text NOT NULL,
  valore integer NOT NULL,
  comp_ts boolean NOT NULL,
  PRIMARY KEY (personaggio_id, car)
);
CREATE TABLE personaggio_abilita (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  abilita text NOT NULL,
  ordine integer NOT NULL,
  PRIMARY KEY (personaggio_id, abilita)
);
CREATE TABLE personaggio_slot (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  livello integer NOT NULL CHECK (livello BETWEEN 1 AND 9),
  spesi integer NOT NULL,
  PRIMARY KEY (personaggio_id, livello)
);
CREATE TABLE personaggio_presagio (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  indice integer NOT NULL,
  valore integer NOT NULL,
  usato boolean NOT NULL,
  PRIMARY KEY (personaggio_id, indice)
);
CREATE TABLE personaggio_xp (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  ordine integer NOT NULL,
  id_locale bigint NOT NULL,         -- id del client (anche Date.now())
  data text NOT NULL,
  valore integer NOT NULL,
  motivo text NOT NULL,
  PRIMARY KEY (personaggio_id, ordine)
);
CREATE TABLE personaggio_oggetti (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  ordine integer NOT NULL,
  id_locale bigint NOT NULL,
  nome text NOT NULL,
  qta integer NOT NULL,
  peso double precision NOT NULL,    -- lb per unità
  PRIMARY KEY (personaggio_id, ordine)
);
CREATE TABLE personaggio_competenze (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  tipo text NOT NULL,                -- lingua, strumento, arma, armatura
  nome text NOT NULL,
  ordine integer NOT NULL,
  PRIMARY KEY (personaggio_id, tipo, nome)
);
CREATE TABLE personaggio_risorse (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  risorsa text NOT NULL,             -- id della risorsa (@dnd/regole/dati/risorse.ts)
  usati integer NOT NULL,
  PRIMARY KEY (personaggio_id, risorsa)
);
CREATE TABLE personaggio_condizioni (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  condizione text NOT NULL,          -- id della condizione (@dnd/regole/dati/condizioni.ts)
  ordine integer NOT NULL,
  PRIMARY KEY (personaggio_id, condizione)
);
CREATE TABLE personaggio_effetti (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  effetto text NOT NULL,             -- id dell'effetto (@dnd/regole/dati/condizioni.ts)
  valore integer,                    -- contatore, per gli effetti che ne hanno uno
  ordine integer NOT NULL,
  PRIMARY KEY (personaggio_id, effetto)
);
CREATE TABLE personaggio_note (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  ordine integer NOT NULL,
  id_locale bigint NOT NULL,
  data text NOT NULL,
  categoria text NOT NULL,           -- sessione, png, obiettivo, altro
  titolo text NOT NULL,
  testo text NOT NULL,
  fatto boolean NOT NULL DEFAULT false,
  PRIMARY KEY (personaggio_id, ordine)
);
CREATE TABLE personaggio_note_campi (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  nota_ordine integer NOT NULL,      -- ordine della nota in personaggio_note
  campo text NOT NULL,               -- id del campo (@dnd/regole/dati/note.ts)
  valore text NOT NULL,
  PRIMARY KEY (personaggio_id, nota_ordine, campo)
);

-- Tabelle ponte verso i cataloghi.
CREATE TABLE personaggio_incantesimi (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  incantesimo_id integer NOT NULL REFERENCES incantesimi(id),
  preparato boolean NOT NULL,
  ordine integer NOT NULL,
  PRIMARY KEY (personaggio_id, incantesimo_id)
);
CREATE TABLE personaggio_armi (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  ordine integer NOT NULL,
  id_locale bigint NOT NULL,
  arma_id integer NOT NULL REFERENCES armi(id),
  bonus integer NOT NULL DEFAULT 0,  -- arma magica +1/+2/+3
  munizioni_rimaste integer,
  munizioni_massime integer,
  durabilita_rimasta integer,        -- con durabilita_massima NULL: colpi rimasti di un'arma danneggiata
  durabilita_massima integer,
  rotta boolean NOT NULL DEFAULT false,
  PRIMARY KEY (personaggio_id, ordine)
);
CREATE TABLE personaggio_privilegi (
  personaggio_id integer NOT NULL REFERENCES personaggi(id) ON DELETE CASCADE,
  privilegio_id integer NOT NULL REFERENCES privilegi(id),
  ordine integer NOT NULL,
  PRIMARY KEY (personaggio_id, privilegio_id)
);
