import type { NomeClasse } from "../dati/classi.ts";
import type { SemePrivilegioClasse } from "./classi.ts";

// Privilegi di classe e di sottoclasse dal 2° al 20° livello (il 1° livello è in classi.ts).
// Gli aumenti dei punteggi di caratteristica non ci sono: li ricorda la tab Progresso.
// Un privilegio che migliora con il livello compare una volta sola, con le soglie nella descrizione.
// Le descrizioni sono riassunti brevi, non il testo del manuale.

const c = (classe: NomeClasse, livello: number, nome: string, descrizione: string): SemePrivilegioClasse =>
  ({ classe, livello, privilegio: { nome, fonte: classe, descrizione } });

const s = (classe: NomeClasse, sottoclasse: string, livello: number, nome: string, descrizione: string): SemePrivilegioClasse =>
  ({ classe, sottoclasse, livello, privilegio: { nome, fonte: sottoclasse, descrizione } });

const BARBARO: SemePrivilegioClasse[] = [
  c("Barbaro", 2, "Attacco Sconsiderato", "Al primo attacco del turno può attaccare con vantaggio i tiri per colpire in mischia con la Forza, ma fino al turno successivo gli attacchi contro di lui hanno vantaggio."),
  c("Barbaro", 2, "Percepire il Pericolo", "Vantaggio ai TS su Destrezza contro effetti che può vedere (trappole, incantesimi), se non è accecato, assordato o incapacitato."),
  c("Barbaro", 3, "Cammino Primordiale", "Sceglie un cammino che gli concede privilegi al 3°, 6°, 10° e 14° livello."),
  c("Barbaro", 5, "Attacco Extra", "Quando compie l'azione di Attacco può attaccare due volte invece di una."),
  c("Barbaro", 5, "Movimento Veloce", "La velocità aumenta di 3 m se non indossa un'armatura pesante."),
  c("Barbaro", 7, "Istinto Ferino", "Vantaggio ai tiri di iniziativa; se è sorpreso può agire normalmente entrando in ira per primo."),
  c("Barbaro", 9, "Critico Brutale", "Con un colpo critico in mischia tira un dado di danno dell'arma in più (2 dadi al 13°, 3 al 17° livello)."),
  c("Barbaro", 11, "Ira Implacabile", "Se scende a 0 PF in ira, un TS su COS (CD 10, +5 a ogni uso successivo) lo lascia a 1 PF invece."),
  c("Barbaro", 15, "Ira Persistente", "L'ira termina solo se cade privo di sensi o la interrompe volontariamente, non per inattività."),
  c("Barbaro", 18, "Forza Indomita", "Se il totale di una prova di Forza è inferiore al suo punteggio di Forza, può usare il punteggio al posto del totale."),
  c("Barbaro", 20, "Campione Primordiale", "Forza e Costituzione aumentano di 4, fino a un massimo di 24; l'ira non ha più limiti di usi."),

  s("Barbaro", "Cammino del Berserker", 3, "Frenesia", "In ira può attaccare con un'azione bonus in ogni turno; alla fine dell'ira subisce un livello di indebolimento."),
  s("Barbaro", "Cammino del Berserker", 6, "Ira Incontrollata", "Mentre è in ira non può essere affascinato né spaventato; se lo era, l'effetto è sospeso."),
  s("Barbaro", "Cammino del Berserker", 10, "Presenza Intimidatoria", "Con un'azione terrorizza una creatura entro 9 m (TS SAG, CD 8 + comp + CAR); può prolungare l'effetto turno per turno."),
  s("Barbaro", "Cammino del Berserker", 14, "Rappresaglia", "Con una reazione attacca in mischia una creatura entro portata che gli ha inflitto danni."),
  s("Barbaro", "Cammino del Combattente Totemico", 3, "Cercatore Spirituale", "Può lanciare come rituale Parlare con gli Animali e Percezione delle Bestie."),
  s("Barbaro", "Cammino del Combattente Totemico", 3, "Spirito Totemico", "In ira sceglie uno spirito animale (orso, aquila o lupo) che gli dà un potere diverso: resistenza a quasi tutti i danni, scatto agile o alleati avvantaggiati."),
  s("Barbaro", "Cammino del Combattente Totemico", 6, "Aspetto della Belva", "Ottiene un beneficio permanente legato a un animale: capacità di carico doppia, vista da aquila o fiuto e udito da lupo."),
  s("Barbaro", "Cammino del Combattente Totemico", 10, "Camminatore Spirituale", "Può lanciare Comunione con la Natura come rituale, tramite uno spirito animale."),
  s("Barbaro", "Cammino del Combattente Totemico", 14, "Sintonia Totemica", "Un altro potere legato all'animale scelto: bonus di mischia per chi lo circonda, velocità di arrampicata o vantaggio ai colpi dei nemici lontani."),
];

const BARDO: SemePrivilegioClasse[] = [
  c("Bardo", 2, "Factotum", "Aggiunge metà del bonus di competenza (per difetto) alle prove di abilità in cui non è competente."),
  c("Bardo", 2, "Canto di Riposo", "Durante un riposo breve, alleati che spendono Dadi Vita recuperano 1d6 PF extra (d8 al 9°, d10 al 13°, d12 al 17° livello)."),
  c("Bardo", 3, "Collegio Bardico", "Sceglie un collegio che gli concede privilegi al 3°, 6° e 14° livello."),
  c("Bardo", 3, "Maestria", "Sceglie due abilità in cui è competente: il bonus di competenza raddoppia (altre due al 10° livello)."),
  c("Bardo", 5, "Fonte di Ispirazione", "L'Ispirazione Bardica si ricarica anche con un riposo breve; il dado sale a d8 (d10 al 10°, d12 al 15° livello)."),
  c("Bardo", 6, "Controfascino", "Con un'azione dà a sé e agli alleati entro 9 m vantaggio ai TS contro spavento e affascinamento fino alla fine del suo turno successivo."),
  c("Bardo", 10, "Segreti Magici", "Impara due incantesimi da qualsiasi classe (altri due al 14° e al 18° livello), che contano come incantesimi da bardo."),
  c("Bardo", 20, "Ispirazione Superiore", "Se tira iniziativa senza usi di Ispirazione Bardica, ne recupera uno."),

  s("Bardo", "Collegio della Sapienza", 3, "Competenze Bonus", "Competenza in tre abilità a scelta."),
  s("Bardo", "Collegio della Sapienza", 3, "Parole Taglienti", "Con una reazione spende un'Ispirazione Bardica per sottrarre il dado a un attacco, una prova o un danno di una creatura entro 18 m."),
  s("Bardo", "Collegio della Sapienza", 6, "Segreti Magici Aggiuntivi", "Impara due incantesimi da qualsiasi classe."),
  s("Bardo", "Collegio della Sapienza", 14, "Abilità Impareggiabile", "Quando fa una prova può spendere un'Ispirazione Bardica e aggiungere il dado al tiro, anche dopo averlo visto."),
  s("Bardo", "Collegio del Valore", 3, "Competenze Bonus (Valore)", "Competenza nelle armature medie, negli scudi e nelle armi da guerra."),
  s("Bardo", "Collegio del Valore", 3, "Ispirazione in Battaglia", "Chi ha l'Ispirazione Bardica può usarla anche per aumentare un danno o la propria CA contro un attacco."),
  s("Bardo", "Collegio del Valore", 6, "Attacco Extra (Bardo)", "Quando compie l'azione di Attacco può attaccare due volte invece di una."),
  s("Bardo", "Collegio del Valore", 14, "Magia da Battaglia", "Dopo aver lanciato un incantesimo con un'azione può attaccare con un'arma come azione bonus."),
];

const CHIERICO: SemePrivilegioClasse[] = [
  c("Chierico", 2, "Incanalare Divinità", "Usa l'energia divina per gli effetti del dominio e per Scacciare Non Morti. 1 uso per riposo breve o lungo (2 dal 6°, 3 dal 18° livello)."),
  c("Chierico", 2, "Incanalare Divinità: Scacciare Non Morti", "Con un'azione mostra il simbolo sacro: i non morti entro 9 m che lo vedono e non superano un TS su SAG sono scacciati per 1 minuto."),
  c("Chierico", 5, "Distruggere Non Morti (GS 1/2)", "Un non morto che fallisce il TS contro Scacciare Non Morti è distrutto se il suo grado sfida è pari o inferiore a 1/2 (1 all'8°, 2 all'11°, 3 al 14°, 4 al 17° livello)."),
  c("Chierico", 10, "Intervento Divino", "Con un'azione implora l'aiuto della divinità: tira un d100 e se il risultato è pari o inferiore al livello da chierico la divinità interviene. Se riesce, non si può riusare per 7 giorni."),
  c("Chierico", 20, "Intervento Divino Migliorato", "L'Intervento Divino riesce automaticamente, senza bisogno di tirare."),

  s("Chierico", "Dominio della Conoscenza", 2, "Incanalare Divinità: Conoscenza delle Ere", "Con un'azione ottiene competenza in un'abilità o in uno strumento a scelta per 10 minuti."),
  s("Chierico", "Dominio della Conoscenza", 6, "Incanalare Divinità: Leggere i Pensieri", "Legge i pensieri di una creatura entro 18 m (TS SAG) e può anche suggerirle un'azione per 1 minuto."),
  s("Chierico", "Dominio della Conoscenza", 8, "Incanto Potente", "Aggiunge il modificatore di Saggezza ai danni dei trucchetti da chierico."),
  s("Chierico", "Dominio della Conoscenza", 17, "Visioni del Passato", "Può meditare su un oggetto o su un luogo per ricevere visioni degli eventi che vi sono accaduti."),
  s("Chierico", "Dominio della Guerra", 2, "Incanalare Divinità: Attacco Guidato", "Quando effettua un tiro per colpire può aggiungere +10 al tiro."),
  s("Chierico", "Dominio della Guerra", 6, "Incanalare Divinità: Benedizione del Dio della Guerra", "Con una reazione dà +10 al tiro per colpire di una creatura entro 9 m."),
  s("Chierico", "Dominio della Guerra", 8, "Colpo Divino (Guerra)", "Una volta per turno infligge 1d8 danni extra dell'arma (2d8 al 14° livello)."),
  s("Chierico", "Dominio della Guerra", 17, "Avatar della Battaglia", "Resistenza ai danni contundenti, perforanti e taglienti delle armi non magiche."),
  s("Chierico", "Dominio dell'Inganno", 2, "Incanalare Divinità: Invocare Duplicità", "Crea un duplicato illusorio di sé (concentrazione, 1 minuto) da cui può lanciare incantesimi e che gli dà vantaggio agli attacchi."),
  s("Chierico", "Dominio dell'Inganno", 6, "Incanalare Divinità: Mantello di Ombre", "Con un'azione diventa invisibile fino alla fine del suo turno successivo."),
  s("Chierico", "Dominio dell'Inganno", 8, "Colpo Divino (Inganno)", "Una volta per turno infligge 1d8 danni da veleno extra (2d8 al 14° livello)."),
  s("Chierico", "Dominio dell'Inganno", 17, "Duplicità Migliorata", "Può creare fino a quattro duplicati con Invocare Duplicità."),
  s("Chierico", "Dominio della Luce", 2, "Incanalare Divinità: Radianza dell'Alba", "Con un'azione emana luce che dissipa l'oscurità magica e infligge 2d10 + livello danni radiosi ai nemici entro 9 m (TS COS per dimezzare)."),
  s("Chierico", "Dominio della Luce", 6, "Bagliore Potenziato", "Il Bagliore Protettivo protegge anche gli alleati entro 9 m."),
  s("Chierico", "Dominio della Luce", 8, "Incanto Potente (Luce)", "Aggiunge il modificatore di Saggezza ai danni dei trucchetti da chierico."),
  s("Chierico", "Dominio della Luce", 17, "Corona di Luce", "Con un'azione emana luce solare per 1 minuto: i nemici entro 18 m subiscono svantaggio ai TS contro i suoi incantesimi di fuoco e radiosi."),
  s("Chierico", "Dominio della Natura", 2, "Incanalare Divinità: Charme su Animali e Piante", "Con un'azione affascina animali e piante entro 9 m che falliscono un TS su SAG."),
  s("Chierico", "Dominio della Natura", 6, "Attenuare Elementi", "Con una reazione dà a sé o a un alleato resistenza ai danni da acido, freddo, fuoco, fulmine o tuono."),
  s("Chierico", "Dominio della Natura", 8, "Colpo Divino (Natura)", "Una volta per turno infligge 1d8 danni da freddo, fuoco o fulmine extra (2d8 al 14° livello)."),
  s("Chierico", "Dominio della Natura", 17, "Padrone della Natura", "Con un'azione bonus può comandare animali e piante affascinati da lui."),
  s("Chierico", "Dominio della Tempesta", 2, "Incanalare Divinità: Ira Distruttiva", "Quando tira danni da fulmine o tuono può infliggere il massimo dei danni."),
  s("Chierico", "Dominio della Tempesta", 6, "Colpo Fulminante", "Quando infligge danni da fulmine a una creatura Grande o più piccola può spingerla di 3 m."),
  s("Chierico", "Dominio della Tempesta", 8, "Colpo Divino (Tempesta)", "Una volta per turno infligge 1d8 danni da tuono extra (2d8 al 14° livello)."),
  s("Chierico", "Dominio della Tempesta", 17, "Figlio della Tempesta", "Ha velocità di volo pari alla sua velocità a terra quando è all'aperto e non sotto terra."),
  s("Chierico", "Dominio della Vita", 2, "Incanalare Divinità: Preservare la Vita", "Con un'azione distribuisce fino a 5 × livello PF di cura tra le creature entro 9 m (senza portarle oltre metà dei PF massimi)."),
  s("Chierico", "Dominio della Vita", 6, "Guaritore Benedetto", "Quando cura un'altra creatura con un incantesimo di 1° livello o superiore recupera anche 2 + livello dell'incantesimo PF."),
  s("Chierico", "Dominio della Vita", 8, "Colpo Divino (Vita)", "Una volta per turno infligge 1d8 danni radiosi extra (2d8 al 14° livello)."),
  s("Chierico", "Dominio della Vita", 17, "Guarigione Suprema", "Quando tira dadi per curare li considera tutti al massimo."),
];

const DRUIDO: SemePrivilegioClasse[] = [
  c("Druido", 2, "Forma Selvatica", "Con un'azione si trasforma in una bestia che ha già visto: 2 usi per riposo breve o lungo; limiti di GS e di tipo di movimento crescono con il livello."),
  c("Druido", 2, "Circolo Druidico", "Sceglie un circolo che gli concede privilegi al 2°, 3°, 6°, 10° e 14° livello."),
  c("Druido", 18, "Corpo Senza Età", "Invecchia di 1 anno ogni 10 che passano."),
  c("Druido", 18, "Incantesimi Bestiali", "Può lanciare incantesimi con componenti verbali e somatiche mentre è in Forma Selvatica."),
  c("Druido", 20, "Arcidruido", "Usi illimitati di Forma Selvatica; ignora le componenti verbali, somatiche e materiali senza costo degli incantesimi."),

  s("Druido", "Circolo della Terra", 2, "Trucchetto Bonus (Terra)", "Impara un trucchetto da druido a scelta."),
  s("Druido", "Circolo della Terra", 2, "Recupero Naturale", "Una volta al giorno, durante un riposo breve, recupera slot per un livello totale pari a metà del livello da druido (per eccesso), massimo 5° livello."),
  s("Druido", "Circolo della Terra", 3, "Incantesimi del Circolo", "Ha sempre preparati gli incantesimi legati al proprio terreno (artico, costa, deserto, foresta, prateria, montagna, palude, Underdark)."),
  s("Druido", "Circolo della Terra", 6, "Passo della Terra", "Attraversa terreno difficile non magico senza rallentare, e piante non magiche senza subire danni."),
  s("Druido", "Circolo della Terra", 10, "Protezione della Natura", "Immune a veleno e malattie; non può essere affascinato o spaventato da elementali e fatati."),
  s("Druido", "Circolo della Terra", 14, "Santuario della Natura", "Bestie e piante devono superare un TS su SAG per attaccarlo; se falliscono scelgono un altro bersaglio."),
  s("Druido", "Circolo della Luna", 2, "Forma Selvatica da Combattimento", "Può usare Forma Selvatica con un'azione bonus e trasformarsi in bestie di GS più alto; può spendere slot per curarsi nella forma."),
  s("Druido", "Circolo della Luna", 2, "Forme del Circolo", "Il GS massimo delle bestie è 1 al 2° livello e sale con il livello (livello / 3 dal 6°)."),
  s("Druido", "Circolo della Luna", 6, "Colpo Primordiale", "Gli attacchi nella forma di bestia contano come magici per superare resistenze e immunità."),
  s("Druido", "Circolo della Luna", 10, "Forma Selvatica Elementale", "Spende 2 usi di Forma Selvatica per trasformarsi in un elementale di aria, fuoco, terra o acqua."),
  s("Druido", "Circolo della Luna", 14, "Mille Forme", "Può lanciare Metamorfosi su se stesso a volontà."),
];

const GUERRIERO: SemePrivilegioClasse[] = [
  c("Guerriero", 2, "Azione Impetuosa", "Per un turno può compiere un'azione aggiuntiva. Una volta per riposo breve o lungo (2 usi dal 17° livello)."),
  c("Guerriero", 3, "Archetipo Marziale", "Sceglie un archetipo che gli concede privilegi al 3°, 7°, 10°, 15° e 18° livello."),
  c("Guerriero", 5, "Attacco Extra", "Quando compie l'azione di Attacco può attaccare due volte (tre all'11°, quattro al 20° livello)."),
  c("Guerriero", 9, "Indomito", "Può ritirare un tiro salvezza fallito, usando il nuovo risultato. Una volta per riposo lungo (2 usi al 13°, 3 al 17° livello)."),

  s("Guerriero", "Campione", 3, "Critico Migliorato", "I suoi attacchi con armi mettono a segno un colpo critico con 19 o 20 sul d20."),
  s("Guerriero", "Campione", 7, "Atleta Straordinario", "Aggiunge metà del bonus di competenza alle prove di FOR, DES e COS in cui non è competente; il salto in lungo aumenta."),
  s("Guerriero", "Campione", 10, "Stile di Combattimento Aggiuntivo", "Sceglie un secondo stile di combattimento."),
  s("Guerriero", "Campione", 15, "Critico Superiore", "I suoi attacchi con armi mettono a segno un colpo critico con 18, 19 o 20 sul d20."),
  s("Guerriero", "Campione", 18, "Sopravvissuto", "Rigenera PF a inizio turno (5 + mod COS) se è ferito e ha almeno 1 PF ma meno di metà dei PF massimi."),
  s("Guerriero", "Maestro di Battaglia", 3, "Superiorità in Combattimento", "Impara 3 manovre e ha 4 dadi di superiorità (d8) che ricarica con il riposo breve o lungo; la CD delle manovre è 8 + comp + FOR o DES."),
  s("Guerriero", "Maestro di Battaglia", 3, "Studente di Guerra", "Competenza in uno strumento da artigiano a scelta."),
  s("Guerriero", "Maestro di Battaglia", 7, "Conosci il Tuo Nemico", "Dopo 1 minuto di osservazione scopre se una creatura è superiore o inferiore a lui in due caratteristiche a scelta tra FOR, DES, COS, CA, PF attuali, livello."),
  s("Guerriero", "Maestro di Battaglia", 10, "Superiorità in Combattimento Migliorata", "I dadi di superiorità diventano d10 (d12 al 18° livello); impara altre 2 manovre."),
  s("Guerriero", "Maestro di Battaglia", 15, "Inesorabile", "Se tira iniziativa senza dadi di superiorità ne recupera uno."),
  s("Guerriero", "Cavaliere Mistico", 3, "Incantesimi (Cavaliere Mistico)", "Lancia incantesimi da mago (soprattutto di abiurazione e invocazione) usando l'Intelligenza, con un numero ridotto di slot."),
  s("Guerriero", "Cavaliere Mistico", 3, "Vincolo con l'Arma", "Dopo 1 ora di rituale vincola fino a due armi: non può essere disarmato e le richiama a mano con un'azione bonus."),
  s("Guerriero", "Cavaliere Mistico", 7, "Magia da Guerra", "Dopo aver lanciato un trucchetto con un'azione può attaccare con un'arma come azione bonus."),
  s("Guerriero", "Cavaliere Mistico", 10, "Colpo Mistico", "Chi colpisce con un'arma ha svantaggio al prossimo TS contro un suo incantesimo entro la fine del suo turno successivo."),
  s("Guerriero", "Cavaliere Mistico", 15, "Carica Arcana", "Quando usa Azione Impetuosa può teletrasportarsi di 9 m in uno spazio libero che vede."),
  s("Guerriero", "Cavaliere Mistico", 18, "Magia da Guerra Migliorata", "Dopo aver lanciato un incantesimo con un'azione può attaccare con un'arma come azione bonus."),
];

const LADRO: SemePrivilegioClasse[] = [
  c("Ladro", 2, "Azione Scaltra", "Può usare un'azione bonus per Scattare, Disimpegnarsi o Nascondersi."),
  c("Ladro", 3, "Archetipo Ladresco", "Sceglie un archetipo che gli concede privilegi al 3°, 9°, 13° e 17° livello."),
  c("Ladro", 5, "Schivata Prodigiosa", "Con una reazione dimezza i danni di un attacco di un nemico che può vedere."),
  c("Ladro", 6, "Maestria Aggiuntiva", "Sceglie altre due competenze cui raddoppiare il bonus."),
  c("Ladro", 7, "Elusione", "Nei TS su Destrezza per dimezzare i danni non ne subisce se ha successo e ne subisce metà se fallisce."),
  c("Ladro", 11, "Talento Affidabile", "Nelle prove di abilità in cui è competente tratta un d20 inferiore a 10 come un 10."),
  c("Ladro", 14, "Percezione Cieca", "Percepisce le creature nascoste o invisibili entro 3 m."),
  c("Ladro", 15, "Mente Sfuggente", "Competenza nei TS su Saggezza."),
  c("Ladro", 18, "Elusivo", "Nessun attacco ha vantaggio contro di lui, se non è incapacitato."),
  c("Ladro", 20, "Colpo di Fortuna", "Se un attacco manca o una prova fallisce può trasformarlo in un 20. Una volta per riposo breve o lungo."),

  s("Ladro", "Furfante", 3, "Mani Rapide", "Può usare l'azione bonus di Azione Scaltra anche per Rapidità di Mano, disinnescare trappole o usare un oggetto."),
  s("Ladro", "Furfante", 3, "Lavoro di Secondo Piano", "Arrampicarsi non costa movimento extra e i salti in lungo crescono con la Destrezza."),
  s("Ladro", "Furfante", 9, "Furtività Suprema", "Se si muove di non più della metà della velocità ha vantaggio alle prove di Furtività."),
  s("Ladro", "Furfante", 13, "Usare Oggetti Magici", "Ignora i requisiti di classe, razza e livello per gli oggetti magici."),
  s("Ladro", "Furfante", 17, "Riflessi da Ladro", "Nel primo round di combattimento agisce due volte: al normale ordine di iniziativa e a iniziativa −10."),
  s("Ladro", "Assassino", 3, "Competenze Bonus (Assassino)", "Competenza nel kit da travestimento e nel kit da avvelenatore."),
  s("Ladro", "Assassino", 3, "Assassinare", "Ha vantaggio contro le creature che non hanno ancora agito e ogni colpo a una creatura sorpresa è critico."),
  s("Ladro", "Assassino", 9, "Specialista dell'Infiltrazione", "Crea identità false complete e può imitare voce e scrittura altrui."),
  s("Ladro", "Assassino", 13, "Impostore", "Dopo 3 ore di studio imita alla perfezione voce, scrittura e comportamento di un'altra persona."),
  s("Ladro", "Assassino", 17, "Colpo Mortale", "Se colpisce una creatura sorpresa questa deve superare un TS su COS (CD 8 + DES + comp) o subisce danni doppi."),
  s("Ladro", "Mistificatore Arcano", 3, "Incantesimi (Mistificatore Arcano)", "Lancia incantesimi da mago (soprattutto di ammaliamento e illusione) usando l'Intelligenza, con pochi slot."),
  s("Ladro", "Mistificatore Arcano", 3, "Mano Magica Migliorata", "Mano Magica è invisibile e può rubare, riporre oggetti o usare arnesi da scasso."),
  s("Ladro", "Mistificatore Arcano", 9, "Imboscata Magica", "Se è nascosto quando lancia un incantesimo, il bersaglio ha svantaggio al TS."),
  s("Ladro", "Mistificatore Arcano", 13, "Versatilità", "Con un'azione bonus può trasferire un effetto di Mano Magica a una creatura vicina."),
  s("Ladro", "Mistificatore Arcano", 17, "Ladro di Incantesimi", "Con una reazione può rubare la conoscenza di un incantesimo lanciato contro di lui, se supera un TS."),
];

const MAGO: SemePrivilegioClasse[] = [
  c("Mago", 2, "Tradizione Arcana", "Sceglie una scuola di magia che gli concede privilegi al 2°, 6°, 10° e 14° livello."),
  c("Mago", 18, "Maestria negli Incantesimi", "Sceglie un incantesimo di 1° livello e uno di 2° del proprio libro e li lancia al loro livello senza spendere slot."),
  c("Mago", 20, "Firma Magica", "Sceglie due incantesimi di 3° livello del libro: può lanciarli una volta ciascuno per riposo breve senza spendere slot."),

  s("Mago", "Scuola di Abiurazione", 2, "Esperto di Abiurazione", "Oro e tempo per copiare un incantesimo di abiurazione nel libro sono dimezzati."),
  s("Mago", "Scuola di Abiurazione", 2, "Protezione Arcana", "Ha una barriera con PF pari a 2 × livello da mago + mod INT che assorbe i danni; si ricarica lanciando incantesimi di abiurazione."),
  s("Mago", "Scuola di Abiurazione", 6, "Protezione Proiettata", "Con una reazione usa la Protezione Arcana per assorbire il danno subito da una creatura vicina."),
  s("Mago", "Scuola di Abiurazione", 10, "Abiurazione Migliorata", "Aggiunge il bonus di competenza alle prove di caratteristica di Controincantesimo e Dissolvi Magie."),
  s("Mago", "Scuola di Abiurazione", 14, "Resistenza agli Incantesimi", "Vantaggio ai TS contro gli incantesimi e resistenza ai danni degli incantesimi."),
  s("Mago", "Scuola di Ammaliamento", 2, "Esperto di Ammaliamento", "Oro e tempo per copiare un incantesimo di ammaliamento nel libro sono dimezzati."),
  s("Mago", "Scuola di Ammaliamento", 2, "Sguardo Ipnotico", "Con un'azione affascina una creatura entro 1,5 m che lo capisce (TS SAG), incapacitandola per il turno successivo."),
  s("Mago", "Scuola di Ammaliamento", 6, "Charme Istintivo", "Con una reazione dirotta su un'altra creatura un attacco contro di lui (TS SAG)."),
  s("Mago", "Scuola di Ammaliamento", 10, "Ammaliamento Suddiviso", "Quando lancia un incantesimo di ammaliamento a un solo bersaglio può sceglierne un secondo."),
  s("Mago", "Scuola di Ammaliamento", 14, "Alterare Ricordi", "Quando affascina una creatura può fargliene dimenticare l'incontro o alterarne il ricordo."),
  s("Mago", "Scuola di Divinazione", 6, "Divinazione Esperta", "Quando lancia un incantesimo di divinazione di 2° livello o superiore recupera uno slot di livello inferiore (massimo 5°)."),
  s("Mago", "Scuola di Divinazione", 10, "Il Terzo Occhio", "Con un'azione ottiene per un certo tempo scurovisione, visione eterea, comprensione del linguaggio o vista di ciò che è invisibile. Una volta per riposo breve o lungo."),
  s("Mago", "Scuola di Divinazione", 14, "Presagio Superiore", "Tira tre dadi di Presagio invece di due."),
  s("Mago", "Scuola di Evocazione", 2, "Esperto di Evocazione", "Oro e tempo per copiare un incantesimo di evocazione nel libro sono dimezzati."),
  s("Mago", "Scuola di Evocazione", 2, "Evocazione Minore", "Con un'azione crea un oggetto non magico (max 3 m per lato, 4,5 kg) che dura 1 ora."),
  s("Mago", "Scuola di Evocazione", 6, "Teletrasporto Benigno", "Dopo aver lanciato un incantesimo di evocazione può teletrasportarsi di 9 m."),
  s("Mago", "Scuola di Evocazione", 10, "Evocazione Focalizzata", "Mentre si concentra su un incantesimo di evocazione la concentrazione non si spezza per i danni."),
  s("Mago", "Scuola di Evocazione", 14, "Evocazione Durevole", "Le creature che evoca hanno 30 PF temporanei."),
  s("Mago", "Scuola di Illusione", 2, "Esperto di Illusione", "Oro e tempo per copiare un incantesimo di illusione nel libro sono dimezzati."),
  s("Mago", "Scuola di Illusione", 2, "Illusione Migliorata", "Impara il trucchetto Illusione Minore; se lo lancia può creare sia un suono sia un'immagine."),
  s("Mago", "Scuola di Illusione", 6, "Creature Fantasma", "Può trasformare una creatura evocata in illusione parziale che ha danni dimezzati."),
  s("Mago", "Scuola di Illusione", 10, "Illusioni Autoprodotte", "Quando è in pericolo può creare l'illusione di sé stesso vicino a lui."),
  s("Mago", "Scuola di Illusione", 14, "Realtà Illusoria", "Dopo aver lanciato un'illusione di 1° livello o superiore può rendere reale un oggetto inanimato per 1 minuto."),
  s("Mago", "Scuola di Invocazione", 2, "Esperto di Invocazione", "Oro e tempo per copiare un incantesimo di invocazione nel libro sono dimezzati."),
  s("Mago", "Scuola di Invocazione", 2, "Scolpire Incantesimi", "Quando lancia un incantesimo di invocazione che colpisce altri può escludere alcune creature dall'area (1 + livello dell'incantesimo)."),
  s("Mago", "Scuola di Invocazione", 6, "Trucchetto Potente", "Un trucchetto che infligge danni infligge comunque metà danni a chi supera il TS o al bersaglio mancato."),
  s("Mago", "Scuola di Invocazione", 10, "Invocazione Potenziata", "Aggiunge il modificatore di Intelligenza ai danni di un incantesimo di invocazione da mago."),
  s("Mago", "Scuola di Invocazione", 14, "Sovraccaricare", "Può infliggere il massimo dei danni con un incantesimo di 5° livello o inferiore; dopo la prima volta subisce danni per ogni uso successivo."),
  s("Mago", "Scuola di Necromanzia", 2, "Esperto di Necromanzia", "Oro e tempo per copiare un incantesimo di necromanzia nel libro sono dimezzati."),
  s("Mago", "Scuola di Necromanzia", 2, "Mietitura Sinistra", "Quando uccide una creatura con un incantesimo recupera PF pari a 2 × livello dell'incantesimo (3 × per la necromanzia)."),
  s("Mago", "Scuola di Necromanzia", 6, "Servitori Non Morti", "Gli scheletri e gli zombie che crea hanno PF extra e un bonus ai danni."),
  s("Mago", "Scuola di Necromanzia", 10, "Assuefatto alla Non Morte", "Resistenza ai danni necrotici e i suoi PF massimi non possono essere ridotti."),
  s("Mago", "Scuola di Necromanzia", 14, "Comandare i Non Morti", "Con un'azione prende il controllo di un non morto (TS CAR)."),
  s("Mago", "Scuola di Trasmutazione", 2, "Esperto di Trasmutazione", "Oro e tempo per copiare un incantesimo di trasmutazione nel libro sono dimezzati."),
  s("Mago", "Scuola di Trasmutazione", 2, "Alchimista Minore", "Con 10 minuti può trasformare un oggetto non magico da un materiale a un altro (legno, pietra, ferro, rame, argento)."),
  s("Mago", "Scuola di Trasmutazione", 6, "Pietra del Trasmutatore", "Crea una pietra che conferisce a chi la porta uno di vari benefici (scurovisione, velocità, competenza COS, resistenza)."),
  s("Mago", "Scuola di Trasmutazione", 10, "Mutaforma", "Impara Metamorfosi e può lanciarlo su se stesso una volta per riposo senza slot."),
  s("Mago", "Scuola di Trasmutazione", 14, "Maestro Trasmutatore", "Con un'azione consuma la Pietra del Trasmutatore per un effetto potente come Panacea, Rianimare Morti, Ringiovanimento o trasformazione."),
];

const MONACO: SemePrivilegioClasse[] = [
  c("Monaco", 2, "Ki", "Ha un numero di punti ki pari al suo livello, con cui alimenta Raffica di Colpi, Difesa Paziente e Passo del Vento; si ricaricano con il riposo breve o lungo."),
  c("Monaco", 2, "Movimento Senza Armatura", "La velocità aumenta di 3 m senza armatura né scudo (di più salendo di livello); dal 9° può correre su superfici verticali e liquidi."),
  c("Monaco", 3, "Tradizione Monastica", "Sceglie una tradizione che gli concede privilegi al 3°, 6°, 11° e 17° livello."),
  c("Monaco", 3, "Deviare Proiettili", "Con una reazione riduce il danno di un attacco a distanza di 1d10 + DES + livello; può rilanciare il proiettile spendendo 1 ki."),
  c("Monaco", 4, "Caduta Lenta", "Con una reazione riduce il danno da caduta di 5 × livello."),
  c("Monaco", 5, "Attacco Extra", "Quando compie l'azione di Attacco può attaccare due volte invece di una."),
  c("Monaco", 5, "Colpo Stordente", "Spendendo 1 ki quando colpisce con un attacco in mischia, il bersaglio deve superare un TS su COS o è stordito fino al turno successivo."),
  c("Monaco", 6, "Colpi Ki Potenziati", "I suoi colpi senz'armi contano come magici per superare resistenze e immunità."),
  c("Monaco", 7, "Evasione", "Nei TS su Destrezza per dimezzare i danni non ne subisce se ha successo e ne subisce metà se fallisce."),
  c("Monaco", 7, "Mente Serena", "Con un'azione termina un effetto su di sé che lo affascina o lo spaventa."),
  c("Monaco", 10, "Purezza del Corpo", "Immune a malattie e veleno."),
  c("Monaco", 13, "Lingua del Sole e della Luna", "Comprende ogni lingua parlata e ogni creatura capisce ciò che dice."),
  c("Monaco", 14, "Anima Adamantina", "Competenza in tutti i tiri salvezza; con una reazione e 1 ki può ritirare un TS fallito."),
  c("Monaco", 15, "Corpo Senza Età", "Non subisce più gli effetti dell'invecchiamento e non ha più bisogno di cibo e acqua."),
  c("Monaco", 18, "Corpo Vuoto", "Spendendo 4 ki diventa invisibile per 1 minuto e resiste a tutti i danni tranne quelli da forza."),
  c("Monaco", 20, "Perfezione Interiore", "Se tira iniziativa senza punti ki ne recupera 4."),

  s("Monaco", "Via della Mano Aperta", 3, "Tecnica della Mano Aperta", "Quando colpisce con Raffica di Colpi può imporre un effetto: caduta prona, spinta o impossibilità di reagire."),
  s("Monaco", "Via della Mano Aperta", 6, "Integrità del Corpo", "Con un'azione recupera PF pari a 3 × livello da monaco. Una volta per riposo lungo."),
  s("Monaco", "Via della Mano Aperta", 11, "Tranquillità", "Alla fine di un riposo lungo ottiene un effetto di Santuario che dura fino al riposo successivo."),
  s("Monaco", "Via della Mano Aperta", 17, "Palmo Tremante", "Spendendo 3 ki può innescare vibrazioni letali in una creatura colpita, che possono ucciderla."),
  s("Monaco", "Via dell'Ombra", 3, "Arti delle Ombre", "Con 2 ki può lanciare Oscurità, Passare Senza Tracce, Silenzio o Scurovisione senza componenti."),
  s("Monaco", "Via dell'Ombra", 6, "Passo delle Ombre", "Con un'azione bonus si teletrasporta di 18 m da un'area in ombra a un'altra e ha vantaggio al primo attacco."),
  s("Monaco", "Via dell'Ombra", 11, "Mantello delle Ombre", "Con un'azione può rendersi invisibile finché si trova in luce fioca o in oscurità."),
  s("Monaco", "Via dell'Ombra", 17, "Opportunista", "Con una reazione attacca una creatura che è stata colpita da un alleato entro 1,5 m da lei."),
  s("Monaco", "Via dei Quattro Elementi", 3, "Discepolo degli Elementi", "Impara Sintonia Elementale e una disciplina elementale (altre al 6°, 11° e 17° livello) alimentate dal ki."),
  s("Monaco", "Via dei Quattro Elementi", 6, "Discipline Elementali Aggiuntive", "Impara una nuova disciplina elementale; la spesa di ki ai livelli superiori aumenta gli effetti."),
  s("Monaco", "Via dei Quattro Elementi", 11, "Discipline Elementali Ulteriori", "Impara un'altra disciplina elementale; può spendere più ki per potenziare quelle già note."),
  s("Monaco", "Via dei Quattro Elementi", 17, "Discipline Elementali Superiori", "Impara un'ultima disciplina elementale, con effetti alimentati da più punti ki."),
];

const PALADINO: SemePrivilegioClasse[] = [
  c("Paladino", 2, "Stile di Combattimento (Paladino)", "Sceglie uno stile tra Combattere con Armi Possenti, Difesa, Duellare e Protezione."),
  c("Paladino", 2, "Incantesimi (Paladino)", "Lancia incantesimi da paladino usando il Carisma; prepara ogni giorno metà del livello + mod CAR incantesimi dall'intera lista. Usa un simbolo sacro come focus."),
  c("Paladino", 2, "Punizione Divina", "Quando colpisce in mischia con un'arma può spendere uno slot: 2d8 danni radiosi extra (+1d8 per ogni livello dello slot oltre il 1°, massimo 5d8; +1d8 contro immondi e non morti)."),
  c("Paladino", 3, "Salute Divina", "Immune alle malattie."),
  c("Paladino", 3, "Giuramento Sacro", "Sceglie un giuramento che gli concede privilegi al 3°, 7°, 15° e 20° livello."),
  c("Paladino", 5, "Attacco Extra", "Quando compie l'azione di Attacco può attaccare due volte invece di una."),
  c("Paladino", 6, "Aura di Protezione", "Lui e gli alleati entro 3 m aggiungono il suo modificatore di Carisma (minimo +1) ai tiri salvezza; 9 m dal 18° livello."),
  c("Paladino", 10, "Aura di Coraggio", "Lui e gli alleati entro 3 m non possono essere spaventati; 9 m dal 18° livello."),
  c("Paladino", 11, "Punizione Divina Migliorata", "Tutti i suoi colpi con armi da mischia infliggono 1d8 danni radiosi extra."),
  c("Paladino", 14, "Tocco Purificante", "Con un'azione termina un incantesimo su sé o su una creatura consenziente; usi pari al mod CAR (minimo 1) per riposo lungo."),

  s("Paladino", "Giuramento di Devozione", 3, "Incanalare Divinità: Arma Sacra", "Con un'azione carica un'arma: aggiunge il mod CAR ai tiri per colpire e la rende magica per 1 minuto."),
  s("Paladino", "Giuramento di Devozione", 3, "Incanalare Divinità: Scacciare gli Empi", "Con un'azione scaccia immondi e non morti entro 9 m che falliscono un TS su SAG."),
  s("Paladino", "Giuramento di Devozione", 7, "Aura di Devozione", "Lui e gli alleati entro 3 m non possono essere affascinati; 9 m dal 18° livello."),
  s("Paladino", "Giuramento di Devozione", 15, "Purezza dello Spirito", "Ha sempre gli effetti di Protezione dal Bene e dal Male."),
  s("Paladino", "Giuramento di Devozione", 20, "Aureola Sacra", "Con un'azione emana luce solare per 1 minuto e ha vantaggio ai TS contro incantesimi di immondi e non morti."),
  s("Paladino", "Giuramento degli Antichi", 3, "Incanalare Divinità: Ira della Natura", "Con un'azione fa emergere viticci spettrali che trattengono una creatura entro 3 m (TS FOR o DES)."),
  s("Paladino", "Giuramento degli Antichi", 3, "Incanalare Divinità: Scacciare gli Infedeli", "Con un'azione scaccia fatati e immondi entro 9 m che falliscono un TS su SAG."),
  s("Paladino", "Giuramento degli Antichi", 7, "Aura di Guardia", "Lui e gli alleati entro 3 m hanno resistenza ai danni degli incantesimi; 9 m dal 18° livello."),
  s("Paladino", "Giuramento degli Antichi", 15, "Sentinella Immortale", "Quando scende a 0 PF senza morire sul colpo resta a 1 PF, una volta per riposo lungo; non invecchia."),
  s("Paladino", "Giuramento degli Antichi", 20, "Campione Anziano", "Con un'azione si trasforma per 1 minuto: recupera 10 PF a turno, ha vantaggio ai TS contro incantesimi e lancia i suoi con un'azione bonus."),
  s("Paladino", "Giuramento di Vendetta", 3, "Incanalare Divinità: Abiurare il Nemico", "Con un'azione spaventa una creatura entro 18 m (TS SAG); immondi e non morti hanno svantaggio."),
  s("Paladino", "Giuramento di Vendetta", 3, "Incanalare Divinità: Voto di Inimicizia", "Con un'azione bonus dichiara un nemico entro 3 m: ha vantaggio ai tiri per colpire contro di lui per 1 minuto."),
  s("Paladino", "Giuramento di Vendetta", 7, "Vendicatore Implacabile", "Quando colpisce con un attacco di opportunità può muoversi di metà velocità verso la creatura senza provocare."),
  s("Paladino", "Giuramento di Vendetta", 15, "Anima di Vendetta", "Quando la creatura sotto Voto di Inimicizia attacca, può reagire con un attacco in mischia."),
  s("Paladino", "Giuramento di Vendetta", 20, "Angelo Vendicatore", "Con un'azione si trasforma per 1 ora: ali, volo e un'aura di terrore che spaventa i nemici entro 9 m."),
];

const RANGER: SemePrivilegioClasse[] = [
  c("Ranger", 2, "Stile di Combattimento (Ranger)", "Sceglie uno stile tra Combattere con Due Armi, Difesa, Duellare e Tiro."),
  c("Ranger", 2, "Incantesimi (Ranger)", "Lancia incantesimi da ranger usando la Saggezza; conosce un numero fisso di incantesimi e usa slot di mezzo incantatore."),
  c("Ranger", 3, "Archetipo del Ranger", "Sceglie un archetipo che gli concede privilegi al 3°, 7°, 11° e 15° livello."),
  c("Ranger", 3, "Consapevolezza Primordiale", "Spendendo uno slot percepisce la presenza di aberrazioni, celestiali, draghi, elementali, fatati, immondi e non morti entro 1,5 km."),
  c("Ranger", 5, "Attacco Extra", "Quando compie l'azione di Attacco può attaccare due volte invece di una."),
  c("Ranger", 6, "Nemico Prescelto Migliorato", "Sceglie un secondo tipo di nemico prescelto e impara un'altra lingua."),
  c("Ranger", 6, "Esploratore Nato Migliorato", "Sceglie un secondo terreno prediletto."),
  c("Ranger", 8, "Passo della Terra", "Attraversa terreno difficile non magico senza rallentare e piante non magiche senza danni."),
  c("Ranger", 10, "Esploratore Nato Superiore", "Sceglie un terzo terreno prediletto."),
  c("Ranger", 10, "Nascondersi in Piena Vista", "Con 1 minuto può camuffarsi con materiali naturali: +10 alle prove di Furtività finché resta fermo."),
  c("Ranger", 14, "Nemico Prescelto Superiore", "Sceglie un terzo tipo di nemico prescelto e impara un'altra lingua."),
  c("Ranger", 14, "Svanire", "Può usare Nascondersi come azione bonus e non può essere seguito tramite tracce non magiche."),
  c("Ranger", 18, "Sensi Ferini", "Non ha svantaggio contro le creature che non vede e percepisce quelle invisibili entro 9 m."),
  c("Ranger", 20, "Sterminatore di Nemici", "Una volta per turno può aggiungere il mod SAG a un tiro per colpire o per i danni contro un nemico prescelto."),

  s("Ranger", "Cacciatore", 3, "Preda del Cacciatore", "Sceglie un'abilità: Uccisore di Colossi (+1d8 a chi ha subito danni), Ammazzagiganti o Rovina delle Orde (attacco extra su un altro bersaglio)."),
  s("Ranger", "Cacciatore", 7, "Tattiche Difensive", "Sceglie una difesa: Fuga dalle Orde, Difesa Multiattacco o Volontà d'Acciaio."),
  s("Ranger", "Cacciatore", 11, "Attacco Multiplo", "Sceglie tra Raffica (attacco a distanza su tutti i bersagli in un raggio) e Attacco Turbinante (mischia su tutti i bersagli adiacenti)."),
  s("Ranger", "Cacciatore", 15, "Difesa Superiore del Cacciatore", "Sceglie una difesa: Evasione, Resistere alle Maree o Schivata Prodigiosa."),
  s("Ranger", "Signore delle Bestie", 3, "Compagno del Ranger", "Ottiene una bestia di GS 1/4 o inferiore che lo accompagna e agisce sotto il suo comando; la sua competenza segue quella del ranger."),
  s("Ranger", "Signore delle Bestie", 7, "Addestramento Eccezionale", "Con un'azione bonus il compagno può Scattare, Disimpegnarsi, Schivare o Aiutare; i suoi attacchi contano come magici."),
  s("Ranger", "Signore delle Bestie", 11, "Furia Bestiale", "Il compagno può attaccare due volte quando compie l'azione di Attacco."),
  s("Ranger", "Signore delle Bestie", 15, "Condividere Incantesimi", "Quando lancia un incantesimo su di sé può bersagliare anche il compagno entro 9 m."),
];

const STREGONE: SemePrivilegioClasse[] = [
  c("Stregone", 2, "Fonte di Magia", "Ha punti stregoneria pari al livello: li converte in slot (o slot in punti) o li spende per la Metamagia. Si ricaricano con il riposo lungo."),
  c("Stregone", 3, "Metamagia", "Impara due opzioni di Metamagia (Incantesimo Distante, Rapido, Gemello...) per modificare i propri incantesimi spendendo punti stregoneria."),
  c("Stregone", 10, "Metamagia Aggiuntiva", "Impara un'altra opzione di Metamagia."),
  c("Stregone", 17, "Metamagia Ulteriore", "Impara un'altra opzione di Metamagia."),
  c("Stregone", 20, "Ripristino Stregonesco", "Se tira iniziativa senza punti stregoneria ne recupera 4."),

  s("Stregone", "Discendenza Draconica", 6, "Affinità Elementale", "Aggiunge il mod CAR ai danni di un incantesimo del tipo del suo drago e può spendere 1 punto stregoneria per una resistenza a quel tipo."),
  s("Stregone", "Discendenza Draconica", 14, "Ali di Drago", "Con un'azione bonus fa spuntare ali da drago e ottiene una velocità di volo pari a quella a terra."),
  s("Stregone", "Discendenza Draconica", 18, "Presenza Draconica", "Spendendo 5 punti stregoneria emana un'aura di 18 m che ammalia o terrorizza le creature ostili."),
  s("Stregone", "Magia Selvaggia", 6, "Piegare la Fortuna", "Con una reazione, spendendo 2 punti stregoneria, aggiunge o toglie 1d4 a un tiro di una creatura entro 18 m."),
  s("Stregone", "Magia Selvaggia", 14, "Caos Controllato", "Quando tira sulla tabella della magia selvaggia può tirare due volte e scegliere il risultato."),
  s("Stregone", "Magia Selvaggia", 18, "Bombardamento di Incantesimi", "Se tira il massimo su un dado di danno di un incantesimo può tirare di nuovo quel dado e sommare il nuovo risultato."),
];

const WARLOCK: SemePrivilegioClasse[] = [
  c("Warlock", 2, "Suppliche Occulte", "Impara due suppliche occulte che gli conferiscono capacità permanenti o incantesimi (altre salendo di livello)."),
  c("Warlock", 3, "Dono del Patto", "Sceglie il dono del patto: Patto della Catena (famiglio), della Lama (arma evocata) o del Tomo (libro con trucchetti)."),
  c("Warlock", 11, "Arcanum Mistico (6° livello)", "Sceglie un incantesimo di 6° livello che può lanciare una volta per riposo lungo senza slot."),
  c("Warlock", 13, "Arcanum Mistico (7° livello)", "Sceglie un incantesimo di 7° livello che può lanciare una volta per riposo lungo senza slot."),
  c("Warlock", 15, "Arcanum Mistico (8° livello)", "Sceglie un incantesimo di 8° livello che può lanciare una volta per riposo lungo senza slot."),
  c("Warlock", 17, "Arcanum Mistico (9° livello)", "Sceglie un incantesimo di 9° livello che può lanciare una volta per riposo lungo senza slot."),
  c("Warlock", 20, "Maestro Ultraterreno", "Con 1 minuto di supplica al patrono recupera tutti gli slot del patto spesi. Una volta per riposo lungo."),

  s("Warlock", "Il Signore Fatato", 6, "Fuga Nebbiosa", "Quando subisce danni può reagire teletrasportandosi di 18 m in una nube di nebbia."),
  s("Warlock", "Il Signore Fatato", 10, "Difese Ammaliatrici", "Immune all'affascinamento e, con una reazione, rimanda un affascinamento su chi ci ha provato."),
  s("Warlock", "Il Signore Fatato", 14, "Delirio Oscuro", "Con un'azione fa entrare una creatura in un reame di illusione: è affascinata o spaventata finché lui si concentra."),
  s("Warlock", "L'Immondo", 6, "Fortuna dell'Oscuro", "Quando fa una prova o un tiro salvezza può aggiungere 1d10 al tiro. Una volta per riposo breve o lungo."),
  s("Warlock", "L'Immondo", 10, "Resilienza Immonda", "Dopo un riposo scegli un tipo di danno: hai resistenza contro di esso finché non cambi."),
  s("Warlock", "L'Immondo", 14, "Scagliare all'Inferno", "Quando colpisce con un attacco può mandare il bersaglio nei piani inferiori per un round (TS CAR); subisce 10d10 danni psichici se non è immondo. Una volta per riposo lungo."),
  s("Warlock", "Il Grande Antico", 6, "Difesa Entropica", "Con una reazione impone svantaggio a un attacco contro di lui e, se manca, può ottenere vantaggio al prossimo attacco. Una volta per riposo breve o lungo."),
  s("Warlock", "Il Grande Antico", 10, "Scudo Mentale", "I suoi pensieri non si possono leggere e ha resistenza ai danni psichici."),
  s("Warlock", "Il Grande Antico", 14, "Creare Servitore", "Con 1 minuto trasforma un umanoide incapacitato in un servitore aberrante che gli obbedisce."),
];

export const PRIVILEGI_AVANZATI: SemePrivilegioClasse[] = [
  ...BARBARO, ...BARDO, ...CHIERICO, ...DRUIDO, ...GUERRIERO, ...LADRO,
  ...MAGO, ...MONACO, ...PALADINO, ...RANGER, ...STREGONE, ...WARLOCK,
];
