import { PIU_DADI, inc, type Voce } from "./incantesimiSottoclassi.ts";

// Incantesimi di 2° e 3° livello del Manuale del Giocatore che non sono altrove nel catalogo
// (descrizioni riassunte, non il testo del manuale).

export const VOCI_M2_3: Record<string, Voce> = {
  // --- 2° livello ---
  "Aiuto": inc(["Chierico", "Paladino"], 2, "Abiurazione", "1 azione", "9 metri", "V, S, M (una striscia di stoffa bianca)", "8 ore",
    "Fino a tre creature aumentano di 5 i PF massimi e attuali per la durata.",
    { livelloSuperiore: "Il bonus ai PF aumenta di 5 per ogni livello di slot oltre il 2°." }),
  "Alterare Se Stesso": inc(["Mago", "Stregone"], 2, "Trasmutazione", "1 azione", "Incantatore", "V, S", "Concentrazione, fino a 1 ora",
    "L'incantatore sceglie una forma: respirare sott'acqua e nuotare, cambiare aspetto, oppure far crescere armi naturali (artigli, denti) che infliggono 1d6 e sono magiche."),
  "Messaggero Animale": inc(["Bardo", "Druido", "Ranger"], 2, "Ammaliamento", "1 azione", "9 metri", "V, S, M (un po' di cibo)", "24 ore",
    "Una bestia Minuscola recapita un messaggio fino a 25 parole a un luogo o a una persona descritta entro le ore previste.",
    { rituale: true, livelloSuperiore: "La durata aumenta di 48 ore per ogni livello di slot oltre il 2°." }),
  "Serratura Arcana": inc(["Mago"], 2, "Abiurazione", "1 azione", "Contatto", "V, S, M (polvere d'oro da 25 mo)", "Finché non viene dissolto",
    "Una porta, finestra o contenitore toccato è sigillato: si apre solo per chi l'incantatore indica o con una parola d'ordine. La CD per forzarlo o scassinarlo sale di 10."),
  "Aura Magica dell'Arcanista": inc(["Mago"], 2, "Illusione", "1 minuto", "Contatto", "V, S, M (un quadratino di seta)", "24 ore",
    "Altera l'aura magica di un oggetto toccato (nasconde la magia, la fa sembrare di un'altra scuola o fa sembrare magico un oggetto normale) e ne cambia il rilevamento da parte di Individuazione del Magico."),
  "Sensi della Bestia": inc(["Druido", "Ranger"], 2, "Divinazione", "1 azione", "Contatto", "S", "Concentrazione, fino a 1 ora",
    "L'incantatore tocca una bestia consenziente: può usare i suoi sensi con un'azione, restando cieco e sordo ai propri.",
    { rituale: true }),
  "Punizione Marchiante": inc(["Paladino"], 2, "Invocazione", "1 azione bonus", "Incantatore", "V", "Concentrazione, fino a 1 minuto",
    "Il prossimo colpo con un'arma infligge 2d6 danni radiosi extra e rende visibile il bersaglio, brillante per la durata: anche l'invisibilità non lo nasconde e non può ottenere benefici dall'oscurità.",
    { livelloSuperiore: PIU_DADI("1d6") }),
  "Fiamma Perenne": inc(["Chierico", "Mago"], 2, "Invocazione", "1 azione", "Contatto", "V, S, M (polvere di rubino da 50 mo)", "Finché non viene dissolta",
    "Una fiamma senza calore, pari a una torcia, si accende su un oggetto toccato: fa luce intensa per 6 metri e fioca per altri 6."),
  "Cordone di Frecce": inc(["Ranger"], 2, "Trasmutazione", "1 azione", "Contatto", "V, S, M (quattro o più frecce o dardi)", "8 ore",
    "Pianta quattro munizioni nel terreno: la prima creatura ostile che entra entro 9 metri dà il via a una scarica di una munizione che infligge 1d6 danni perforanti se fallisce il tiro salvezza, poi la munizione si consuma.",
    { tiroSalvezza: { car: "DES", effetto: "nessun effetto" }, danni: { dado: "1d6", tipo: "perforanti" } }),
  "Corona della Follia": inc(["Bardo", "Mago", "Stregone", "Warlock"], 2, "Ammaliamento", "1 azione", "36 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Un umanoide che fallisce il tiro salvezza è affascinato: nel suo turno deve usare il movimento e un'azione per attaccare una creatura vicina scelta dall'incantatore. Ad ogni turno può ripetere il tiro salvezza.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Scurovisione": inc(["Druido", "Mago", "Ranger", "Stregone"], 2, "Trasmutazione", "1 azione", "Contatto", "V, S, M (una carota secca o un'agata)", "8 ore",
    "Una creatura consenziente toccata vede al buio per 18 metri come se fosse luce fioca."),
  "Potenziare Caratteristica": inc(["Bardo", "Chierico", "Druido", "Stregone"], 2, "Trasmutazione", "1 azione", "Contatto", "V, S, M (pelo o piuma)", "Concentrazione, fino a 1 ora",
    "Una creatura toccata ottiene vantaggio alle prove di una caratteristica a scelta, con un beneficio in più: Costituzione (2d6 PF temporanei), Forza (carico doppio), Destrezza (niente danni da caduta fino a 6 m), Carisma, Intelligenza o Saggezza.",
    { livelloSuperiore: "Una creatura in più per ogni livello di slot oltre il 2°." }),
  "Ingrandire/Ridurre": inc(["Bardo", "Druido", "Mago", "Stregone"], 2, "Trasmutazione", "1 azione", "9 metri", "V, S, M (un pizzico di polvere di ferro)", "Concentrazione, fino a 1 minuto",
    "Una creatura o un oggetto cambia taglia: ingrandita è più forte (vantaggio alle prove e ai TS di Forza, +1d4 ai danni delle armi), ridotta danneggia meno (−1d4) e ha svantaggio. Il bersaglio non consenziente può evitare l'effetto con un tiro salvezza su Costituzione.",
    { tiroSalvezza: { car: "COS", effetto: "nessun effetto" } }),
  "Incantare": inc(["Bardo", "Warlock"], 2, "Ammaliamento", "1 azione", "27 metri", "V, S", "1 minuto",
    "Le creature che l'incantatore sceglie e che lo vedono, se falliscono il tiro salvezza, restano affascinate dalle sue parole e hanno svantaggio alle prove di Saggezza (Percezione) verso chiunque altro.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Trovare Destriero": inc(["Paladino"], 2, "Evocazione", "10 minuti", "9 metri", "V, S", "Istantanea",
    "Un destriero ultraterreno (cavallo da guerra, pony, cammello, alce o mastino) appare, intelligente e fedele: obbedisce, comprende la lingua dell'incantatore e condivide gli incantesimi su di sé con lui."),
  "Trovare Trappole": inc(["Chierico", "Druido", "Ranger"], 2, "Divinazione", "1 azione", "36 metri", "V, S", "Istantanea",
    "L'incantatore percepisce la presenza di trappole entro gittata e in linea di vista, ma non la loro posizione esatta né la natura; sa solo che esistono."),
  "Lama Infuocata": inc(["Druido"], 2, "Evocazione", "1 azione bonus", "Incantatore", "V, S, M (una foglia di sommacco)", "Concentrazione, fino a 10 minuti",
    "Una lama infuocata appare in mano all'incantatore: attacco in mischia con incantesimo, 3d6 danni da fuoco, e fa luce intensa per 3 metri. Con un'azione bonus la si può far riapparire.",
    { attacco: { numero: 1 }, danni: { dado: "3d6", tipo: "da fuoco", perAttacco: true }, livelloSuperiore: "+1d6 danni per ogni due livelli di slot oltre il 2°." }),
  "Riposo Inviolato": inc(["Chierico", "Mago"], 2, "Necromanzia", "1 azione", "Contatto", "V, S, M (un pizzico di sale e una moneta su ogni occhio)", "10 giorni",
    "Un cadavere toccato non può diventare non morto e non si decompone: il tempo trascorso non conta per i limiti di Rianimare Morti.",
    { rituale: true }),
  "Metallo Incandescente": inc(["Bardo", "Druido"], 2, "Trasmutazione", "1 azione", "18 metri", "V, S, M (un pezzo di ferro e una fiamma)", "Concentrazione, fino a 1 minuto",
    "Un oggetto di metallo diventa rovente: 2d8 danni da fuoco a chi lo tocca o lo indossa, che deve superare un tiro salvezza su Costituzione o lascia l'oggetto o ha svantaggio a prove e attacchi. Con un'azione bonus ripete i danni.",
    { tiroSalvezza: { car: "COS", effetto: "nessuno svantaggio" }, danni: { dado: "2d8", tipo: "da fuoco", perLivello: "1d8" }, livelloSuperiore: PIU_DADI("1d8") }),
  "Scasso": inc(["Bardo", "Mago", "Stregone", "Warlock"], 2, "Trasmutazione", "1 azione", "18 metri", "V", "Istantanea",
    "Sblocca un oggetto chiuso entro gittata (porta, scrigno, catena, serratura arcana per 10 minuti). Un boato udibile a 90 metri avvisa chi è vicino."),
  "Levitazione": inc(["Mago", "Stregone"], 2, "Trasmutazione", "1 azione", "18 metri", "V, S, M (una piccola freccia di cuoio)", "Concentrazione, fino a 10 minuti",
    "Una creatura o un oggetto (fino a 250 kg) si solleva a 6 metri di quota; la creatura può muoversi solo spingendosi su oggetti. Un bersaglio non consenziente evita l'effetto con un tiro salvezza su Costituzione.",
    { tiroSalvezza: { car: "COS", effetto: "nessun effetto" } }),
  "Localizzare Animali o Piante": inc(["Bardo", "Druido", "Ranger"], 2, "Divinazione", "1 azione", "Incantatore", "V, S, M (pelo di segugio)", "Istantanea",
    "L'incantatore percepisce direzione e distanza della più vicina bestia o pianta di un tipo specifico entro 7,5 km.",
    { rituale: true }),
  "Localizzare Oggetto": inc(["Bardo", "Chierico", "Druido", "Mago", "Paladino", "Ranger"], 2, "Divinazione", "1 azione", "Incantatore", "V, S, M (un ramo a forcella)", "Concentrazione, fino a 10 minuti",
    "L'incantatore percepisce la direzione di un oggetto conosciuto entro 300 metri, o dell'oggetto più vicino di un tipo specifico. Non lo trova se è schermato da piombo."),
  "Bocca Magica": inc(["Bardo", "Mago"], 2, "Illusione", "1 minuto", "9 metri", "V, S, M (un pezzo di favo e polvere di giada da 10 mo)", "Finché non viene dissolta",
    "Imprime un messaggio di massimo 25 parole in un oggetto: una bocca appare e lo recita quando scatta la condizione fissata dall'incantatore.",
    { rituale: true }),
  "Preghiera di Guarigione": inc(["Chierico"], 2, "Invocazione", "10 minuti", "9 metri", "V", "Istantanea",
    "Fino a sei creature entro gittata recuperano 2d8 + il modificatore di caratteristica da incantatore PF. Non ha effetto su non morti e costrutti.",
    { livelloSuperiore: "+1d8 PF per ogni livello di slot oltre il 2°." }),
  "Protezione dal Veleno": inc(["Chierico", "Druido", "Paladino", "Ranger"], 2, "Abiurazione", "1 azione", "Contatto", "V, S", "1 ora",
    "Neutralizza un veleno su una creatura toccata. Per 1 ora ha vantaggio ai tiri salvezza contro veleni e resistenza ai danni da veleno."),
  "Raggio di Indebolimento": inc(["Mago", "Warlock"], 2, "Necromanzia", "1 azione", "18 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Attacco a distanza con incantesimo: se colpisce, il bersaglio infligge solo metà dei danni con gli attacchi basati sulla Forza e può ripetere il TS su Costituzione alla fine di ogni suo turno.",
    { attacco: { numero: 1 }, tiroSalvezza: { car: "COS", effetto: "l'incantesimo termina" } }),
  "Trucco della Corda": inc(["Mago"], 2, "Trasmutazione", "1 azione", "Contatto", "S, M (estratto di grano e un anello di pergamena)", "1 ora",
    "Una corda toccata sale in aria aprendo uno spazio extradimensionale in cima, che ospita fino a otto creature Medie."),
  "Vedere Invisibile": inc(["Bardo", "Mago", "Stregone"], 2, "Divinazione", "1 azione", "Incantatore", "V, S, M (talco e un pizzico di argento)", "1 ora",
    "L'incantatore vede le creature e gli oggetti invisibili entro 9 metri, e vede il Piano Etereo."),
  "Legame Protettivo": inc(["Chierico", "Paladino"], 2, "Abiurazione", "1 azione", "Contatto", "V, S, M (due anelli di platino da 50 mo)", "1 ora",
    "Una creatura consenziente toccata ottiene +1 alla CA e ai tiri salvezza e resistenza a tutti i danni; l'incantatore subisce gli stessi danni che essa evita."),

  // --- 3° livello ---
  "Animare Morti": inc(["Chierico", "Mago"], 3, "Necromanzia", "1 minuto", "3 metri", "V, S, M (una goccia di sangue, un pezzo di carne e polvere d'ossa)", "Istantanea",
    "Rianima un cumulo di ossa o un cadavere Medio o Piccolo come scheletro o zombi sotto il controllo dell'incantatore per 24 ore (poi va di nuovo lanciato per mantenerlo).",
    { livelloSuperiore: "Una creatura in più per ogni livello di slot oltre il 3°." }),
  "Maledizione": inc(["Bardo", "Chierico", "Mago"], 3, "Necromanzia", "1 azione", "Contatto", "V, S", "Concentrazione, fino a 1 minuto",
    "Una creatura toccata che fallisce il tiro salvezza subisce una maledizione a scelta: svantaggio alle prove di una caratteristica, ai tiri per colpire contro l'incantatore, a sprecare il turno, o 1d8 danni necrotici extra.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" }, livelloSuperiore: "Con uno slot di 4° livello dura 10 minuti, di 5° 8 ore, di 7° 24 ore, di 9° finché dissolto." }),
  "Punizione Accecante": inc(["Paladino"], 3, "Invocazione", "1 azione bonus", "Incantatore", "V", "Concentrazione, fino a 1 minuto",
    "Il prossimo colpo in mischia con un'arma infligge 3d8 danni radiosi extra e il bersaglio è accecato finché non supera un tiro salvezza su Costituzione.",
    { tiroSalvezza: { car: "COS", effetto: "non è accecato" } }),
  "Evocare Animali": inc(["Druido", "Ranger"], 3, "Evocazione", "1 azione", "18 metri", "V, S", "Concentrazione, fino a 1 ora",
    "Fa apparire spiriti animali sotto forma di bestie: una di grado sfida 2, due di 1, quattro di 1/2 o otto di 1/4, che combattono per l'incantatore.",
    { livelloSuperiore: "Il numero di bestie cresce con slot di 5°, 7° e 9° livello." }),
  "Evocare Proiettili": inc(["Ranger"], 3, "Evocazione", "1 azione", "Incantatore (cono di 18 metri)", "V, S, M (una munizione o un'arma da lancio)", "Istantanea",
    "L'incantatore scaglia un'arma: la sua copia si moltiplica in un cono di 18 metri; chi fallisce il tiro salvezza subisce 3d8 danni (metà se lo supera).",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "3d8", tipo: "dell'arma", perLivello: "1d8" }, livelloSuperiore: PIU_DADI("1d8") }),
  "Controincantesimo": inc(["Mago", "Stregone", "Warlock"], 3, "Abiurazione", "1 reazione, quando l'incantatore vede una creatura entro 18 metri lanciare un incantesimo", "18 metri", "S", "Istantanea",
    "Interrompe l'incantesimo della creatura: se è di 3° livello o inferiore fallisce; se è superiore serve una prova di caratteristica da incantatore (CD 10 + livello dell'incantesimo).",
    { livelloSuperiore: "Interrompe automaticamente un incantesimo di livello pari allo slot usato o inferiore." }),
  "Arma Elementale": inc(["Paladino"], 3, "Trasmutazione", "1 azione", "Contatto", "V, S", "Concentrazione, fino a 1 ora",
    "Un'arma non magica toccata diventa magica con +1 al tiro per colpire e infligge 1d4 danni extra di acido, freddo, fuoco, fulmine o tuono a scelta.",
    { livelloSuperiore: "Con slot di 5° o 6° livello il bonus è +2 e i danni extra 2d4; con 7° o più +3 e 3d4." }),
  "Paura": inc(["Bardo", "Mago", "Stregone", "Warlock"], 3, "Illusione", "1 azione", "Incantatore (cono di 9 metri)", "V, S, M (una piuma bianca o il cuore di una gallina)", "Concentrazione, fino a 1 minuto",
    "Le creature nel cono che falliscono il tiro salvezza sono spaventate: lasciano cadere ciò che stringono e fuggono. Ripetono il TS alla fine di ogni turno in cui non vedono più l'incantatore.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Fingere la Morte": inc(["Bardo", "Chierico", "Druido", "Mago"], 3, "Necromanzia", "1 azione", "Contatto", "V, S, M (un pizzico di terra di cimitero)", "1 ora",
    "Una creatura consenziente appare morta: è cieca e incapacitata, ha resistenza a tutti i danni tranne psichici, ed è immune a veleni e malattie.",
    { rituale: true }),
  "Volare": inc(["Mago", "Stregone", "Warlock"], 3, "Trasmutazione", "1 azione", "Contatto", "V, S, M (una piuma d'ala)", "Concentrazione, fino a 10 minuti",
    "La creatura toccata ottiene una velocità di volo di 18 metri per la durata. Se l'effetto termina in volo, la creatura cade.",
    { livelloSuperiore: "Una creatura in più per ogni livello di slot oltre il 3°." }),
  "Glifo di Interdizione": inc(["Bardo", "Chierico", "Mago"], 3, "Abiurazione", "1 ora", "Contatto", "V, S, M (polvere di diamante da 200 mo)", "Finché non viene dissolto o innescato",
    "Traccia un glifo su una superficie o un oggetto: quando viene innescato esplode (5d8 danni di un tipo a scelta in 6 metri) o rilascia un incantesimo di 3° livello o inferiore immagazzinato.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "5d8", tipo: "dell'energia scelta", perLivello: "1d8" }, livelloSuperiore: PIU_DADI("1d8") }),
  "Fame di Hadar": inc(["Warlock"], 3, "Evocazione", "1 azione", "45 metri", "V, S, M (un tentacolo in salamoia)", "Concentrazione, fino a 1 minuto",
    "Una sfera di oscurità di 6 metri di raggio blocca la luce e il suono: chi inizia il turno nell'area subisce 2d6 danni da freddo e chi lo finisce lì deve superare un tiro salvezza su Destrezza o subisce 2d6 danni da acido.",
    { tiroSalvezza: { car: "DES", effetto: "nessun effetto" }, danni: { dado: "2d6", tipo: "da acido" } }),
  "Motivo Ipnotico": inc(["Bardo", "Mago", "Stregone", "Warlock"], 3, "Illusione", "1 azione", "36 metri", "S, M (un bastoncino d'incenso o una fiala di cristallo)", "Concentrazione, fino a 1 minuto",
    "Un disegno colorato in un cubo di 9 metri affascina le creature che falliscono il tiro salvezza: sono incapacitate e con velocità 0 finché subiscono danni o vengono scosse.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Minuscola Capanna di Leomund": inc(["Bardo", "Mago"], 3, "Invocazione", "1 minuto", "Incantatore (emisfero di 3 metri)", "V, S, M (una perla di cristallo)", "8 ore",
    "Una cupola immobile di forza protegge fino a nove creature Medie: all'interno la temperatura è confortevole e nulla di ostile la attraversa.",
    { rituale: true }),
  "Freccia Fulminante": inc(["Ranger"], 3, "Trasmutazione", "1 azione bonus", "Incantatore", "V, S", "Concentrazione, fino a 1 minuto",
    "Il prossimo attacco a distanza con un'arma diventa un fulmine: infligge 4d8 danni da fulmine extra (metà se manca) e il bersaglio e le creature entro 3 metri subiscono 2d8 da fulmine, dimezzati con il tiro salvezza.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "4d8", tipo: "da fulmine", perLivello: "1d8" }, livelloSuperiore: PIU_DADI("1d8") }),
  "Cerchio Magico": inc(["Chierico", "Mago", "Paladino", "Warlock"], 3, "Abiurazione", "1 minuto", "3 metri", "V, S, M (acqua santa o polvere d'argento e ferro da 100 mo)", "1 ora",
    "Un cilindro di 3 metri di raggio impedisce a un tipo di creatura (celestiali, elementali, folletti, immondi, non morti) di entrare o di affascinare, spaventare o possedere chi è all'interno.",
    { livelloSuperiore: "La durata aumenta di 1 ora per ogni livello di slot oltre il 3°." }),
  "Immagine Maggiore": inc(["Bardo", "Mago", "Stregone", "Warlock"], 3, "Illusione", "1 azione", "36 metri", "V, S, M (un po' di vello)", "Concentrazione, fino a 10 minuti",
    "Un'illusione visiva e sonora di un oggetto, una creatura o un fenomeno, in un cubo di 6 metri, con anche odori e temperatura. Un'interazione fisica o un'indagine riuscita la rivela.",
    { livelloSuperiore: "Con uno slot di 6° livello o superiore dura senza concentrazione per 24 ore." }),
  "Parola Guaritrice di Massa": inc(["Chierico"], 3, "Invocazione", "1 azione bonus", "18 metri", "V", "Istantanea",
    "Fino a sei creature visibili entro gittata recuperano 1d4 + il modificatore di caratteristica da incantatore PF. Non ha effetto su non morti e costrutti.",
    { livelloSuperiore: "+1d4 PF per ogni livello di slot oltre il 3°." }),
  "Destriero Fantasma": inc(["Mago"], 3, "Illusione", "1 minuto", "9 metri", "V, S", "1 ora",
    "Una creatura quasi equina e semitrasparente, spettrale, appare: un destriero con velocità 30 metri che porta l'incantatore e fino a tre persone, camminando anche sull'acqua.",
    { rituale: true }),
  "Rimuovere Maledizione": inc(["Chierico", "Mago", "Paladino", "Warlock"], 3, "Abiurazione", "1 azione", "Contatto", "V, S", "Istantanea",
    "Tutte le maledizioni su una creatura o un oggetto toccato terminano; se l'oggetto è magico e maledetto la maledizione resta ma non ha più effetto sulla sintonia."),
  "Parlare con le Piante": inc(["Bardo", "Druido", "Ranger"], 3, "Trasmutazione", "1 azione", "Incantatore (raggio di 9 metri)", "V, S", "10 minuti",
    "L'incantatore dà alle piante vicine la capacità di comunicare: può interrogarle sulla zona e farle spostare il terreno difficile in normale o viceversa."),
  "Lingue": inc(["Bardo", "Chierico", "Mago", "Stregone", "Warlock"], 3, "Divinazione", "1 azione", "Contatto", "V, M (un piccolo modello di zigurat)", "1 ora",
    "La creatura toccata comprende qualsiasi linguaggio parlato e può essere capita da chiunque conosca almeno una lingua."),
  "Tocco Vampirico": inc(["Mago", "Warlock"], 3, "Necromanzia", "1 azione", "Incantatore", "V, S", "Concentrazione, fino a 1 minuto",
    "Attacco in mischia con incantesimo: 3d6 danni necrotici e l'incantatore recupera metà dei danni inflitti in PF. Con un'azione ripete l'attacco.",
    { attacco: { numero: 1 }, danni: { dado: "3d6", tipo: "necrotici", perLivello: "1d6", perAttacco: true }, livelloSuperiore: PIU_DADI("1d6") }),
  "Aura di Vitalità": inc(["Paladino"], 3, "Invocazione", "1 azione", "Incantatore (raggio di 9 metri)", "V", "Concentrazione, fino a 1 minuto",
    "Un'aura di energia curativa: con un'azione bonus a turno l'incantatore fa recuperare 2d6 punti ferita a una creatura nell'aura."),
};
