import { PIU_DADI, inc, type Voce } from "./incantesimiSottoclassi.ts";

// Incantesimi dal 6° al 9° livello del Manuale del Giocatore (descrizioni riassunte, non il testo del manuale).

export const VOCI_M6_9: Record<string, Voce> = {
  // --- 6° livello ---
  "Barriera di Lame": inc(["Chierico"], 6, "Invocazione", "1 azione", "27 metri", "V, S", "Concentrazione, fino a 10 minuti",
    "Un muro di lame rotanti (fino a 30 metri di lunghezza, 6 di altezza): chi inizia il turno nell'area o vi entra subisce 6d10 danni taglienti (metà con il tiro salvezza superato). Fornisce copertura tre quarti.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "6d10", tipo: "taglienti" } }),
  "Catena di Fulmini": inc(["Mago", "Stregone"], 6, "Invocazione", "1 azione", "45 metri", "V, S, M (un po' di pelliccia, ambra o cristallo e tre spilli d'argento)", "Istantanea",
    "Un fulmine colpisce un bersaglio e poi salta fino a quattro altre creature entro 9 metri: ciascuna subisce 10d8 danni da fulmine (metà con il tiro salvezza superato).",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "10d8", tipo: "da fulmine" }, livelloSuperiore: "Un bersaglio in più per ogni livello di slot oltre il 6°." }),
  "Cerchio della Morte": inc(["Mago", "Stregone", "Warlock"], 6, "Necromanzia", "1 azione", "45 metri", "V, S, M (la polvere di una perla nera da 500 mo)", "Istantanea",
    "Una sfera di energia negativa di 18 metri di raggio: le creature subiscono 8d6 danni necrotici (metà con il tiro salvezza superato).",
    { tiroSalvezza: { car: "COS", effetto: "metà danni" }, danni: { dado: "8d6", tipo: "necrotici", perLivello: "2d6" }, livelloSuperiore: PIU_DADI("2d6") }),
  "Evocare Fatati": inc(["Druido", "Warlock"], 6, "Evocazione", "1 minuto", "27 metri", "V, S", "Concentrazione, fino a 1 ora",
    "Chiama una creatura fatata di grado sfida 6 o inferiore, che appare amica e obbedisce all'incantatore; se la concentrazione si spezza, diventa ostile.",
    { livelloSuperiore: "Con slot più alti il grado sfida massimo sale (7 a 7°, 8 a 8°, 9 a 9° livello)." }),
  "Contingenza": inc(["Mago"], 6, "Invocazione", "10 minuti", "Incantatore", "V, S, M (una statuetta d'avorio e una gemma da 1.500 mo)", "10 giorni",
    "L'incantatore prepara un incantesimo di 5° livello o inferiore che si attiva da solo quando si verifica una condizione stabilita in anticipo, su di lui."),
  "Creare Non Morti": inc(["Chierico", "Mago", "Warlock"], 6, "Necromanzia", "1 minuto", "3 metri", "V, S, M (un vaso di argilla con terra di tomba e una pietra nera da 150 mo)", "Istantanea",
    "Anima fino a tre cadaveri Medi o Piccoli come ghoul, che obbediscono all'incantatore per 24 ore (poi serve un nuovo lancio per mantenerli). Si può farlo solo di notte.",
    { livelloSuperiore: "Con slot di 7°, 8° o 9° livello si creano ombre, spettri o mummie e più creature." }),
  "Disintegrare": inc(["Mago", "Stregone"], 6, "Trasmutazione", "1 azione", "18 metri", "V, S, M (una calamita e un pizzico di polvere)", "Istantanea",
    "Un raggio verde: se il bersaglio fallisce il tiro salvezza subisce 10d6 + 40 danni da forza; se arriva a 0 PF diventa polvere. Distrugge anche oggetti e costrutti di forza.",
    { tiroSalvezza: { car: "DES", effetto: "nessun danno" }, danni: { dado: "10d6", mod: 40, tipo: "da forza", perLivello: "3d6" }, livelloSuperiore: "+3d6 danni per ogni livello di slot oltre il 6°." }),
  "Convocazione Istantanea di Drawmij": inc(["Mago"], 6, "Evocazione", "1 minuto", "Contatto", "V, S, M (uno zaffiro da 1.000 mo)", "Finché non viene dissolta",
    "Associa un oggetto (fino a 5 kg) a uno zaffiro: l'incantatore può richiamarlo da qualsiasi luogo e distanza con una parola.",
    { rituale: true }),
  "Malocchio": inc(["Bardo", "Mago", "Stregone", "Warlock"], 6, "Necromanzia", "1 azione", "Incantatore", "V, S", "Concentrazione, fino a 1 minuto",
    "L'occhio dell'incantatore diventa nero: con un'azione a turno colpisce una creatura che vede entro 18 metri, che se fallisce il tiro salvezza è addormentata, spaventata o malata (a scelta, con effetti diversi).",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Trovare la Via": inc(["Bardo", "Chierico", "Druido"], 6, "Divinazione", "1 minuto", "Incantatore", "V, S, M (un gioco di attrezzi da divinazione da 100 mo)", "Concentrazione, fino a 1 giorno",
    "L'incantatore conosce la via più breve e diretta verso un luogo fisso conosciuto sullo stesso piano, come se vedesse la direzione e la distanza."),
  "Interdizione": inc(["Chierico"], 6, "Abiurazione", "10 minuti", "Contatto", "V, S, M (acqua santa, incenso e polvere di rubino da 1.000 mo)", "24 ore",
    "Protegge un'area fino a 4.000 m² dai teletrasporti e dal viaggio planare, e a scelta infligge 5d10 danni radiosi o necrotici a chi vi entra.",
    { rituale: true }),
  "Globo di Invulnerabilità": inc(["Mago", "Stregone"], 6, "Abiurazione", "1 azione", "Incantatore (raggio di 3 metri)", "V, S, M (una perla di vetro)", "Concentrazione, fino a 1 minuto",
    "Una barriera immobile impedisce il passaggio degli incantesimi di 5° livello o inferiore: non hanno effetto su chi è all'interno.",
    { livelloSuperiore: "Blocca anche gli incantesimi di un livello più alto per ogni livello di slot oltre il 6°." }),
  "Guardie e Interdizioni": inc(["Bardo", "Mago"], 6, "Abiurazione", "10 minuti", "Contatto", "V, S, M (incenso, zolfo, olio, corda, vino e una bacchetta)", "24 ore",
    "Protegge un'area fino a 800 m²: nebbia, porte sigillate, scale ingarbugliate, ragnatele, sentieri ingannevoli e altro; si possono impostare allarmi e una parola d'ordine."),
  "Nuocere": inc(["Chierico"], 6, "Necromanzia", "1 azione", "18 metri", "V, S", "Istantanea",
    "Una malattia aggredisce il bersaglio: se fallisce il tiro salvezza subisce 14d6 danni necrotici e i suoi PF massimi si riducono dello stesso valore; non scende sotto 1 PF.",
    { tiroSalvezza: { car: "COS", effetto: "metà danni" }, danni: { dado: "14d6", tipo: "necrotici" } }),
  "Guarigione": inc(["Chierico", "Druido"], 6, "Invocazione", "1 azione", "18 metri", "V, S", "Istantanea",
    "Una creatura visibile recupera 70 punti ferita e viene curata da cecità, sordità e malattie. Non ha effetto su non morti e costrutti.",
    { livelloSuperiore: "+10 PF per ogni livello di slot oltre il 6°." }),
  "Banchetto degli Eroi": inc(["Bardo", "Chierico", "Druido"], 6, "Evocazione", "10 minuti", "9 metri", "V, S, M (una ciotola ingioiellata da 1.000 mo)", "Istantanea",
    "Un banchetto per fino a dodici creature, che dopo un'ora ottengono per 24 ore immunità a veleno e paura, vantaggio ai tiri salvezza su Saggezza e PF massimi aumentati di 2d10."),
  "Vaso Magico": inc(["Mago", "Warlock"], 6, "Necromanzia", "1 minuto", "Incantatore", "V, S, M (una gemma da 500 mo o un cristallo)", "Finché non viene dissolto",
    "L'anima dell'incantatore entra in un contenitore e può possedere un umanoide che fallisce il tiro salvezza su Carisma, controllandone il corpo.",
    { tiroSalvezza: { car: "CAR", effetto: "nessun effetto" } }),
  "Suggestione di Massa": inc(["Bardo", "Mago", "Stregone", "Warlock"], 6, "Ammaliamento", "1 azione", "18 metri", "V, M (una lingua di serpente)", "24 ore",
    "Come Suggestione, ma agisce su fino a dodici creature che fallisce il tiro salvezza su Saggezza.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" }, livelloSuperiore: "Con slot di 7° livello dura 10 giorni, di 8° 30 giorni, di 9° 366 giorni." }),
  "Spostare Terreno": inc(["Druido", "Mago", "Stregone"], 6, "Trasmutazione", "1 azione", "36 metri", "V, S, M (una lama di ferro e una manciata di terra)", "Concentrazione, fino a 2 ore",
    "Rimodella un'area di 12 metri di lato: alza, abbassa o sposta il terreno (terra, sabbia, argilla) con una modifica ogni 10 minuti."),
  "Sfera Congelante di Otiluke": inc(["Mago"], 6, "Invocazione", "1 azione", "90 metri", "V, S, M (una sfera di cristallo)", "Istantanea",
    "Una sfera di gelo di 18 metri di raggio: 10d6 danni da freddo (metà con il tiro salvezza superato) e l'acqua si congela.",
    { tiroSalvezza: { car: "COS", effetto: "metà danni" }, danni: { dado: "10d6", tipo: "da freddo", perLivello: "1d6" }, livelloSuperiore: PIU_DADI("1d6") }),
  "Danza Irresistibile di Otto": inc(["Bardo", "Mago"], 6, "Ammaliamento", "1 azione", "9 metri", "V", "Concentrazione, fino a 1 minuto",
    "Una creatura è costretta a ballare: ha svantaggio ai tiri salvezza su Destrezza e ai tiri per colpire, gli attacchi contro di lei hanno vantaggio e deve usare il movimento per ballare. Non può essere fatta ballare con il tiro salvezza superato.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Alleato Planare": inc(["Chierico"], 6, "Evocazione", "10 minuti", "18 metri", "V, S", "Istantanea",
    "L'incantatore chiede aiuto a un'entità ultraterrena (celestiale, elementale o immondo): arriva un servitore che chiede un pagamento in cambio di un compito."),
  "Illusione Programmata": inc(["Bardo", "Mago"], 6, "Illusione", "1 azione", "36 metri", "V, S, M (un po' di vello e polvere di giada da 25 mo)", "Finché non viene dissolta",
    "Un'illusione visiva e sonora (fino a un cubo di 9 metri) che si attiva quando si verifica la condizione stabilita e dura fino a 5 minuti."),
  "Raggio di Sole": inc(["Druido", "Mago", "Stregone"], 6, "Invocazione", "1 azione", "Incantatore (linea di 18 metri)", "V, S, M (una lente d'ingrandimento)", "Concentrazione, fino a 1 minuto",
    "Una linea di luce di 1,5 metri di larghezza: le creature subiscono 6d8 danni radiosi e sono accecate (metà dei danni e non accecate se superano il tiro salvezza). Con un'azione si ripete.",
    { tiroSalvezza: { car: "COS", effetto: "metà danni e non accecato" }, danni: { dado: "6d8", tipo: "radiosi" } }),
  "Trasporto Vegetale": inc(["Druido"], 6, "Evocazione", "1 azione", "3 metri", "V, S", "1 round",
    "Dà alle piante la capacità di fare da porta: una creatura che entra in una pianta può uscire da un'altra pianta della stessa specie entro 1,5 km."),
  "Visione del Vero": inc(["Bardo", "Chierico", "Mago", "Stregone", "Warlock"], 6, "Divinazione", "1 azione", "Contatto", "V, S, M (un unguento per gli occhi da 25 mo)", "1 ora",
    "La creatura toccata vede nell'oscurità per 36 metri, vede il Piano Etereo, riconosce creature e oggetti invisibili, illusioni, trasformazioni e porte segrete."),
  "Muro di Ghiaccio": inc(["Mago"], 6, "Invocazione", "1 azione", "36 metri", "V, S, M (un pezzetto di quarzo)", "Concentrazione, fino a 10 minuti",
    "Un muro di ghiaccio (10 pannelli di 3 metri o una cupola): chi è nell'area quando appare subisce 10d6 danni da freddo (metà con il tiro salvezza superato). Il muro blocca, ma può essere distrutto.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "10d6", tipo: "da freddo", perLivello: "2d6" }, livelloSuperiore: "+2d6 danni per ogni livello di slot oltre il 6°." }),
  "Muro di Spine": inc(["Druido"], 6, "Evocazione", "1 azione", "36 metri", "V, S, M (una manciata di spine)", "Concentrazione, fino a 10 minuti",
    "Un muro di cespugli spinosi (fino a 18 metri di lunghezza, 3 di altezza): chi vi entra o inizia il turno lì subisce 7d8 danni perforanti (metà con il tiro salvezza superato) ed è terreno difficile.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "7d8", tipo: "perforanti", perLivello: "1d8" }, livelloSuperiore: PIU_DADI("1d8") }),
  "Camminare nel Vento": inc(["Druido"], 6, "Trasmutazione", "1 minuto", "9 metri", "V, S, M (fuoco e acqua benedetta)", "8 ore",
    "L'incantatore e fino a dieci creature consenzienti diventano nubi e si muovono nel cielo a velocità di volo 90 metri, con resistenza ai danni non magici."),
  "Parola del Ritorno": inc(["Chierico"], 6, "Evocazione", "1 azione", "1,5 metri", "V", "Istantanea",
    "L'incantatore e fino a cinque creature consenzienti entro 1,5 metri si teletrasportano nel santuario designato, anche su altri piani, purché sia un luogo consacrato alla divinità."),

  // --- 7° livello ---
  "Evocare Celestiale": inc(["Chierico"], 7, "Evocazione", "1 minuto", "27 metri", "V, S", "Concentrazione, fino a 1 ora",
    "Chiama un celestiale di grado sfida 4 o inferiore, che obbedisce e combatte per l'incantatore.",
    { livelloSuperiore: "Con uno slot di 9° livello il celestiale è di grado sfida 5." }),
  "Palla di Fuoco Ritardata": inc(["Mago", "Stregone"], 7, "Invocazione", "1 azione", "45 metri", "V, S, M (una pallina di guano di pipistrello e zolfo)", "Concentrazione, fino a 1 minuto",
    "Un globo di fuoco cresce di 1d6 danni a ogni turno finché dura: quando la concentrazione termina esplode in una sfera di 6 metri infliggendo almeno 12d6 danni da fuoco (metà con il tiro salvezza superato).",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "12d6", tipo: "da fuoco", perLivello: "1d6" }, livelloSuperiore: PIU_DADI("1d6") }),
  "Parola Divina": inc(["Chierico"], 7, "Ammaliamento", "1 azione bonus", "9 metri", "V", "Istantanea",
    "Una parola di potere divino: le creature a scelta con meno di 50 PF subiscono un effetto (assordate, accecate, stordite o morte, a seconda dei PF rimasti) se falliscono il tiro salvezza su Carisma; i celestiali, gli elementali, i folletti e gli immondi sono scacciati al loro piano.",
    { tiroSalvezza: { car: "CAR", effetto: "nessun effetto" } }),
  "Eterealità": inc(["Bardo", "Chierico", "Mago", "Stregone", "Warlock"], 7, "Trasmutazione", "1 azione", "Incantatore", "V, S", "Fino a 8 ore",
    "L'incantatore entra nel Piano Etereo e vi si muove, vedendo il piano di provenienza come nebbia. Non può essere visto né toccato dal Piano Materiale.",
    { livelloSuperiore: "Con slot più alti può portare con sé fino a tre creature per livello oltre il 7°." }),
  "Dito della Morte": inc(["Mago", "Stregone", "Warlock"], 7, "Necromanzia", "1 azione", "18 metri", "V, S", "Istantanea",
    "Energia negativa colpisce una creatura: 7d8 + 30 danni necrotici (metà con il tiro salvezza superato). Se muore per questo incantesimo, si rialza come zombi sotto il controllo dell'incantatore.",
    { tiroSalvezza: { car: "COS", effetto: "metà danni" }, danni: { dado: "7d8", mod: 30, tipo: "necrotici" } }),
  "Tempesta di Fuoco": inc(["Chierico", "Druido", "Stregone"], 7, "Invocazione", "1 azione", "45 metri", "V, S", "Istantanea",
    "Fiamme in un'area di fino a 10 cubi di 3 metri: 7d10 danni da fuoco (metà con il tiro salvezza superato) e incendia gli oggetti infiammabili.",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "7d10", tipo: "da fuoco" } }),
  "Gabbia di Forza": inc(["Bardo", "Mago", "Warlock"], 7, "Invocazione", "1 azione", "30 metri", "V, S, M (polvere di rubino da 1.500 mo)", "1 ora",
    "Una prigione invisibile di forza a forma di cubo o di gabbia con sbarre: nulla vi entra né esce, nemmeno con il teletrasporto, e ci si può muovere solo in forma eterea."),
  "Miraggio Arcano": inc(["Bardo", "Druido", "Mago"], 7, "Illusione", "10 minuti", "Vista", "V, S", "10 giorni",
    "Cambia l'aspetto del terreno su un'area di 2,5 km quadrati, anche edifici e creature, con effetti anche tattili."),
  "Magnifica Dimora di Mordenkainen": inc(["Bardo", "Mago"], 7, "Evocazione", "1 minuto", "90 metri", "V, S, M (un portale in miniatura d'avorio, un pezzo di marmo e un cucchiaino d'argento da 15 mo)", "24 ore",
    "Crea un ingresso a una dimora extradimensionale con arredi, cibo e servitori invisibili per fino a 100 ospiti."),
  "Spada di Mordenkainen": inc(["Bardo", "Mago"], 7, "Invocazione", "1 azione", "18 metri", "V, S, M (una spada di platino in miniatura da 250 mo)", "Concentrazione, fino a 1 minuto",
    "Una spada di forza fluttuante: attacco in mischia con incantesimo, 3d10 danni da forza. Con un'azione bonus si sposta e attacca di nuovo.",
    { attacco: { numero: 1 }, danni: { dado: "3d10", tipo: "da forza", perAttacco: true } }),
  "Spostamento Planare": inc(["Chierico", "Druido", "Mago", "Stregone", "Warlock"], 7, "Evocazione", "1 azione", "Contatto", "V, S, M (una forcella di metallo da 250 mo)", "Istantanea",
    "L'incantatore e fino a otto creature consenzienti si spostano su un altro piano; una creatura ostile può resistere con il tiro salvezza su Carisma.",
    { tiroSalvezza: { car: "CAR", effetto: "non viene spostata" } }),
  "Spruzzo Prismatico": inc(["Bardo", "Mago", "Stregone"], 7, "Invocazione", "1 azione", "Incantatore (cono di 18 metri)", "V, S", "Istantanea",
    "Otto raggi colorati in un cono: ogni creatura fallisce o supera un tiro salvezza e subisce un effetto a caso, tra danni (10d6 di un tipo), accecamento, pietrificazione e invio su un altro piano.",
    { tiroSalvezza: { car: "DES", effetto: "evita l'effetto" } }),
  "Proiettare Immagine": inc(["Bardo", "Mago"], 7, "Illusione", "1 azione", "800 km", "V, S, M (una piccola replica dell'incantatore)", "Concentrazione, fino a 1 giorno",
    "Crea una copia illusoria dell'incantatore in un luogo conosciuto entro gittata: può vedere e sentire attraverso di essa, parlare e lanciare incantesimi come se fosse lì."),
  "Rigenerazione": inc(["Bardo", "Chierico", "Druido"], 7, "Trasmutazione", "1 minuto", "Contatto", "V, S, M (una ruota di preghiera e acqua santa)", "1 ora",
    "La creatura toccata recupera 4d8 + 15 PF subito e 1 PF all'inizio di ogni suo turno; riattacca gli arti persi in 2 minuti."),
  "Resurrezione": inc(["Bardo", "Chierico"], 7, "Necromanzia", "1 ora", "Contatto", "V, S, M (un diamante da 1.000 mo)", "Istantanea",
    "Riporta in vita una creatura morta da non più di un secolo (non di vecchiaia) con tutti i PF; sana le malattie e le ferite ma subisce penalità di −4 a tutti i tiri."),
  "Inversione della Gravità": inc(["Druido", "Mago", "Stregone"], 7, "Trasmutazione", "1 azione", "30 metri", "V, S, M (una calamita e limatura di ferro)", "Concentrazione, fino a 1 minuto",
    "Un cilindro di 15 metri di raggio e 30 di altezza inverte la gravità: le creature e gli oggetti non fissati cadono verso l'alto (danni da caduta di 1d6 ogni 3 metri)."),
  "Sequestrare": inc(["Mago"], 7, "Trasmutazione", "1 azione", "Contatto", "V, S, M (polvere di diamante, smeraldo, rubino e zaffiro da 5.000 mo)", "Finché non viene dissolto",
    "Nasconde una creatura o un oggetto consenzienti alla divinazione e alla vista, in animazione sospesa (se creatura)."),
  "Simulacro": inc(["Mago"], 7, "Illusione", "12 ore", "Contatto", "V, S, M (neve o ghiaccio e polvere di rubino da 1.500 mo)", "Finché non viene dissolto",
    "Crea un duplicato (di ghiaccio o neve) di una bestia o umanoide con la metà dei suoi PF, che obbedisce all'incantatore."),
  "Simbolo": inc(["Bardo", "Chierico", "Druido", "Mago", "Warlock"], 7, "Abiurazione", "1 minuto", "Contatto", "V, S, M (mercurio, fosforo e polvere di diamante e opale da 1.000 mo)", "Finché non viene dissolto o innescato",
    "Traccia un glifo di vari effetti (morte, discordia, paura, dolore, sonno, stordimento, follia) che si attiva quando una creatura lo tocca o entra nell'area.",
    { tiroSalvezza: { car: "COS", effetto: "metà danni o nessun effetto" } }),
  "Teletrasporto": inc(["Bardo", "Mago", "Stregone"], 7, "Evocazione", "1 azione", "3 metri", "V", "Istantanea",
    "L'incantatore e fino a otto creature consenzienti si teletrasportano in un luogo conosciuto: il risultato dipende da quanto bene si conosce la destinazione, con possibili scarti o rischi."),

  // --- 8° livello ---
  "Forme Animali": inc(["Druido"], 8, "Trasmutazione", "1 azione", "9 metri", "V, S", "Concentrazione, fino a 24 ore",
    "Trasforma tutte le creature consenzienti entro gittata in bestie di grado sfida fino a 4 a scelta."),
  "Campo Anti-Magia": inc(["Chierico", "Mago"], 8, "Abiurazione", "1 azione", "Incantatore (sfera di 3 metri)", "V, S, M (limatura di ferro o polvere di ferro)", "Concentrazione, fino a 1 ora",
    "Una sfera di 3 metri di raggio sopprime ogni effetto magico: gli incantesimi, gli oggetti magici e le creature evocate smettono di funzionare finché restano dentro."),
  "Antipatia/Simpatia": inc(["Bardo", "Druido", "Mago"], 8, "Ammaliamento", "1 ora", "18 metri", "V, S, M (alume immerso in aceto)", "10 giorni",
    "Un oggetto o un luogo diventa repulsivo (antipatia) o irresistibile (simpatia) per un tipo di creatura: chi fallisce il tiro salvezza su Saggezza resta spaventato o affascinato.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Clonare": inc(["Mago"], 8, "Necromanzia", "1 ora", "Contatto", "V, S, M (un diamante da 1.000 mo e un pezzo di carne della creatura)", "Istantanea",
    "Crea un clone inerte di una creatura: se l'originale muore, la sua anima si trasferisce nel clone dopo 120 giorni, con i ricordi."),
  "Controllare il Tempo Atmosferico": inc(["Chierico", "Druido", "Mago"], 8, "Trasmutazione", "10 minuti", "Incantatore (raggio di 7,5 km)", "V, S, M (incenso e terra e legno)", "Concentrazione, fino a 8 ore",
    "L'incantatore cambia le condizioni atmosferiche nell'area: precipitazioni, temperatura e vento, cambiando le condizioni gradualmente."),
  "Dominare Mostri": inc(["Bardo", "Mago", "Stregone", "Warlock"], 8, "Ammaliamento", "1 azione", "18 metri", "V, S", "Concentrazione, fino a 1 ora",
    "Come Dominare Persone, ma agisce su qualsiasi creatura: se fallisce il tiro salvezza è affascinata e obbedisce all'incantatore, con nuovi tiri se subisce danni.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" }, livelloSuperiore: "Con slot di 9° livello dura fino a 8 ore." }),
  "Terremoto": inc(["Chierico", "Druido", "Stregone"], 8, "Invocazione", "1 azione", "150 metri", "V, S, M (un pizzico di terra, roccia e argilla)", "Concentrazione, fino a 1 minuto",
    "Scuote il terreno in un'area di 30 metri di raggio: crea fessure, fa crollare strutture e rende il suolo terreno difficile, con danni a chi vi si trova.",
    { tiroSalvezza: { car: "DES", effetto: "nessun effetto" } }),
  "Indebolire la Mente": inc(["Bardo", "Druido", "Mago", "Warlock"], 8, "Ammaliamento", "1 azione", "45 metri", "V, S, M (argilla, cristallo, vetro e minerale)", "Istantanea",
    "Una creatura subisce 4d6 danni psichici e la sua Intelligenza e il Carisma scendono a 1 se fallisce il tiro salvezza: non può lanciare incantesimi né capire il linguaggio finché non è guarita.",
    { tiroSalvezza: { car: "INT", effetto: "nessun effetto" }, danni: { dado: "4d6", tipo: "psichici" } }),
  "Parlantina": inc(["Bardo", "Warlock"], 8, "Trasmutazione", "1 azione", "Incantatore", "V", "1 ora",
    "Per la durata, quando l'incantatore tira 14 o meno su una prova di Carisma considera il risultato come 15, e la magia non può rivelare le sue bugie."),
  "Aura Sacra": inc(["Chierico"], 8, "Abiurazione", "1 azione", "Incantatore (raggio di 9 metri)", "V, S, M (un piccolo reliquiario da 1.000 mo)", "Concentrazione, fino a 1 minuto",
    "Luce divina avvolge le creature alleate: hanno vantaggio ai tiri salvezza e gli attacchi contro di loro hanno svantaggio; gli immondi e i non morti che colpiscono sono accecati."),
  "Nube Incendiaria": inc(["Druido", "Mago", "Stregone"], 8, "Evocazione", "1 azione", "45 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Una nube di fumo di 6 metri di raggio: la visibilità è nulla e chi inizia il turno nell'area subisce 10d8 danni da fuoco (metà con il tiro salvezza superato).",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "10d8", tipo: "da fuoco" } }),
  "Labirinto": inc(["Mago"], 8, "Evocazione", "1 azione", "18 metri", "V, S", "Concentrazione, fino a 10 minuti",
    "Isola una creatura in un semipiano labirintico: ne esce con una prova di Intelligenza con CD 20 (o per un minotauro, automaticamente)."),
  "Mente Vuota": inc(["Bardo", "Mago"], 8, "Abiurazione", "1 azione", "Contatto", "V, S", "24 ore",
    "Una creatura consenziente è immune ai danni psichici, alle divinazioni e alla lettura dei pensieri e non può essere affascinata."),
  "Parola del Potere: Stordire": inc(["Bardo", "Mago", "Stregone", "Warlock"], 8, "Ammaliamento", "1 azione", "18 metri", "V", "Istantanea",
    "Stordisce una creatura con 150 PF o meno entro gittata: ripete un tiro salvezza su Costituzione alla fine di ogni suo turno per terminare l'effetto."),
  "Esplosione Solare": inc(["Druido", "Mago", "Stregone"], 8, "Invocazione", "1 azione", "45 metri", "V, S, M (fuoco e un pezzo di pietra solare)", "Istantanea",
    "Una sfera di luce solare di 18 metri di raggio: 12d6 danni radiosi e cecità (metà dei danni e non accecato se supera il tiro salvezza su Costituzione).",
    { tiroSalvezza: { car: "COS", effetto: "metà danni e non accecato" }, danni: { dado: "12d6", tipo: "radiosi" } }),
  "Telepatia": inc(["Mago"], 8, "Divinazione", "1 azione", "Illimitata", "V, S, M (due metà d'uovo)", "24 ore",
    "Crea un legame telepatico con una creatura conosciuta sullo stesso piano: possono comunicare a qualsiasi distanza e l'incantatore può passare anche immagini e suoni."),
  "Tsunami": inc(["Druido"], 8, "Evocazione", "1 minuto", "Vista", "V, S", "Concentrazione, fino a 6 round",
    "Un muro d'acqua di 90 metri per 90, alto 90 metri, avanza spazzando via le creature: chi lo incontra subisce 6d10 danni contundenti (metà con il tiro salvezza superato) e viene trascinato.",
    { tiroSalvezza: { car: "FOR", effetto: "metà danni" }, danni: { dado: "6d10", tipo: "contundenti" } }),
  "Semipiano": inc(["Mago", "Warlock"], 8, "Evocazione", "1 azione", "18 metri", "S", "1 ora",
    "Crea un portale su una superficie che dà accesso a una stanza vuota di 9 metri di lato, in un semipiano; la stanza svanisce alla fine della durata."),

  // --- 9° livello ---
  "Proiezione Astrale": inc(["Chierico", "Mago", "Warlock"], 9, "Necromanzia", "1 ora", "Contatto", "V, S, M (un giacinto da 1.000 mo e una barra d'argento da 100 mo per creatura)", "Speciale",
    "L'incantatore e fino a otto creature consenzienti proiettano la propria forma astrale su altri piani, lasciando il corpo in animazione sospesa."),
  "Premonizione": inc(["Bardo", "Druido", "Mago", "Warlock"], 9, "Divinazione", "1 minuto", "Contatto", "V, S, M (una piuma di un uccello)", "8 ore",
    "La creatura toccata riceve visioni di ciò che sta per accadere: non può essere colta di sorpresa, ha vantaggio a tiri per colpire, prove e tiri salvezza e gli attacchi contro di lei sono con svantaggio."),
  "Portale": inc(["Chierico", "Mago", "Stregone", "Warlock"], 9, "Evocazione", "1 azione", "18 metri", "V, S, M (un diamante da 5.000 mo)", "Concentrazione, fino a 1 minuto",
    "Apre un portale tra due luoghi su piani diversi, con raggio da 1,5 a 6 metri. L'incantatore può anche chiamare una creatura per nome attraverso il portale."),
  "Imprigionare": inc(["Mago", "Warlock"], 9, "Abiurazione", "1 minuto", "9 metri", "V, S, M (una pergamena e polvere di rubino da 5.000 mo)", "Finché non viene dissolto",
    "Intrappola una creatura che fallisce il tiro salvezza su Saggezza in un modo a scelta (sepoltura, catene, prigione minima, sonno, ecc.), senza che possa muoversi o essere trovata.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Guarigione di Massa": inc(["Chierico"], 9, "Invocazione", "1 azione", "18 metri", "V, S", "Istantanea",
    "Un'ondata di energia guaritrice: fino a sei creature entro gittata recuperano 700 PF in totale, e vengono curate da cecità, sordità e malattie."),
  "Sciame di Meteore": inc(["Mago", "Stregone"], 9, "Invocazione", "1 azione", "1,5 km", "V, S", "Istantanea",
    "Quattro sfere di fuoco cadono su punti scelti dall'incantatore: ogni creatura entro 12 metri subisce 20d6 danni da fuoco e 20d6 danni contundenti (metà con il tiro salvezza superato).",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "20d6", tipo: "da fuoco (più 20d6 contundenti)" } }),
  "Parola del Potere: Guarire": inc(["Bardo"], 9, "Ammaliamento", "1 azione", "Contatto", "V, S", "Istantanea",
    "La creatura toccata recupera tutti i PF, ed è curata da charme, spavento, paralisi, stordimento e altro."),
  "Parola del Potere: Uccidere": inc(["Bardo", "Mago", "Stregone", "Warlock"], 9, "Ammaliamento", "1 azione", "18 metri", "V", "Istantanea",
    "Una creatura con 100 PF o meno muore all'istante; con più PF non ha effetto."),
  "Muro Prismatico": inc(["Bardo", "Mago"], 9, "Abiurazione", "1 azione", "18 metri", "V, S", "10 minuti",
    "Un muro scintillante di sette strati colorati, ciascuno con un effetto diverso (danni, accecamento, pietrificazione, paralisi), blocca ogni accesso.",
    { tiroSalvezza: { car: "COS", effetto: "evita l'effetto" } }),
  "Cambiare Forma": inc(["Druido", "Mago"], 9, "Trasmutazione", "1 azione", "Incantatore", "V, S, M (un cerchietto di giada da 1.500 mo)", "Concentrazione, fino a 1 ora",
    "L'incantatore si trasforma in qualsiasi creatura di grado sfida fino al suo livello e può cambiare forma di nuovo con un'azione."),
  "Tempesta di Vendetta": inc(["Druido"], 9, "Evocazione", "1 azione", "Vista", "V, S", "Concentrazione, fino a 1 minuto",
    "Una nube tempestosa di 108 metri di raggio con effetti crescenti ogni turno (tuono, acido, fulmini, grandine) che infliggono vari danni a chi è sotto.",
    { tiroSalvezza: { car: "COS", effetto: "nessun effetto" } }),
  "Fermare il Tempo": inc(["Mago", "Stregone"], 9, "Trasmutazione", "1 azione", "Incantatore", "V", "Istantanea",
    "L'incantatore ottiene 1d4 + 1 turni consecutivi in cui il tempo si ferma per gli altri: gli effetti che danneggiano gli altri o li coinvolgono terminano l'incantesimo."),
  "Metamorfosi Suprema": inc(["Bardo", "Mago", "Warlock"], 9, "Trasmutazione", "1 azione", "9 metri", "V, S, M (una goccia di mercurio e gomma arabica)", "Concentrazione, fino a 1 ora",
    "Trasforma una creatura in un'altra creatura o un oggetto in una creatura: dopo 1 ora di concentrazione la trasformazione diventa permanente.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Resurrezione Suprema": inc(["Chierico", "Druido"], 9, "Necromanzia", "1 ora", "Contatto", "V, S, M (acqua santa e diamanti da 25.000 mo)", "Istantanea",
    "Riporta in vita una creatura morta da non più di 200 anni, anche senza il corpo, ripristinando i PF e curando tutti i mali e le menomazioni."),
  "Terrore Fantasmagorico": inc(["Mago", "Warlock"], 9, "Illusione", "1 azione", "36 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Il peggiore incubo di ogni creatura scelta entro 9 metri prende forma: chi fallisce il tiro salvezza è spaventato e subisce 10d10 danni psichici ogni turno, finché non supera un nuovo tiro salvezza.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun danno" }, danni: { dado: "10d10", tipo: "psichici" } }),
  "Desiderio": inc(["Mago", "Stregone"], 9, "Invocazione", "1 azione", "Incantatore", "V", "Istantanea",
    "Il più potente incantesimo mortale: può duplicare un altro incantesimo fino all'8° livello o creare un effetto più grande a discrezione del Master, con il rischio di non poter più lanciare Desiderio."),
  "Invulnerabilità": inc(["Mago"], 9, "Abiurazione", "1 azione", "Incantatore", "V, S, M (un frammento di adamantio da 500 mo)", "Concentrazione, fino a 10 minuti",
    "L'incantatore è immune a tutti i danni per la durata."),
};
