import { PIU_DADI, inc, type Voce } from "./incantesimiSottoclassi.ts";

// Incantesimi di 4° e 5° livello del Manuale del Giocatore che non sono altrove nel catalogo
// (descrizioni riassunte, non il testo del manuale).

export const VOCI_M4_5: Record<string, Voce> = {
  // --- 4° livello ---
  "Aura di Vita": inc(["Paladino"], 4, "Abiurazione", "1 azione", "Incantatore (raggio di 9 metri)", "V", "Concentrazione, fino a 10 minuti",
    "Nell'aura le creature alleate hanno resistenza ai danni necrotici e i loro PF massimi non possono essere ridotti. Chi è a 0 PF nell'aura recupera 1 PF all'inizio del turno."),
  "Aura di Purezza": inc(["Paladino"], 4, "Abiurazione", "1 azione", "Incantatore (raggio di 9 metri)", "V", "Concentrazione, fino a 10 minuti",
    "Nell'aura le creature alleate hanno resistenza ai danni da veleno, vantaggio ai tiri salvezza contro condizioni negative (accecato, affascinato, assordato, avvelenato, paralizzato, spaventato, stordito) e le malattie non hanno effetto."),
  "Compulsione": inc(["Bardo"], 4, "Ammaliamento", "1 azione", "9 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Le creature scelte che falliscono il tiro salvezza devono muoversi nella direzione indicata dall'incantatore, usando il loro movimento, a ogni loro turno, finché dura.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" } }),
  "Evocare Elementali Minori": inc(["Druido", "Mago"], 4, "Evocazione", "1 minuto", "27 metri", "V, S", "Concentrazione, fino a 1 ora",
    "Fa apparire elementali sotto il comando dell'incantatore: uno di grado sfida 2, due di 1, quattro di 1/2 o otto di 1/4.",
    { livelloSuperiore: "Il numero di elementali cresce con slot di 6° e 8° livello." }),
  "Evocare Esseri Silvani": inc(["Druido", "Ranger"], 4, "Evocazione", "1 azione", "18 metri", "V, S, M (una bacca di agrifoglio)", "Concentrazione, fino a 1 ora",
    "Fa apparire creature fatate alleate: una di grado sfida 2, due di 1, quattro di 1/2 o otto di 1/4.",
    { livelloSuperiore: "Il numero di creature cresce con slot di 6° e 8° livello." }),
  "Fabbricare": inc(["Mago"], 4, "Trasmutazione", "10 minuti", "36 metri", "V, S", "Istantanea",
    "Trasforma materiali grezzi (fino a 3 metri cubi) in prodotti dello stesso materiale: un ponte di legno da un albero, una corda da canapa, vestiti da lino."),
  "Insetto Gigante": inc(["Druido"], 4, "Trasmutazione", "1 azione", "9 metri", "V, S", "Concentrazione, fino a 10 minuti",
    "Trasforma fino a dieci insetti in versioni giganti sotto il suo controllo (centopiedi, ragni, vespe o scorpioni), una creatura per tipo."),
  "Forziere Segreto di Leomund": inc(["Mago"], 4, "Evocazione", "1 azione", "Contatto", "V, S, M (un forziere squisito da 5.000 mo e la sua replica minuscola)", "Istantanea",
    "Nasconde un forziere e il suo contenuto (fino a 3 metri cubi) nel Piano Etereo: si recupera con la replica minuscola."),
  "Segugio Fedele di Mordenkainen": inc(["Mago"], 4, "Evocazione", "1 azione", "9 metri", "V, S, M (un piccolo fischietto d'argento)", "8 ore",
    "Un cane spettrale invisibile fa la guardia: abbaia se si avvicina una creatura Piccola o più grande e, se è ostile, la morde (4d8 danni perforanti, con un tiro salvezza su Destrezza per dimezzarli)."),
  "Santuario Privato di Mordenkainen": inc(["Mago"], 4, "Abiurazione", "10 minuti", "36 metri", "V, S, M (una lamina di piombo e una lamina d'argento)", "24 ore",
    "Protegge un'area fino a 30 metri di lato: blocca i suoni, oscura la vista, impedisce la divinazione e il teletrasporto e può rendere le creature indifferenti.",
    { livelloSuperiore: "L'area aumenta con slot più alti." }),
  "Sfera Resiliente di Otiluke": inc(["Mago"], 4, "Invocazione", "1 azione", "9 metri", "V, S, M (una semisfera di cristallo e gomma)", "Concentrazione, fino a 1 minuto",
    "Una sfera di forza racchiude una creatura che fallisce il tiro salvezza: è protetta e immobilizzata, nulla l'attraversa e non subisce danni; gli altri possono farla rotolare.",
    { tiroSalvezza: { car: "DES", effetto: "nessun effetto" } }),
  "Assassino Fantasmatico": inc(["Mago"], 4, "Illusione", "1 azione", "36 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "L'incantatore crea nella mente di una creatura il suo peggiore incubo: se fallisce il tiro salvezza è spaventata e subisce 4d10 danni psichici a ogni turno finché non supera un nuovo tiro salvezza.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun danno, l'incantesimo termina" }, danni: { dado: "4d10", tipo: "psichici", perLivello: "1d10" }, livelloSuperiore: PIU_DADI("1d10") }),
  "Punizione Stordente": inc(["Paladino"], 4, "Invocazione", "1 azione bonus", "Incantatore", "V", "Concentrazione, fino a 1 minuto",
    "Il prossimo colpo in mischia con un'arma infligge 4d6 danni psichici extra e il bersaglio ha svantaggio a prove e attacchi finché non supera un tiro salvezza su Saggezza.",
    { tiroSalvezza: { car: "SAG", effetto: "nessuno svantaggio" }, danni: { dado: "4d6", tipo: "psichici" } }),

  // --- 5° livello ---
  "Animare Oggetti": inc(["Bardo", "Mago", "Stregone"], 5, "Trasmutazione", "1 azione", "36 metri", "V, S", "Concentrazione, fino a 1 minuto",
    "Anima fino a dieci oggetti non magici e non indossati: ognuno combatte per l'incantesimo con attacco, CA e PF secondo la taglia (da Minuscolo a Enorme), e un'azione bonus li comanda.",
    { livelloSuperiore: "Un oggetto in più per ogni livello di slot oltre il 5°." }),
  "Guscio Anti-Vita": inc(["Druido"], 5, "Abiurazione", "1 azione", "Incantatore (raggio di 3 metri)", "V, S", "Concentrazione, fino a 1 ora",
    "Una barriera impedisce alle creature viventi, tranne l'incantatore e i suoi alleati, di entrare o di attaccare dall'esterno con armi. Non ferma gli incantesimi."),
  "Risvegliare": inc(["Bardo", "Druido"], 5, "Trasmutazione", "8 ore", "Contatto", "V, S, M (un'agata da 1.000 mo)", "Istantanea",
    "Dà Intelligenza 10 e la capacità di parlare a una bestia con Intelligenza 3 o meno, o a una pianta, rendendola amica dell'incantatore per 30 giorni."),
  "Punizione Esiliante": inc(["Paladino"], 5, "Abiurazione", "1 azione bonus", "Incantatore", "V", "Concentrazione, fino a 1 minuto",
    "Il prossimo colpo con un'arma infligge 5d10 danni da forza extra; se riduce il bersaglio a meno di 50 PF, lo esilia in un semipiano innocuo."),
  "Mano di Bigby": inc(["Mago"], 5, "Invocazione", "1 azione", "36 metri", "V, S, M (un guscio d'uovo e un guanto di pelle di serpente)", "Concentrazione, fino a 1 minuto",
    "Una mano di forza con CA 20 e PF pari ai PF massimi dell'incantatore: con un'azione bonus colpisce (4d8 danni da forza), spinge, afferra o fa da scudo.",
    { attacco: { numero: 1 }, danni: { dado: "4d8", tipo: "da forza", perLivello: "2d8", perAttacco: true }, livelloSuperiore: "I danni aumentano di 2d8 per ogni livello di slot oltre il 5°." }),
  "Cerchio di Potere": inc(["Paladino"], 5, "Abiurazione", "1 azione", "Incantatore (raggio di 9 metri)", "V", "Concentrazione, fino a 10 minuti",
    "Gli alleati nell'aura hanno vantaggio ai tiri salvezza contro incantesimi e effetti magici e dimezzano i danni se superano un tiro salvezza che normalmente li ridurrebbe."),
  "Evocare Salva": inc(["Ranger"], 5, "Evocazione", "1 azione", "Incantatore (raggio di 12 metri)", "V, S, M (una munizione o un'arma da lancio)", "Istantanea",
    "Una pioggia di munizioni colpisce le creature entro 12 metri dall'incantatore: 8d8 danni (metà con il tiro salvezza superato).",
    { tiroSalvezza: { car: "DES", effetto: "metà danni" }, danni: { dado: "8d8", tipo: "dell'arma" } }),
  "Contattare un Altro Piano": inc(["Mago", "Warlock"], 5, "Divinazione", "1 minuto", "Incantatore", "V", "1 minuto",
    "L'incantatore contatta un'entità di un altro piano per porle fino a cinque domande: deve superare un tiro salvezza su Intelligenza o subisce 6d6 danni psichici e rimane folle fino al riposo lungo.",
    { rituale: true, tiroSalvezza: { car: "INT", effetto: "nessun effetto" } }),
  "Contagio": inc(["Chierico", "Druido"], 5, "Necromanzia", "1 azione", "Contatto", "V, S", "7 giorni",
    "Attacco in mischia con incantesimo: una malattia colpisce il bersaglio (cecità, febbre, tremore, putrescenza, affaticamento o piaga) e il bersaglio ha svantaggio ai tiri salvezza su una caratteristica.",
    { attacco: { numero: 1 } }),
  "Creazione": inc(["Mago", "Stregone"], 5, "Illusione", "1 minuto", "9 metri", "V, S, M (un pennello)", "Speciale",
    "Con filamenti d'ombra l'incantatore crea un oggetto di materia vegetale (o minerale) fino a 1,5 metri cubi: cibo, vestiti, una corda, una scala; la durata dipende dal materiale.",
    { livelloSuperiore: "Il volume aumenta di 1,5 metri cubi per ogni livello di slot oltre il 5°." }),
  "Dissolvere il Bene e il Male": inc(["Chierico", "Paladino"], 5, "Abiurazione", "1 azione", "Incantatore", "V, S, M (acqua santa o polvere d'argento e ferro)", "Concentrazione, fino a 1 minuto",
    "Protegge l'incantatore da aberrazioni, celestiali, elementali, folletti, immondi e non morti: hanno svantaggio agli attacchi contro di lui e può scacciarli con il tocco."),
  "Geas": inc(["Bardo", "Chierico", "Druido", "Mago", "Paladino"], 5, "Ammaliamento", "1 minuto", "18 metri", "V", "30 giorni",
    "Impone a una creatura che fallisce il tiro salvezza un comando (fai o non fare qualcosa): se disobbedisce subisce 5d10 danni psichici, una volta al giorno.",
    { tiroSalvezza: { car: "SAG", effetto: "nessun effetto" }, danni: { dado: "5d10", tipo: "psichici" }, livelloSuperiore: "Con uno slot di 7° o 8° livello dura 1 anno; di 9° finché non viene dissolto." }),
  "Ristorare Superiore": inc(["Bardo", "Chierico", "Druido"], 5, "Abiurazione", "1 azione", "Contatto", "V, S, M (polvere di diamante da 100 mo)", "Istantanea",
    "Elimina un effetto debilitante su una creatura toccata: un livello di indebolimento, un incantesimo di charme o pietrificazione, una maledizione, un calo ai punteggi di caratteristica o PF massimi ridotti."),
  "Fuorviare": inc(["Bardo", "Mago", "Warlock"], 5, "Illusione", "1 azione", "Incantatore", "S", "Concentrazione, fino a 1 ora",
    "L'incantatore diventa invisibile e crea un doppio illusorio nella sua posizione; l'illusione si muove e parla mentre l'incantatore è altrove."),
  "Vincolare Esseri Planari": inc(["Bardo", "Chierico", "Druido", "Mago", "Warlock"], 5, "Abiurazione", "1 ora", "18 metri", "V, S, M (un gioiello da 1.000 mo)", "24 ore",
    "Costringe un celestiale, un elementale, un folletto o un immondo a servire per la durata se fallisce il tiro salvezza su Carisma.",
    { tiroSalvezza: { car: "CAR", effetto: "nessun effetto" }, livelloSuperiore: "La durata aumenta con slot di 6° (10 giorni), 7° (30), 8° (180) e 9° livello (366)." }),
  "Legame Telepatico di Rary": inc(["Bardo", "Mago"], 5, "Divinazione", "1 azione", "9 metri", "V, S, M (due gusci d'uovo)", "1 ora",
    "Fino a otto creature consenzienti sono unite da un legame telepatico: possono comunicare a qualsiasi distanza, anche senza lingua comune.",
    { rituale: true }),
  "Reincarnazione": inc(["Druido"], 5, "Trasmutazione", "1 ora", "Contatto", "V, S, M (olio e unguenti rari da 1.000 mo)", "Istantanea",
    "Riporta in vita un umanoide morto da non più di 10 giorni in un nuovo corpo (tirato casualmente), con i ricordi e le capacità."),
  "Faretra Veloce": inc(["Ranger"], 5, "Trasmutazione", "1 azione bonus", "Contatto", "V, S, M (una faretra)", "Concentrazione, fino a 1 minuto",
    "Una faretra toccata produce munizioni a ogni attacco; l'incantatore può attaccare due volte con un'azione bonus con un'arma a distanza."),
  "Cerchio di Teletrasporto": inc(["Bardo", "Mago", "Stregone", "Warlock"], 5, "Evocazione", "1 minuto", "3 metri", "V, M (gessetti rari e inchiostri da 50 mo)", "1 round",
    "Traccia un cerchio di 3 metri che collega a un cerchio permanente noto: chi vi entra viene trasportato subito alla destinazione."),
  "Muro di Forza": inc(["Mago"], 5, "Invocazione", "1 azione", "36 metri", "V, S, M (un pizzico di polvere di gemma trasparente)", "Concentrazione, fino a 10 minuti",
    "Un muro invisibile di forza (10 pannelli di 3 metri, o una cupola di 3 metri di raggio) blocca tutto, resiste ai danni ed è immune a dissolvi magie; solo un incantesimo Disintegrare lo distrugge."),
};
